### ISSUE TITLE
Supply Voltage? 

### ISSUE THREAD

**Issue by ErasedFlash** [petretiandrea/home-assistant-tapo-p100#103]
Is it possible to add grid supply Voltage?

**Comment by petretiandrea** [comment]
What do you mean? Please explain better :)

**Comment by ErasedFlash** [comment]
This is TP-Link Kasa HS110 (Smart plug with energy monitoring). I know that Tapo P110 is similar rebranded TP-Link device. Maybe the chipset is different. Is it possible to show Voltage of the socket? Screenshot attached. 

![Screenshot_20211228_232921_io homeassistant companion android~2](https://user-images.githubusercontent.com/96752411/147686042-e45662b9-fc1b-48b4-aeb4-8af941f040cf.jpg)

**Comment by petretiandrea** [comment]
Actually, P110 does not return information about voltage. This snippet is an example of JSON returned by P110 and as you can see there is no information regarding Voltage.

`{'device_id': '80222EF474BEC01D849DB7F9B01DB7041E800077', 'fw_ver': '1.0.7 Build 210629 Rel.174901', 'hw_ver': '1.0', 'type': 'SMART.TAPOPLUG', 'model': 'P110', 'mac': 'C0-06-C3-E4-AB-5C', 'hw_id': '56DD079101D61D400A11C4A3D41C51DA', 'fw_id': '00000000000000000000000000000000', 'oem_id': 'AE7B616A7168B34151ABBCF86C88DF34', 'overheated': False, 'ip': '192.168.0.59', 'time_diff': 0, 'ssid': 'U0tZNVlSR0s=', 'rssi': -44, 'signal_level': 3, 'latitude': 513553, 'longitude': -18955, 'lang': 'en_US', 'avatar': 'plug', 'region': 'Europe/London', 'specs': '', 'nickname': 'UG93ZXIgRGVzaw==', 'has_set_location_info': True, 'device_on': True, 'on_time': 31570, 'default_states': {'type': 'last_states', 'state': {}}}
{'today_runtime': 1018, 'month_runtime': 31986, 'today_energy': 610, 'month_energy': 24609, 'local_time': '2021-09-03 17:17:26', 'past24h': [22, 18, 19, 18, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 7, 51, 59, 69, 62, 53, 53, 82, 82, 18], 'past30d': [0, 0, 0, 311, 914, 1127, 1690, 1559, 1631, 1683, 1478, 1484, 1347, 837, 833, 979, 681, 644, 1174, 1612, 1034, 843, 857, 348, 0, 0, 0, 266, 667, 610], 'past1y': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23066, 1543], 'past7d': [[26, 26, 25, 26, 25, 25, 26, 26, 28, 27, 29, 27, 23, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 22, 8, 57, 50, 27, 23, 9, 29, 7, 7, 6, 8], [7, 7, 7, 8, 7, 7, 7, 8, 22, 51, 62, 44, 60, 67, 64, 61, 60, 23, 22, 18, 19, 18, 9, 9], [9, 9, 9, 9, 9, 9, 10, 10, 7, 51, 59, 69, 62, 53, 53, 82, 82, 18, 0, 0, 0, 0, 0, 0]], 'current_power': 40274}`
