### ISSUE TITLE
No Host to configure

### ISSUE THREAD

**Issue by MithUK1** [petretiandrea/home-assistant-tapo-p100#105]
Using latest version of home-assistant-tapo-p100 

I have installed via HACs and rebooted my pi device (I have HACs for other addons, so know the score here).

## Describe the bug

I have a username and password for TAPO on the app on my smart phone, but io don;t have a controller... so when (via UI) it asks for "controller" and i leave it blank, It then has a red exclamation and blanks the details for me to try again.

For note I have 3 x TP-Link Tapo L900 strips connected via Wifi and the Tapo app, and can control them with that without issue.  All on latest firmware (1.0.9) and then connected to my home's wifi.

You help / advice trying to get thgis to work in home assistant appreciated.

**Comment by petretiandrea** [comment]
What controller do you see in the UI? There are 3 form fields, the first one is the "Host", so the IP address of your tapo device (this must be set as static one on your router or DHCP). The other 2 fields are about username and password (the same used from Tapo App)

**Comment by MithUK1** [comment]
misunderstanding - all sorted - each light its own host - using its IP (changed to static IP too to avoid change later)
I thought it may need some cloud address whereas its all local.

Thanks, works great

**Comment by Chriss1337** [comment]
Hi there =)
I have try to add my P100 device.
Host is the IP address that they got from my router and username and password is from my Tapo App account but i got every time "Invalid authentication". Have anyone an idea?
Thanks a lot for help =) 
![Screenshot_20220104-125753_Tapo](https://user-images.githubusercontent.com/97064923/148055731-a3eda444-dfe7-4707-b7ac-652028465837.jpg)
![Screenshot_20220104-125658_Home Assistant](https://user-images.githubusercontent.com/97064923/148055735-6b8b9ffb-a76d-493d-9349-02922edfc661.jpg)
