### ISSUE TITLE
Invalid authentication p100

### ISSUE THREAD

**Issue by Chriss1337** [petretiandrea/home-assistant-tapo-p100#106]
Hi there =)
I have try to add my P100 device.
Host is the IP address that they got from my router and username and password is from my Tapo App account but i got every time "Invalid authentication". Have anyone an idea?
Thanks a lot for help =) 
![Screenshot_20220104-125753_Tapo](https://user-images.githubusercontent.com/97064923/148055731-a3eda444-dfe7-4707-b7ac-652028465837.jpg)
![Screenshot_20220104-125658_Home Assistant](https://user-images.githubusercontent.com/97064923/148055735-6b8b9ffb-a76d-493d-9349-02922edfc661.jpg)

_Originally posted by @Chriss1337 in https://github.com/petretiandrea/home-assistant-tapo-p100/issues/105#issuecomment-1004747937_

**Comment by petretiandrea** [comment]
Can you try this snippet of code? Replace "<email>" with your username with right case and report here the results. 

```python
import asyncio

from plugp100 import TapoApiClient


async def main():
    # create generic tapo api
    sw = TapoApiClient("<ip>", "<email>", "<passwd>")
    await sw.login()
    print(await sw.get_state_as_dict())

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.run_until_complete(asyncio.sleep(0.1))
loop.close()
```

**Comment by Quixus** [comment]
I'm having the same issue. The email address is entered exactly like it is in the tapo app, the password was pasted from my password manager. Just to be sure, at host I am supposed to enter the IP address of the bulb/switch I'm trying to integrate, right?

**Comment by srd424** [comment]
I'm using plugp100 directly (can't report issues over there), and keep getting:
```
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://p110.lan/app')
```
I wonder if TP-Link have changed something? https://github.com/fishbigger/TapoP100 works with my device, but I see that calls out to TP-link's servers, I was hoping to use a local-only solution after account creation. Device details:
```
Model: Tapo P110
Hardware version: 1.0
Firmware version: 1.0.7 Build 210629 Rel. 174901
```

**Comment by petretiandrea** [comment]
I don't know why in plugp100 repo issues are disabled, now it's enabled. So you can report it here https://github.com/petretiandrea/plugp100/issues. Anyway, I see "http://p110.lan/app" in your snippet, instead of using a hostname try to use a "direct" ip address and report any issue

**Comment by srd424** [comment]
https://github.com/petretiandrea/plugp100/pull/4 solves my problem! Don't know why nobody else had hit this... it goes back to 2.1.1 I think so perhaps unlikely to be the cause of the problems in this issue.

**Comment by petretiandrea** [comment]
> I'm having the same issue. The email address is entered exactly like it is in the tapo app, the password was pasted from my password manager. Just to be sure, at host I am supposed to enter the IP address of the bulb/switch I'm trying to integrate, right?

Yes right

**Comment by Chriss1337** [comment]
> @Chriss1337 I was having the same issue, The Username field is case sensitive, can you verify that the username capitalisation you are entering matches the capitalisation in the "me" page on the tapo app.
> 
> @petretiandrea I dont know if you are able to make a change to make the login case insensitive, I'm guessing its an issue on the tapo side, If not please consider adding a warning in the config step to make people aware of the issue.

Yeah it works^^ Thank you
