### ISSUE TITLE
Full P110 configuration via yaml

### ISSUE THREAD

**Issue by FishCoding** [petretiandrea/home-assistant-tapo-p100#111]
Firstly, thanks for the project :)

Secondly, I would like to ask if it is possible to declare via yaml the switch and sensors that appear in Home Assistant if I do the configuration of the P110 plug via GUI.

Thanks in advance.

**Comment by petretiandrea** [comment]
In home assistant, you need to decide if you want to configure a device using GUI or Yaml. You can't configure the same entity from both.
