### ISSUE TITLE
Strip led L900

### ISSUE THREAD

**Issue by millenniumy2k** [petretiandrea/home-assistant-tapo-p100#129]
I have an L900 RGB led strip, it turns on and off but does not change color. is it possible to integrate it?

**Comment by millenniumy2k** [comment]
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.tapo.common_setup
Source: helpers/update_coordinator.py:219
Integration: Tapo Controller (documentation, issues)
First occurred: 16:04:43 (1 occurrences)
Last logged: 16:04:43

Error fetching tapo data:

**Comment by petretiandrea** [comment]
Colors for L900 are already supported by the integration, so you can try to re-add your strip or/and restart home assistant

**Comment by mario872** [comment]
Hello, I'm having the same issue. I'm able to turn on/off, decrease/increase brightness and use effects, but cannot change the colour. I have re-added the strip and restarted home assistant. Using an L900-5. Happy to provide screenshot or video if needed.
Also, sorry if I'm not using the issues sections right, I'm a noob.
