### ISSUE TITLE
integration not working, found copy, that working.

### ISSUE THREAD

**Issue by Psytoshgen** [petretiandrea/home-assistant-tapo-p100#137]
integration not working (and didn't shows at integrations in home assistant), also I found aanother one, that works fine... how that?

https://github.com/fishbigger/HomeAssistant-Tapo-P100-Control

**Comment by petretiandrea** [comment]
A lot of people are using this integration successfully. What issue do you have?

**Comment by petretiandrea** [comment]
@Psytoshgen please read the updated readme.md and follow the steps to install and add devices

**Comment by Psytoshgen** [comment]
yes, after update its works fine, and shows some info. Thank you. And sorry.
