### ISSUE TITLE
Light State not refreshing 

### ISSUE THREAD

**Issue by Jrgf27** [petretiandrea/home-assistant-tapo-p100#141]
Found another interesting bug, unsure if it is with the integration or home assistant. 

I was trying to pass some data in scripts to turn on the lights with specific brightness and/or colour temps, as seen below:

service: light.turn_on
data_template:
  entity_id: '{{ entity }}'
  brightness_pct: 100

When running the script with a specific light, the light does turn on but the "On" state is not visible in either Home Assistant or the Tapo App. In both softwares, the light is considered off although it is physically on. This is using the same L530 we used to debug the brightness and colour temp bug in a previous issue, running on 1.2.8 (I can post the software and hardware details again if needed). 

On the other hand, if I run the script without passing any other data, apart from entity_id, the script works fine and the state is correctly refreshed in both tapo app and HA. 

service: light.turn_on
data_template:
  entity_id: '{{ entity }}'

**Comment by petretiandrea** [comment]
Can you post the log after executing the service with brightness? In the log, there should be strings like: `Setting brightness...`

**Comment by Jrgf27** [comment]
Reinstalled the integration and seems to be fine, I probably did something wrong in my previous manual installation.
