### ISSUE TITLE
Setup failed with core-2022.3.1

### ISSUE THREAD

**Issue by giga89** [petretiandrea/home-assistant-tapo-p100#147]
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 10:20:22 (1 occurrences)
Last logged: 10:20:22

Setup failed for custom integration tapo: Requirements for tapo not found: ['plugp100==2.1.10b1']

core-2022.3.1
supervisor-2022.01.1
Home Assistant OS 7.4

With core-2022.2.1 everything it's ok

**Comment by petretiandrea** [comment]
Which version of integration are you installing? The latest version use 2.1.13b1, see: https://github.com/petretiandrea/home-assistant-tapo-p100/blob/main/custom_components/tapo/manifest.json#L10

**Comment by giga89** [comment]
You are right @petretiandrea . After update everything gone well.
Thank you so much
