### ISSUE TITLE
Setup failed for custom integration tapo

### ISSUE THREAD

**Issue by solidforce** [petretiandrea/home-assistant-tapo-p100#149]
Hi, after upgradinh HA to 2022.3.0 my TapoP100 plugin broke down. I'm running HA on Synology NAS:
OS: DSM 7.0.1-42218 Update 2
CPU: INTEL Celeron J3355 x64
TapoP100: v1.2.9
HACS: 1.23.0

Version | core-2022.3.0
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 4.4.180+
CPU Architecture | x86_64

Logs:

`Logger: homeassistant.setup
Source: setup.py:162
First occurred: 09:17:05 (1 occurrences)
Last logged: 09:17:05

Setup failed for custom integration tapo: Requirements for tapo not found: ['plugp100==2.1.13b1'].

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 09:15:56 (3 occurrences)
Last logged: 09:17:05

Unable to install package plugp100==2.1.13b1: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [30 lines of output] Testing support for clang Target does not support clang Testing support for gcc Target does not support gcc Testing support for stdint.h header Target does not support stdint.h header Testing support for 128-bit integer Target does not support 128-bit integer Testing support for cpuid.h header Target does not support cpuid.h header Testing support for intrin.h header Target does not support intrin.h header Testing support for posix_memalign Target does not support posix_memalign Testing support for memalign Target does not support memalign Testing support for SSE2(intrin.h) Target does not support SSE2(intrin.h) Testing support for SSE2(x86intrin.h) Target does not support SSE2(x86intrin.h) Testing support for SSE2(emmintrin.h) Target does not support SSE2(emmintrin.h) Warning: compiler does not support AESNI instructions Warning: compiler does not support CLMUL instructions running bdist_wheel running build running build_py running build_ext building 'Crypto.Hash._MD2' extension error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for pycryptodome error: subprocess-exited-with-error × Running setup.py install for pycryptodome did not run successfully. │ exit code: 1 ╰─> [32 lines of output] Testing support for clang Target does not support clang Testing support for gcc Target does not support gcc Testing support for stdint.h header Target does not support stdint.h header Testing support for 128-bit integer Target does not support 128-bit integer Testing support for cpuid.h header Target does not support cpuid.h header Testing support for intrin.h header Target does not support intrin.h header Testing support for posix_memalign Target does not support posix_memalign Testing support for memalign Target does not support memalign Testing support for SSE2(intrin.h) Target does not support SSE2(intrin.h) Testing support for SSE2(x86intrin.h) Target does not support SSE2(x86intrin.h) Testing support for SSE2(emmintrin.h) Target does not support SSE2(emmintrin.h) Warning: compiler does not support AESNI instructions Warning: compiler does not support CLMUL instructions running install /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py running build_ext building 'Crypto.Hash._MD2' extension error: command 'gcc' failed: No such file or directory [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. WARNING: No metadata found in /usr/local/lib/python3.9/site-packages error: legacy-install-failure × Encountered error while trying to install package. ╰─> pycryptodome note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.`

**Comment by petretiandrea** [comment]
Try to install `build-essential` from linux which include c compiler. Also install `python-dev`

**Comment by solidforce** [comment]
Thank you @petretiandrea , installing build-base and python3-dev helped.
