### ISSUE TITLE
Second L920 Stripe 

### ISSUE THREAD

**Issue by TimoFeist** [petretiandrea/home-assistant-tapo-p100#163]
Hey there,

i hope anyone can help me, i have more than one LED Stripe L920, but i can add only one Controller to my Devicelist. I try to it manuel in the configuration.yaml but it doesnt work.

Here is a Screenshot from the Error Message, when i try to bind a second Controller:

![grafik](https://user-images.githubusercontent.com/69906940/161769919-e701ddf4-610a-4e33-91d8-50967a2d7237.png)

I wish a nice Week, greetings 
Timo

**Comment by petretiandrea** [comment]
Can you provide me the log of home assistant after getting this error?
