### ISSUE TITLE
Problem re-adding devices

### ISSUE THREAD

**Issue by Lydras** [petretiandrea/home-assistant-tapo-p100#167]
Generally I have always had an issue where some of my tapo devices drop off the integration following a home assistant restart. Which I guess relates to those devices changing IP address. This I have addressed by giving them static IPs. However in attempting to re add the devices this time, I am now getting an error I haven't seen before: 
<img width="333" alt="image" src="https://user-images.githubusercontent.com/82093023/163362455-3d1df0a8-15d4-49b8-8045-c287a44fceca.png">
And it won't add the device any longer. I have 6 devices in total. Currently 4 of them are offline and 2 are still online. I deleted the offline devices and have not been able to readd any of them.
I am running v.1.2.10 of your integration and the latest version of HA, HACS, etc.

**Comment by petretiandrea** [comment]
Can you provide me the log of home assistant when this error happens?

**Comment by Lydras** [comment]
I did check the logs and didn't see anything in there regarding it. However, I tried again after an hour or so and it all worked correctly. So maybe it was just one of those things. Happy to withdraw this issue.
