### ISSUE TITLE
Decreasing month energy value

### ISSUE THREAD

**Issue by JFox-sk** [petretiandrea/home-assistant-tapo-p100#172]
Hi, my Tapo p110 month energy entity is decreasing - always at the midnight jumps down (see the image below).
![image](https://user-images.githubusercontent.com/2402129/164726740-8eee6e0e-8f32-4d04-ba56-d217de624448.png)

## Version of the custom_component
v1.2.10

## Debug log
No logs found about this integration.

**Comment by JFox-sk** [comment]
Hi, 
I looked at the source code a bit and I think I know the reason for the problem. Tapo p110 month energy entity using today_energy property of plugp100 package. And this package returns this value for the sum of energy for the last 30 days, not for the current month (starting from the first day of the current month), so that explains this decrease (e.g.: when I consume less energy for the last days). And Home assistant Energy dashboard can not work correctly with such entity. We can fix it by using data for the current month (starting from the first day of the current month) - I will try to send pull request to both [plugp100](https://github.com/petretiandrea/plugp100) and this repository.

**Comment by petretiandrea** [comment]
Hi, many thanks for your contribution. I will start the release process for plugp100 and for this integration
