### ISSUE TITLE
TP-LINK L520E

### ISSUE THREAD

**Issue by thanasiskalos** [petretiandrea/home-assistant-tapo-p100#175]
Hello

I have used the integration to control successfully Tapo devices ( P100 , L530E). 
Today I added the TAPO L520E and although it was discovered only 2 entitles were identified  - RF Signal and overheat.
Unfortunately ON/Off and brightness  has not been identified so I cannot control the bulb.

Should I provide any assistance with logs please let me know to submit them.

![image](https://user-images.githubusercontent.com/69139820/166674813-99c2524d-3bb6-4ee7-80aa-a40b05dc7e30.png)

Best Regards and thanks for your efforts. 
```

**Comment by thanasiskalos** [comment]
Hello

I added the following line on const.py , restarted the HA and all functionality has been available for L520E

SUPPORTED_DEVICE_AS_LIGHT = {
    "l920": SUPPORT_BRIGHTNESS | SUPPORT_COLOR,
    "l900": SUPPORT_BRIGHTNESS | SUPPORT_COLOR,
    "l530": SUPPORT_BRIGHTNESS | SUPPORT_COLOR_TEMP | SUPPORT_COLOR,
    "l510": SUPPORT_BRIGHTNESS,
    **"l520": SUPPORT_BRIGHTNESS,**

Pease update the sources for any future use.

Regards

**Comment by petretiandrea** [comment]
Thanks for support, you can try to open a pull request with these changes. I will approve and release a new version

**Comment by petretiandrea** [comment]
New release 1.2.12 contains the l520 support :)

**Comment by Sr-psycho** [comment]
Greetings! I have the same problem with Tapo L520E.

**Comment by Nerd0o0** [comment]
Same problem with Tapo L530E, displays as L530 without color control. 
Integration version 3.0.0 (HACS)
Core 2024.3.1
Supervisor 2024.03.0
Operating System 12.1
Frontend 20240307.0
