### ISSUE TITLE
Is this local or does it need the internet ?

### ISSUE THREAD

**Issue by atv2016** [petretiandrea/home-assistant-tapo-p100#189]
Just wondering if it will keep wondering or if i'm reliant on the internet/tp link.

**Comment by jzeb11** [comment]
I would like to know this too.

**Comment by petretiandrea** [comment]
It relies on LAN, so doesn't work through internet. The only way to do that is by opening tapo device's port on your router. You can provide a public ip to your tapo device and use the ip to connect to it.

**Comment by NePoCz** [comment]
Hi, I know this is closed, but I think there was a slight misuderstaning. I believe the initial question was more about "Does the Tapo device need internet access, or can it work purely on LAN without internet?" while your answer is about it being controlled over internet. I am also interested in this and would like to block internet trafic for the Tapo device. From what I gathered, internet access is needed for the initial setup, but then it all should work purely over LAN - is this correct?

**Comment by petretiandrea** [comment]
> Hi, I know this is closed, but I think there was a slight misuderstaning. I believe the initial question was more about "Does the Tapo device need internet access, or can it work purely on LAN without internet?" while your answer is about it being controlled over internet. I am also interested in this and would like to block internet trafic for the Tapo device. From what I gathered, internet access is needed for the initial setup, but then it all should work purely over LAN - is this correct?

The device needs internet access to synchronize with tapo cloud, especially for credentials, a missing internet access could lead into "Invalida authentication error":
