### ISSUE TITLE
HomeAssistant 2022.7.0 setup.py

### ISSUE THREAD

**Issue by lannon89** [petretiandrea/home-assistant-tapo-p100#200]
Upgraded to HomeAssistant 2022.7.0 and the tapo hacs integration has stopped working. Log file reads:
Setup failed for custom integration tapo: Requirements for tapo not found: ['plugp100==2.1.14'].
10:56:04 PM – (ERROR) setup.py

Is this just me?

**Comment by d3sbo** [comment]
no me to

**Comment by lannon89** [comment]
Going to close, didn't see the ticket below

**Comment by petretiandrea** [comment]
Refers to #199
