### ISSUE TITLE
Unable to load Tapo integration

### ISSUE THREAD

**Issue by pvanleen** [petretiandrea/home-assistant-tapo-p100#203]
Getting the following error in logs since upgrading HA last two updates....

Logger: homeassistant.setup
Source: setup.py:162
First occurred: 18:57:09 (1 occurrences)
Last logged: 18:57:09

Setup failed for custom integration tapo: Requirements for tapo not found: ['plugp100==2.1.14'].

Have been unable to remove integration although I have reloaded it.

**Comment by RandumbPrints** [comment]
I have a feeling this maybe the change to the python version that HA Core now ships with, they have updated it to 3.10 so I think the dev will have to update the python maybe? I'm theorising

**Comment by tarokker** [comment]
The author is working on it:
https://github.com/petretiandrea/home-assistant-tapo-p100/issues/199#issuecomment-1177879540

**Comment by petretiandrea** [comment]
Refers to #199
