### ISSUE TITLE
allow port number in host field

### ISSUE THREAD

**Issue by wernerkarlheisenberg** [petretiandrea/home-assistant-tapo-p100#219]
## Version of the custom_component
v1.2.14

## Configuration
Problem occurs when trying to add the integration via the UI.

## Describe the bug
When I try to specify a host including a port number (format XXX.XXX.XXX.XXX:YYYY) in the host field, it immediately returns an empty error. I would like to add a port number after the IP as I'm using port forwarding.

![image](https://user-images.githubusercontent.com/20357407/181821484-91298aae-83b3-48f3-b776-b01355b82d6c.png)
 
## Debug log
No debug log entries for plugp100 are created.

**Comment by petretiandrea** [comment]
Why you need to specify port number? by default, tapo devices runs on 80? Are you trying to access from remote with a port-forwarding mapping?

**Comment by wernerkarlheisenberg** [comment]
The exact use case is a bit different, but indeed I'm using port forwarding and hence need to be able to specify a port number.

petretiandrea ***@***.***> schreef op 1 augustus 2022 07:36:25 CEST:

**Comment by wernerkarlheisenberg** [comment]
Small update. Instead of using the GUI, I updated configuration.yaml.

switch:
  platform: tapo
  host: "XXX:YYY"
  username: "XXX"
  password: "XXX"

This works, the plug is added as a switch. However, it is a P110 with energy monitor capabilities. So I believe I should add it as a sensor in order to have the energy consumption values. Unfortunately, when I'm adding

sensor:
  platform: tapo
  host: "XXX:YYY"
  username: "XXX"
  password: "XXX"

the below error appear in the logs

2022-08-05 17:44:00.448 ERROR (MainThread) [homeassistant.components.sensor] The tapo platform for the sensor integration does not support platform setup. Please remove it from your config.

**Comment by wernerkarlheisenberg** [comment]
By commenting line 87 and 88 in config_flow.py I managed to get it working. Maybe you could update the regex to allow a port number being specified.

**Comment by wernerkarlheisenberg** [comment]
I'm reopening this issue as I noticed that my configuration is no longer working since I upgraded to the latest version. I believe the problem has been (re)introduced in version 2.7.0.

As you can see in the below screenshot, :80 seems to be added to the configured hostname, independent on whether the configured hostname already contains a port number or not. 

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/20357407/bf1446e6-38f0-4ec1-b253-eab0361ca381)
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/20357407/94e3bec0-a5c3-4521-aa2f-1546c574cd8d)

FYI, when I remove an existing configured item and try to add it again, it doesn't work either. I get the below error message.
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/20357407/c07c94ca-5dce-45ad-b745-9df63915b46c)
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/20357407/589c00ec-9e59-4079-bc18-1af35b21a699)
