### ISSUE TITLE
HACS integration successfull, but can't see TAPO in HA Integrations

### ISSUE THREAD

**Issue by igiffrekt** [petretiandrea/home-assistant-tapo-p100#225]
I installed the TAPO Controller HACS integration successfully
![image](https://user-images.githubusercontent.com/31223770/183258511-0069ca8d-0630-4acc-8dc4-540752f86fd7.png)

But when I search for TAPO in HA Integrations I don't see it
![image](https://user-images.githubusercontent.com/31223770/183258527-5375e435-f74f-4586-9217-9a6913cced4a.png)

**Comment by igiffrekt** [comment]
Sorry, I gave it a go again a few times, and some hours later it appeared anyways.

**Comment by RestOp** [comment]
The same and not found in integrations till now.
Rpi 4
Hassos
Everything are the latest versions
