### ISSUE TITLE
Add energy to bulb l510

### ISSUE THREAD

**Issue by jjdiazgarcia** [petretiandrea/home-assistant-tapo-p100#226]
**Is your feature request related to a problem? Please describe.**
I have added some new tapo L510 bulbs to my HA and only three entities are added. I have checked official application and power/energy can be measured for L510 bulbs.

**Describe the solution you'd like**
I would like to be able to show power/energy of L510 bulb un HA

**Additional context**
Here you are some screenshot of entities added in HA and official app.

![Screenshot_2022-08-07-00-21-14-694_io homeassistant companion android](https://user-images.githubusercontent.com/15831309/183268047-65f9545b-5c48-4b9a-81c5-bfd94ced3579.jpg)

![Screenshot_2022-08-07-00-42-51-658_com tplink iot](https://user-images.githubusercontent.com/15831309/183268122-585e9dce-c516-437b-85bb-29d33363b98d.jpg)

I have had a look how it is implemented but I have some questions.

Should it be implemented for all bulbs or only for L510?

I would like to know if it only required to add something like https://github.com/petretiandrea/home-assistant-tapo-p100/blob/2ac821f59289dd54005482a1e878a770e04a9c78/custom_components/tapo/sensor.py#L31 Of course, create a new variable for bulbs to use it only for energy. If so I can create a PR to add this feature. Let me know if my solution is good.

**Comment by petretiandrea** [comment]
Are you sure that L510 supports power monitoring? Here https://www.tp-link.com/it/home-networking/smart-bulb/tapo-l510e/ there is no reference about power meter. I think is an app estimation
