### ISSUE TITLE
L530 Controls are unreliable since the last few updates

### ISSUE THREAD

**Issue by dragosdmc** [petretiandrea/home-assistant-tapo-p100#227]
Hello,

Since the last few months the controls don't work properly for L530 lights in the sense that:
-lights stopped gradually turning on. They turn on instantly with a bit of delay
-color changing crashes stops the connection if you want to cycle through colors. After a few cycles, the bulb loses connection and starts doing a rainbow effect
-what bothers me the most: I have a script that lights up my 3 bulbs, consecutively, to 3 different colors at about 15% intensity. Since updating HA, when running the script the colors change correctly, however a flash occurs before reaching the correct status. 
It seems like it first tries to reach it's default state, then change to the color from the script a few milliseconds later

I run HA 2022.8.x, just updated from 2022.2.x. Things where running fine on 2022.2.x. I also updated the firmware from the tapo app to 1.2.2 build 20220110 Rel.72329 and the Tapo integration for HACS running 1.2.14 with HACS version 1.26.2. I should mention that this has happened for a while, this is the reason why I used HA v2022.2.x

Thank you!

**Comment by petretiandrea** [comment]
I need some logs

**Comment by dragosdmc** [comment]
Hello. First of all sorry for the late response. Below you can find some logs. I have turned on and off the light 2 times using a standard button, then I ran a script that automatically turns on the light to a color/brightness that I set.

[home-assistant_tapo_2022-12-19T22-57-33.470Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/10263374/home-assistant_tapo_2022-12-19T22-57-33.470Z.log)
