### ISSUE TITLE
P115 energy meter support?

### ISSUE THREAD

**Issue by roelofvandijk** [petretiandrea/home-assistant-tapo-p100#240]
Is reading out the P115 energy measurements also supported?

**Comment by xanderificnl** [comment]
Yes. 

For the record:

![image](https://user-images.githubusercontent.com/8600870/188398787-1bc58b7a-09cf-45b8-a116-5f8a57f2a90d.png)
![image](https://user-images.githubusercontent.com/8600870/188398912-a6641f52-933c-41fb-a111-9b2e547f874f.png)

**Comment by roelofvandijk** [comment]
Fantastic, thank you!
