### ISSUE TITLE
Tapo lightstrip 930

### ISSUE THREAD

**Issue by Thorvarium** [petretiandrea/home-assistant-tapo-p100#242]
Can you add support to the lightstrip tapo 930? Just basic support on/off. I would greatly appreciate it.
Right now on the device manager it only shows the overheat sensor and the signal level sensor, but no light

for the tapo 920 it shows the light and both sensors.

I have one each if you need someone to do testing or to grab some kind of needed data.

**Comment by petretiandrea** [comment]
I need a state report of tapo device

**Comment by Thorvarium** [comment]
> I need a state report of tapo device

Can you guide me to get this state report? I am unsure where to retrieve from

**Comment by petretiandrea** [comment]
You must install plugp100 library by `pip install plugp100==2.1.18` and run this python script:
```python
import asyncio
from plugp100 import TapoApiClient


async def main():
    # create generic tapo api
    sw = TapoApiClient("<ip>", "<email>", "<passwd>")
    await sw.login()
    state = await sw.get_state()
    print(state.state)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.run_until_complete(asyncio.sleep(0.1))
loop.close()
```

**Comment by Thorvarium** [comment]
> You must install plugp100 library by `pip install plugp100==2.1.18` and run this python script:
> 
> ```python
> import asyncio
> from plugp100 import TapoApiClient
> 
> 
> async def main():
>     # create generic tapo api
>     sw = TapoApiClient("<ip>", "<email>", "<passwd>")
>     await sw.login()
>     state = await sw.get_state()
>     print(state.state)
> 
> loop = asyncio.get_event_loop()
> loop.run_until_complete(main())
> loop.run_until_complete(asyncio.sleep(0.1))
> loop.close()
> ```

3c347d1ae9fcbffa340252d757e223eb527e1b08
{'device_id': '80230A9A889D0FC2F6AF79287F62F6D21FFA4B74', 'fw_ver': '1.0.9 Build 220727 Rel.150045', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L930', 'mac': '28-87-BA-88-50-6E', 'hw_id': '630F72CFA5B3DE1350011A0D04DE98B5', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '7B1BE6CFC4CF7D31E82C1CCD46D1FCFB', 'color_temp_range': [2500, 6500], 'overheated': False, 'ip': '192.168.4.88', 'time_diff': -300, 'ssid': 'b2NhdmFsb2JlYmVsZWl0ZQ==', 'rssi': -56, 'signal_level': 2, 'latitude': 280312, 'longitude': -825223, 'lang': 'en_US', 'avatar': 'light_strip', 'region': 'America/New_York', 'specs': '', 'nickname': 'RGVzayBMaWdodA==', 'has_set_location_info': True, 'lighting_effect': {'enable': 1, 'id': 'TapoStrip_7CC5y4lsL8pETYvmz7UOpQ', 'name': 'Rainbow', 'custom': 0, 'brightness': 100, 'display_colors': [[0, 100, 100], [100, 100, 100], [200, 100, 100], [300, 100, 100]]}, 'music_rhythm_enable': False, 'music_rhythm_mode': 'single_lamp', 'device_on': True, 'brightness': 100, 'hue': 0, 'saturation': 100, 'color_temp': 4500, 'default_states': {'type': 'last_states', 'state': {'lighting_effect': {'type': 'sequence', 'id': 'TapoStrip_7CC5y4lsL8pETYvmz7UOpQ', 'name': 'Rainbow', 'enable': 1, 'segments': [0], 'expansion_strategy': 1, 'transition': 1500, 'duration': 0, 'brightness': 100, 'sequence': [[0, 100, 100], [100, 100, 100], [200, 100, 100], [300, 100, 100]], 'spread': 12, 'direction': 1, 'repeat_times': 0, 'custom': 0, 'display_colors': [[0, 100, 100], [100, 100, 100], [200, 100, 100], [300, 100, 100]]}}}}

**Comment by petretiandrea** [comment]
Nice work. Can you take 2/3 app screenshot with color wheel related state change by python script? 

You can follow this approach:
1. open app change color
2. take a screenshot
3. execute the script and save the state (in this way I can associate the state to app screenshot)
4. repeat 2 or 3 times steps 1,2,3

**Comment by Thorvarium** [comment]
> Nice work. Can you take 2/3 app screenshot with color wheel related state change by python script?
> 
> You can follow this approach:
> 
> 1. open app and change color
> 2. take a screenshot
> 3. execute the script and save the state (in this way I can associate the state to app screenshot)
> 4. repeat 2 or 3 times steps 1,2,3

sure thing:

red:
![Screenshot_20220915-170027_Tapo](https://user-images.githubusercontent.com/6555325/190508194-2aef0f8a-504d-4976-a599-eb1fe390addb.jpg)
3c347d1ae9fcbffa340252d757e223eb527e1b08
{'device_id': '80230A9A889D0FC2F6AF79287F62F6D21FFA4B74', 'fw_ver': '1.0.9 Build 220727 Rel.150045', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L930', 'mac': '28-87-BA-88-50-6E', 'hw_id': '630F72CFA5B3DE1350011A0D04DE98B5', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '7B1BE6CFC4CF7D31E82C1CCD46D1FCFB', 'color_temp_range': [2500, 6500], 'overheated': False, 'ip': '192.168.4.88', 'time_diff': -300, 'ssid': 'b2NhdmFsb2JlYmVsZWl0ZQ==', 'rssi': -53, 'signal_level': 2, 'latitude': 280312, 'longitude': -825223, 'lang': 'en_US', 'avatar': 'light_strip', 'region': 'America/New_York', 'specs': '', 'nickname': 'RGVzayBMaWdodA==', 'has_set_location_info': True, 'lighting_effect': {'enable': 0, 'id': 'TapoStrip_7CC5y4lsL8pETYvmz7UOpQ', 'name': 'Rainbow', 'custom': 0, 'brightness': 100, 'display_colors': [[0, 100, 100], [100, 100, 100], [200, 100, 100], [300, 100, 100]]}, 'music_rhythm_enable': False, 'music_rhythm_mode': 'single_lamp', 'device_on': True, 'brightness': 100, 'hue': 0, 'saturation': 100, 'color_temp': 0, 'default_states': {'type': 'last_states', 'state': {'brightness': 100, 'hue': 0, 'saturation': 100, 'color_temp': 0}}}


blue:
![Screenshot_20220915-170030_Tapo](https://user-images.githubusercontent.com/6555325/190508202-d719a50c-de08-46f6-be82-178cf3ccf748.jpg)
3c347d1ae9fcbffa340252d757e223eb527e1b08
{'device_id': '80230A9A889D0FC2F6AF79287F62F6D21FFA4B74', 'fw_ver': '1.0.9 Build 220727 Rel.150045', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L930', 'mac': '28-87-BA-88-50-6E', 'hw_id': '630F72CFA5B3DE1350011A0D04DE98B5', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '7B1BE6CFC4CF7D31E82C1CCD46D1FCFB', 'color_temp_range': [2500, 6500], 'overheated': False, 'ip': '192.168.4.88', 'time_diff': -300, 'ssid': 'b2NhdmFsb2JlYmVsZWl0ZQ==', 'rssi': -53, 'signal_level': 2, 'latitude': 280312, 'longitude': -825223, 'lang': 'en_US', 'avatar': 'light_strip', 'region': 'America/New_York', 'specs': '', 'nickname': 'RGVzayBMaWdodA==', 'has_set_location_info': True, 'lighting_effect': {'enable': 0, 'id': 'TapoStrip_7CC5y4lsL8pETYvmz7UOpQ', 'name': 'Rainbow', 'custom': 0, 'brightness': 100, 'display_colors': [[0, 100, 100], [100, 100, 100], [200, 100, 100], [300, 100, 100]]}, 'music_rhythm_enable': False, 'music_rhythm_mode': 'single_lamp', 'device_on': True, 'brightness': 100, 'hue': 240, 'saturation': 100, 'color_temp': 0, 'default_states': {'type': 'last_states', 'state': {'brightness': 100, 'hue': 240, 'saturation': 100, 'color_temp': 0}}}

green:
![Screenshot_20220915-170033_Tapo](https://user-images.githubusercontent.com/6555325/190508211-fca9036c-15f8-4d87-b9dd-0cb7fae8c6f2.jpg)
3c347d1ae9fcbffa340252d757e223eb527e1b08
{'device_id': '80230A9A889D0FC2F6AF79287F62F6D21FFA4B74', 'fw_ver': '1.0.9 Build 220727 Rel.150045', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L930', 'mac': '28-87-BA-88-50-6E', 'hw_id': '630F72CFA5B3DE1350011A0D04DE98B5', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '7B1BE6CFC4CF7D31E82C1CCD46D1FCFB', 'color_temp_range': [2500, 6500], 'overheated': False, 'ip': '192.168.4.88', 'time_diff': -300, 'ssid': 'b2NhdmFsb2JlYmVsZWl0ZQ==', 'rssi': -53, 'signal_level': 2, 'latitude': 280312, 'longitude': -825223, 'lang': 'en_US', 'avatar': 'light_strip', 'region': 'America/New_York', 'specs': '', 'nickname': 'RGVzayBMaWdodA==', 'has_set_location_info': True, 'lighting_effect': {'enable': 0, 'id': 'TapoStrip_7CC5y4lsL8pETYvmz7UOpQ', 'name': 'Rainbow', 'custom': 0, 'brightness': 100, 'display_colors': [[0, 100, 100], [100, 100, 100], [200, 100, 100], [300, 100, 100]]}, 'music_rhythm_enable': False, 'music_rhythm_mode': 'single_lamp', 'device_on': True, 'brightness': 100, 'hue': 120, 'saturation': 100, 'color_temp': 0, 'default_states': {'type': 'last_states', 'state': {'brightness': 100, 'hue': 120, 'saturation': 100, 'color_temp': 0}}}

**Comment by petretiandrea** [comment]
@Thorvarium Many thanks, I will work on it

**Comment by petretiandrea** [comment]
I've added a basic support to L930, lighting effects require more effort because I need to update plugp100 library.

To test L930 basic support you must setup on HACS store the ability to receive beta version of my integration, so use this RC -> https://github.com/petretiandrea/home-assistant-tapo-p100/releases/tag/v1.2.16-rc1

**Comment by Thorvarium** [comment]
> I've added a basic support to L930, lighting effects require more effort because I need to update plugp100 library.
> 
> To test L930 basic support you must setup on HACS store the ability to receive beta version of my integration, so use this RC -> https://github.com/petretiandrea/home-assistant-tapo-p100/releases/tag/v1.2.16-rc1

Worked great on the L930 thanks to turn on/off, I didn't even need to add the device again. Just updated to the 1.2.16-rc1 and the new device showed up. 
Even changing color on the card is working when an effect is active thru the app.

Also tested the L920 and now I can change to colors even with effects active.

**Comment by petretiandrea** [comment]
Hi @Thorvarium, I'm trying to add effects support to my plugp100 library. I've released a new experimental version, you can install by using `pip install plugp100==2.1.19` .

I need your support to try it, because I haven't a led strip. You can find an example script on my repository -> [https://github.com/petretiandrea/plugp100#code-example](https://github.com/petretiandrea/plugp100#code-example).

Lighting effects are activated by this lines:
```python
await sw.set_light_effect(LightEffect.rainbow())
state = await sw.get_state()
print(state.get_unmapped_state())
```

**Comment by Thorvarium** [comment]
> pip install plugp100==2.1.19

Maybe something is wrong. When I am using the 2.1.18 and I try to do the:
` state = await sw.get_state()
  print(state.state)
`
It prints the json, but when I do it on the 2.1.19 it reports:

`
D:\tapo.py:12: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "D:\tapo.py", line 13, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\tapo.py", line 7, in main
    sw = TapoApiClient("192.168.X.XX", "XXX@XXX.com", "XXXX")
TypeError: TapoApiClient.__init__() takes 2 positional arguments but 4 were given
`

**Comment by petretiandrea** [comment]
The api Is changed. Have you copy the example script from the link above?

**Comment by Thorvarium** [comment]
> The api Is changed. Have you copy the example script from the link above?

Sorry, I had the wrong example.

I ran it and the color is changing to light blue instead of applying the effect:
`
D:\>python3 tapo.py
D:\tapo.py:20: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
3c347d1ae9fcbffa340252d757e223eb527e1b08
{'device_id': '80230A9A889D0FC2F6AF79287F62F6D21FFA4B74', 'fw_ver': '1.0.9 Build 220727 Rel.150045', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L930', 'mac': '28-87-BA-88-50-6E', 'hw_id': '630F72CFA5B3DE1350011A0D04DE98B5', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '7B1BE6CFC4CF7D31E82C1CCD46D1FCFB', 'color_temp_range': [2500, 6500], 'overheated': False, 'ip': '192.168.4.88', 'time_diff': -300, 'ssid': 'b2NhdmFsb2JlYmVsZWl0ZQ==', 'rssi': -59, 'signal_level': 2, 'latitude': 280312, 'longitude': -825223, 'lang': 'en_US', 'avatar': 'light_strip', 'region': 'America/New_York', 'specs': '', 'nickname': 'RGVzayBMaWdodA==', 'has_set_location_info': True, 'lighting_effect': {'enable': 0, 'id': 'TapoStrip_6Dy0Nc45vlhFPEzG021Pe9', 'name': 'Candy Cane', 'custom': 0, 'brightness': 100, 'display_colors': [[0, 0, 100], [360, 81, 100]]}, 'music_rhythm_enable': False, 'music_rhythm_mode': 'single_lamp', 'device_on': True, 'brightness': 100, 'hue': 194, 'saturation': 50, 'color_temp': 0, 'default_states': {'type': 'last_states', 'state': {'brightness': 100, 'hue': 194, 'saturation': 50, 'color_temp': 0}}}
{'device_id': '80230A9A889D0FC2F6AF79287F62F6D21FFA4B74', 'fw_ver': '1.0.9 Build 220727 Rel.150045', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L930', 'mac': '28-87-BA-88-50-6E', 'hw_id': '630F72CFA5B3DE1350011A0D04DE98B5', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '7B1BE6CFC4CF7D31E82C1CCD46D1FCFB', 'color_temp_range': [2500, 6500], 'overheated': False, 'ip': '192.168.4.88', 'time_diff': -300, 'ssid': 'b2NhdmFsb2JlYmVsZWl0ZQ==', 'rssi': -58, 'signal_level': 2, 'latitude': 280312, 'longitude': -825223, 'lang': 'en_US', 'avatar': 'light_strip', 'region': 'America/New_York', 'specs': '', 'nickname': 'RGVzayBMaWdodA==', 'has_set_location_info': True, 'lighting_effect': {'enable': 0, 'id': 'TapoStrip_6Dy0Nc45vlhFPEzG021Pe9', 'name': 'Candy Cane', 'custom': 0, 'brightness': 100, 'display_colors': [[0, 0, 100], [360, 81, 100]]}, 'music_rhythm_enable': False, 'music_rhythm_mode': 'single_lamp', 'device_on': True, 'brightness': 100, 'hue': 194, 'saturation': 50, 'color_temp': 0, 'default_states': {'type': 'last_states', 'state': {'brightness': 100, 'hue': 194, 'saturation': 50, 'color_temp': 0}}}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000217FA9B5360>
D:\tapo.py:26: RuntimeWarning: coroutine 'main' was never awaited
  main()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
`

**Comment by GuanhongW** [comment]
Hi, any updates about this light strip? I plan to purchase but not sure if I can use HA to control it?

**Comment by petretiandrea** [comment]
Actually is working, but effects support is working in progress feature

**Comment by petretiandrea** [comment]
I've found a way to get light effects working. I will release a new version by a week

**Comment by Thorvarium** [comment]
> I've found a way to get light effects working. I will release a new version by a week

Awesome! Thanks

**Comment by Thorvarium** [comment]
> Available on new version 1.4.0

how do I use it? I am on version 1.4 and I don't see any special controllers in the devices
![image](https://user-images.githubusercontent.com/6555325/214337530-efd3604e-ea22-4f84-ba57-9ec6d1aaaa7a.png)
![image](https://user-images.githubusercontent.com/6555325/214337571-da7e9e04-2e42-4db1-b074-3f685a3eabb1.png)

**Comment by petretiandrea** [comment]
Press over light-strip icon

**Comment by petretiandrea** [comment]
Issue closed cause now light effects are supported
