### ISSUE TITLE
Support for Tapo L630

### ISSUE THREAD

**Issue by veggielane** [petretiandrea/home-assistant-tapo-p100#253]
**Is your feature request related to a problem? Please describe.**
I would like support for Tapo L630

**Describe the solution you'd like**
To be able to use Tapo L630 in Home Assistant

**Describe alternatives you've considered**
I tried to use this integration as-is, but it only supported temperature alarm

**Additional context**
State Dumps:

100% 2200K
![Screenshot_20221011-191506](https://user-images.githubusercontent.com/221314/195170908-1058abfb-edd4-4b3b-bca6-b50712a11000.png)
{'device_id': '8023555987AB6B3157DBA992F0B170811FE5BF3B', 'fw_ver': '1.0.3 Build 220703 Rel.125450', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L630', 'mac': 'XX-XX-XX-XX-XX-XX', 'hw_id': '0161987C98B25AD5BC3CD002C7EEE7D0', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '9E6C0F34C742F1F710041E8DED16B223', 'color_temp_range': [2200, 6500], 'overheated': False, 'ip': '10.0.1.208', 'time_diff': 0, 'ssid': 'XXSSIDXX', 'rssi': -78, 'signal_level': 1, 'latitude': XXXX, 'longitude': -XXXX, 'lang': 'en_US', 'avatar': 'bulb', 'region': 'Europe/London', 'specs': '', 'nickname': 'U21hcnQgQnVsYg==', 'has_set_location_info': True, 'device_on': True, 'brightness': 100, 'hue': 0, 'saturation': 0, 'color_temp': 2200, 'dynamic_light_effect_enable': False, 'default_states': {'type': 'custom', 'state': {'brightness': 100, 'hue': 0, 'saturation': 0, 'color_temp': 2700}}}

100% 6500K
![Screenshot_20221011-191644](https://user-images.githubusercontent.com/221314/195170901-733a5faa-26df-48a1-a534-05094985e62f.png)
1b171f02d7485a06784a3357c6e29f5ad875c2d0
{'device_id': '8023555987AB6B3157DBA992F0B170811FE5BF3B', 'fw_ver': '1.0.3 Build 220703 Rel.125450', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L630', 'mac': 'XX-XX-XX-XX-XX-XX', 'hw_id': '0161987C98B25AD5BC3CD002C7EEE7D0', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '9E6C0F34C742F1F710041E8DED16B223', 'color_temp_range': [2200, 6500], 'overheated': False, 'ip': '10.0.1.208', 'time_diff': 0, 'ssid': 'XXSSIDXX', 'rssi': -78, 'signal_level': 1, 'latitude': XXXX, 'longitude': -XXXX, 'lang': 'en_US', 'avatar': 'bulb', 'region': 'Europe/London', 'specs': '', 'nickname': 'U21hcnQgQnVsYg==', 'has_set_location_info': True, 'device_on': True, 'brightness': 100, 'hue': 0, 'saturation': 0, 'color_temp': 6500, 'dynamic_light_effect_enable': False, 'default_states': {'type': 'custom', 'state': {'brightness': 100, 'hue': 0, 'saturation': 0, 'color_temp': 2700}}}

RED
![Screenshot_20221011-191840](https://user-images.githubusercontent.com/221314/195170923-6eb1db2e-c312-42fa-b4b0-fdf1a4a9c3fe.png)
1b171f02d7485a06784a3357c6e29f5ad875c2d0
{'device_id': '8023555987AB6B3157DBA992F0B170811FE5BF3B', 'fw_ver': '1.0.3 Build 220703 Rel.125450', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L630', 'mac': 'XX-XX-XX-XX-XX-XX', 'hw_id': '0161987C98B25AD5BC3CD002C7EEE7D0', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '9E6C0F34C742F1F710041E8DED16B223', 'color_temp_range': [2200, 6500], 'overheated': False, 'ip': '10.0.1.208', 'time_diff': 0, 'ssid': 'XXSSIDXX', 'rssi': -78, 'signal_level': 1, 'latitude': XXXX, 'longitude': -XXXX, 'lang': 'en_US', 'avatar': 'bulb', 'region': 'Europe/London', 'specs': '', 'nickname': 'U21hcnQgQnVsYg==', 'has_set_location_info': True, 'device_on': True, 'brightness': 100, 'hue': 0, 'saturation': 100, 'color_temp': 0, 'dynamic_light_effect_enable': False, 'default_states': {'type': 'custom', 'state': {'brightness': 100, 'hue': 0, 'saturation': 0, 'color_temp': 2700}}}

GREEN
![Screenshot_20221011-191915](https://user-images.githubusercontent.com/221314/195170916-a4115842-e778-475a-8ad6-75582e376f7a.png)
{'device_id': '8023555987AB6B3157DBA992F0B170811FE5BF3B', 'fw_ver': '1.0.3 Build 220703 Rel.125450', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L630', 'mac': 'XX-XX-XX-XX-XX-XX', 'hw_id': '0161987C98B25AD5BC3CD002C7EEE7D0', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '9E6C0F34C742F1F710041E8DED16B223', 'color_temp_range': [2200, 6500], 'overheated': False, 'ip': '10.0.1.208', 'time_diff': 0, 'ssid': 'XXSSIDXX', 'rssi': -78, 'signal_level': 1, 'latitude': XXXX, 'longitude': -XXXX, 'lang': 'en_US', 'avatar': 'bulb', 'region': 'Europe/London', 'specs': '', 'nickname': 'U21hcnQgQnVsYg==', 'has_set_location_info': True, 'device_on': True, 'brightness': 100, 'hue': 120, 'saturation': 100, 'color_temp': 0, 'dynamic_light_effect_enable': False, 'default_states': {'type': 'custom', 'state': {'brightness': 100, 'hue': 0, 'saturation': 0, 'color_temp': 2700}}}

BLUE
![Screenshot_20221011-192333](https://user-images.githubusercontent.com/221314/195170911-548b8819-ac1f-45ba-9f07-59a2be27d7a1.png)
1b171f02d7485a06784a3357c6e29f5ad875c2d0
{'device_id': '8023555987AB6B3157DBA992F0B170811FE5BF3B', 'fw_ver': '1.0.3 Build 220703 Rel.125450', 'hw_ver': '1.0', 'type': 'SMART.TAPOBULB', 'model': 'L630', 'mac': 'XX-XX-XX-XX-XX-XX', 'hw_id': '0161987C98B25AD5BC3CD002C7EEE7D0', 'fw_id': '7BECA9DC454565672FEC87D1104F9972', 'oem_id': '9E6C0F34C742F1F710041E8DED16B223', 'color_temp_range': [2200, 6500], 'overheated': False, 'ip': '10.0.1.208', 'time_diff': 0, 'ssid': 'XXSSIDXX', 'rssi': -78, 'signal_level': 1, 'latitude': XXXX, 'longitude': -XXXX, 'lang': 'en_US', 'avatar': 'bulb', 'region': 'Europe/London', 'specs': '', 'nickname': 'U21hcnQgQnVsYg==', 'has_set_location_info': True, 'device_on': True, 'brightness': 100, 'hue': 240, 'saturation': 100, 'color_temp': 0, 'dynamic_light_effect_enable': False, 'default_states': {'type': 'custom', 'state': {'brightness': 100, 'hue': 0, 'saturation': 0, 'color_temp': 2700}}}

**Comment by petretiandrea** [comment]
Thanks for support ;)
