### ISSUE TITLE
LED Strip L900-5 poor integration

### ISSUE THREAD

**Issue by lcp97** [petretiandrea/home-assistant-tapo-p100#255]
Hello! I recently integrated via your integration some a ld strip L900-5, but there's no controlling entities available. Only 2 entities detected are the overheat sensor and wi-fi signal sensor. Am I doing something wrong or are other entities going to be added? 

Thanks in advance, appreciate your work!

![Schermata 2022-10-12 alle 23 51 18](https://user-images.githubusercontent.com/115668986/195454801-e2c53df1-3b5e-4cd4-b815-2099b93f8ad5.png)
 

```

**Comment by laurent1981be** [comment]
I got the same issue with a new one L900.
I got the WiFi quality and overheating information, but no light switch...
I tried to delete and re install but it the same issue.
Have you a solution? 
I've updated to last to date version.
Thank you.

**Comment by laurent1981be** [comment]
Amazingly, the light appears some minutes after installing...
Ok, issue to be closed!
