### ISSUE TITLE
Color and brightness change without transition

### ISSUE THREAD

**Issue by barisonal** [petretiandrea/home-assistant-tapo-p100#256]
I'm using latest version of Home Assistant (2022.10.3) and Tapo Controller (1.2.15) with my L900 lights. 

When I change the color or brightness via Home Assistant, leds change suddenly, without any transition effect.

**Comment by petretiandrea** [comment]
What transition are you talking about? There is one when change color from tapo app?

**Comment by barisonal** [comment]
Let me explain the transition I mean and my use case. 

I use different bridges such as Mi Gateway, Homekit (Apple TV), Sonoff and of course Home Assitant together to manage things in my home via Apple Home application. So I consolidated all the brdiges in Apple Homekit.

There are some different led strips and lights with different brands I have which has been integrated to Apple Homekit. For example in Yeelight integration, when I change the birghtness or color, it changes smoothly to the target color or brightness by showing mid-tones.

But with Tapo integration, when I change the color via Apple Home App ot turns directly to the color or brightness. For example from red to yellow, it is not showing the color flow. It turns yellow from red directly.

**Comment by petretiandrea** [comment]
Probably Yeelight integration implements color transition or the device itself do this. Please try with tapo app to change color and check if some transition happens, if not, neither the application nor the device implements transition. This means that I would have to do a whole a custom implementation on the integration.

**Comment by barisonal** [comment]
Yes I have already tried it with Tapo App and it works fine with transitions.

**Comment by barisonal** [comment]
Hey guys, you can close this issue.

There is an option in Tapo App to allow this transition.

![DC719EDE-E6BC-46B0-9209-379F9ED1B34B](https://user-images.githubusercontent.com/5008507/196005450-dd8656c0-5c6f-4a84-be5f-dd4f8a8fa300.jpeg)
