### ISSUE TITLE
P110 Energy Monitoring polling rate?

### ISSUE THREAD

**Issue by KieranHare99** [petretiandrea/home-assistant-tapo-p100#258]
**Is your feature request related to a problem? Please describe.**
I'm currently using a P110 to monitor the output of my inverter for my solar system. Is it possible to change the polling rate or is this dependant on Tapo's intergration?

**Describe the solution you'd like**
An option to change polling rates in the entity GUI on home assistant. e.g 250ms/500ms/1000ms/2500ms in a dropdown. 

**Describe alternatives you've considered**
n/a

If something like this can be implemented it would be amazing, if it's not possible apologies for creating an FR.

**Comment by petretiandrea** [comment]
Nice idea, but it requires a lot of testing, a polling rate too fast can lead into a non-response from tapo device

**Comment by KieranHare99** [comment]
Brilliant, I wasn't too sure if this was a Tapo limitation or not. Thank you for looking into this.

**Comment by MaxDev98** [comment]
Is there a way to make this work the other way around as well?
Like that polling of the P100 devices (not P110) only happens every 5-15 minutes, so the devices consume less power?

**Comment by DanielHani** [comment]
Being able to set the polling rate would be really nice. For me, 30 seconds is not fast enough.

Not sure if you really have to test it that much. You could leave it to the user. Just include a warning like: "By customizing the polling rate unexpected behavior could occur. The device could even become unresponsive for a while."

Cheers

**Comment by DoplerGanger** [comment]
bump ^_^ its realy need.

**Comment by josecoelho96** [comment]
Bump on this. I would really love this feature. I agree with @DanielHani , the user could be responsible for partially test out the polling rate, as long as it's warned by the possible side-effects of doing so.
@petretiandrea I saw the Release 2.0.0 milestone, any idea on when that would happen? Just out of curiosity :)
Nice work on the integration!

**Comment by petretiandrea** [comment]
I will start to work on it

**Comment by KieranHare99** [comment]
Just returned to say thank you for implementing this 😁
Brilliant work, working flawlessly.

**Comment by GlenWi** [comment]
Yes, thank you for adding this capability!
I changed fro 30sec to 60sec - in my case I don't need such frequent polling.
Nice work!

**Comment by ssergiio** [comment]
Thank you for the implementation! @petretiandrea
