### ISSUE TITLE
Configuration of Sensors

### ISSUE THREAD

**Issue by rolbre** [petretiandrea/home-assistant-tapo-p100#260]
First of all, thanks for your great work. 

But i have still a Problem. I have Tapo P110 with Energy Sensors. When i add the Tapo Integration through the UI, i got the Switch and some Sensors. That works fine. Otherwise, when i try to configure the Tapo through the configuration.yaml i got only the Switch not the Sensors. 

Can you post a Example how to configure the Sensors in the configuration.yaml? Or is this not possible at the moment?

**Comment by bedddo1929** [comment]
Hi Rolbre....I seem to have the other problem whereby I have the sensors but no switch.  So the sensors are definitely supported. I am going to remove and re-install all the components and following other posts on the community pages, I've assigned static IPs to the Tapo P110s.  I may just completely remove my Tapo devices from the Tapo App and re-install too for good measure.  Not sure if you have tried that?

**Comment by petretiandrea** [comment]
By using the configuration you must specify every entity type, in the same manner you declare `switch` entity, you must specify a `sensor` entity.

**Comment by negletios** [comment]
The way that is described in the README.md will not work. There different elements missing. What you can do is to add every device manually through the UI:

Settings -> Devices -> Add Device -> Select Tapo Controller and then add the new host. That will create the related entities and devices
