### ISSUE TITLE
P100 No control, only Overheat & Signal

### ISSUE THREAD

**Issue by Plutoaurus** [petretiandrea/home-assistant-tapo-p100#271]
## Version of the integration
V1.2.17

## Configuration

Name: alarmsiren
Firmware: 1.1.0 Build 220720 Rel: 163239

```yaml
Added through UI
```

## Describe the bug

P100 Switch Device, added on local internal network (other lighting devices discovers OK)
No controls discovered.
Only 2 sensors discovered:
Overheat
Signal level

## Debug log

```text

Logger: custom_components.tapo.common_setup
Source: helpers/update_coordinator.py:151
Integration: Tapo Controller ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/))
First occurred: 20:12:57 (1 occurrences)
Last logged: 20:12:57

Error fetching tapo data:

```

**Comment by jocamane** [comment]
![image](https://user-images.githubusercontent.com/32019937/198148772-0f507601-3f35-4860-b48a-b7eb7bb9146f.png)

**Comment by jocamane** [comment]
UPDATE: After CRTL+F5 work OK

**Comment by petretiandrea** [comment]
Some errors like "Error fetching tapo data:" exist in log" can be ignored if data is updated
