### ISSUE TITLE
Error when adding integration 

### ISSUE THREAD

**Issue by r6fgu** [petretiandrea/home-assistant-tapo-p100#276]
Installed successfully through HACS. Following HA restart and trying to add integration I get an immediate error, "Config flow could not be loaded: {"message:":"invalid handler specified"}

![Screenshot_2022-11-06-22-04-15-058-edit_io homeassistant companion android](https://user-images.githubusercontent.com/114952756/200197864-e4e7e549-363e-4c02-a985-bdc2f4581ec9.jpg)

**Comment by petretiandrea** [comment]
This is an unexpected error, can you post the home assistant log?

**Comment by r6fgu** [comment]
Logger: homeassistant.config_entries
Source: config_entries.py:809
First occurred: 20:43:14 (1 occurrences)
Last logged: 20:43:14

Error occurred loading configuration flow for integration tapo: No module named 'Crypto'

**Comment by r6fgu** [comment]
Any update on this?

**Comment by Yougoshatenshi** [comment]
I had this too, but fixed it by installing manually the missing dependency with "pip3 install pycryptodome --target ~/.homeassistant/deps" into the home assistants deps folder.
although the plugp100 [requirements](https://github.com/petretiandrea/plugp100/blob/main/requirements.txt) list has it as a requirement it was missing for me, when i installed the integration.

**Comment by toketin** [comment]
I've the same issue on HA 2022.11 (docker container).
