### ISSUE TITLE
P100 smart plugs dropping off of Home Assistant

### ISSUE THREAD

**Issue by smittyuk** [petretiandrea/home-assistant-tapo-p100#277]
Hi I seem to be having this issue fairly regularly where a Tapo P100 smart plug will drop off of Home Assistant. It won't respond in the app or web console - it gives an error:

'This entity is no longer bring provided by the Tapo integration. If the entity is no longer in use, delete it in settings'

I then need to remove it and readd it as a new switch in the integration. I've had to do this a few times now with different plugs.

Any ideas?

**Comment by smittyuk** [comment]
Closing this as it was an issue with the plug itself in this case. Thanks

**Comment by jhkuperus** [comment]
I'm curious, what sort of issue was it with the plug? My P115s also exhibit this behaviour. When I add them to HomeAssistant, all entities are there and responsive, but after a couple of hours the switch-entitiy becomes unavailable and after a few day the current_power entity also becomes unavailable. The only way for me to fix it at this moment is to remove the device and re-add it. But that just gives me a couple of hours of control before it drops again.

If this is solved by some setting on the device, please share it :)

**Comment by jhkuperus** [comment]
It seems this same behaviour is discussed in #264 , moving my attention over there.

**Comment by smittyuk** [comment]
N/A
