### ISSUE TITLE
Support for P115 energy monitoring ?

### ISSUE THREAD

**Issue by wiklund75** [petretiandrea/home-assistant-tapo-p100#278]
Is it possible to integrate energy monitoring for the P115 plug similar to the P110?

**Comment by wiklund75** [comment]
Is it possible to integrate energy monitoring for the P115 plug similar to the P110?

**Comment by wiklund75** [comment]
Oh sorry, seems like it's already is working according to closed issues.
My recommendation is to update the description of the "tapo integration" to HA.
Today it is stated that energy monitoring is only provided for Tapo P110.

**Comment by Friedolino2** [comment]
And hie is it integrated? Can Not find Any Energy sensors in HA
