### ISSUE TITLE
L630 support

### ISSUE THREAD

**Issue by DerDenniis** [petretiandrea/home-assistant-tapo-p100#282]
Hello all,

I am still quite new in the field HA and integration of new lamps. I have here the GU10 - L630 from TP-Link/Tapo. On good luck I downloaded and tested this integration here. And it works! But only partially. My lamps can only be set in warm white or cold white, not in other colors, although this is also displayed in HA, it is not set in the lamps. 
Is it me, or can this be set somehow so that this works? :)
Thanks!

**Comment by xBodoB** [comment]
Hi,
I also have the L630 but unfortunately can not test it yet because I lack the P100. 
The integration goes unfortunately only with it or have you been able to solve this differently?

**Comment by petretiandrea** [comment]
You can request new device support by creating a new Issue and following the `New Device Support Request` issue template

**Comment by virtualorg1** [comment]
I've got exactly the same issue. Can manipulate L630, but cannot change the colour. So if you could add this, it would be great.

**Comment by petretiandrea** [comment]
Please follow the New Device Support Request issue template -> https://github.com/petretiandrea/home-assistant-tapo-p100/issues/new?assignees=&labels=&template=feature_request.md

**Comment by olirodd** [comment]
@petretiandrea I'm also looking for L630 and L610 support but I don't currently own the devices to be able to run the python script in order to get the debug info. Do you know what the chances are for support? I'm happy to buy both of the bulbs I want support for and execute the script but only if I know support will be able to be added, have you come across troubles with any previous tapo devices that might make you sceptical about being able to provide full support?

**Comment by olirodd** [comment]
Update to my previous comment, just ended up buying 2 610s and they worked out the box, I guess similar API to the 510s? Creating a PR to update the readme, will buy a 630 soon

**Comment by petretiandrea** [comment]
The readme is now update, L630 and L610 are both supported, except for light effects

**Comment by rivet-defiance-lament-pomp** [comment]
Do you know if the L630 has colour options yet in HA? I've just setup the integration however all I seem to be able to do is turn it on and off, 

**Device Info** - ![image](https://github.com/user-attachments/assets/3b8567f0-1056-443f-a557-d9493072234d)
**Available Actions** - ![image](https://github.com/user-attachments/assets/4f13da5f-8a79-4207-97af-e6a2a7a20396)
**Entities** - ![image](https://github.com/user-attachments/assets/c639efac-9df9-4f5d-9709-8d132b41aa0f)
**Diagnostics** - [config_entry-tapo-01JD9QDDXVEZNKHY2GYZ8TYMRG.json](https://github.com/user-attachments/files/17870785/config_entry-tapo-01JD9QDDXVEZNKHY2GYZ8TYMRG.json)
