### ISSUE TITLE
Configuration Flow could not be loaded: Unknown Error

### ISSUE THREAD

**Issue by Lucas-wwu** [petretiandrea/home-assistant-tapo-p100#284]
Hey I installed it via HACS, restarted and tried to add via the Integration Sector, when loading up it says: The Configurationflow couldnt be loaded: Unknown Error.

Am I doing something wrong?

Thx in advance!

**Comment by calielc** [comment]
Same here, 
my TP100 was working fine up to yesterday, today it became unavaliable.
I remove and tried to readd it, but then I get the "Unknown Error" well

**Comment by petretiandrea** [comment]
> Hey I installed it via HACS, restarted and tried to add via the Integration Sector, when loading up it says: The Configurationflow couldnt be loaded: Unknown Error.
> 
> Am I doing something wrong?
> 
> Thx in advance!

please post your configuration.yaml snippet
