### ISSUE TITLE
Watt comsumtion recording/analysis

### ISSUE THREAD

**Issue by Eric9453** [petretiandrea/home-assistant-tapo-p100#29]
I have to say this is a very good project, thank you very much.

Is it possible to add the feature about watt consumption recording or analysis?

 Anyway, you public this project to HACS is very kind, and I like it. Thank you very much.

**Comment by petretiandrea** [comment]
Hi Eric, I think that is not possible for now. Actually the protocol allow to get the state of bulb or plug, but this state not contains information regarding watt consumption. I have known that Tapo application contains the information about KWh for L510E (the bulb that I have), but, for example, for the plug P100 the app doesn't show this information. 

Actually I don't know how application receive this information or if are information calculated by cloud. I will search for, and if it is possible I will add this feature.

**Comment by Eric9453** [comment]
got it! thanks for your reply. :)
