### ISSUE TITLE
Tapo Light Bulb gets into a bad state with color_mode = "unknown"

### ISSUE THREAD

**Issue by bwims** [petretiandrea/home-assistant-tapo-p100#301]
## Version of the integration
V1.2.18
-->

## Configuration

L530 H/W V 2.0 F/W V1.0.9 Build 220526 Rel 203202

```yaml
Add your logs here.
```

## Describe the bug

It is easy to put the L530 into a mode which does not conform to the 
[Light Entity](https://developers.home-assistant.io/docs/core/entity/light/) specifications, which documentation says that: 
the `color_mode` property must `Return the color mode of the light. The returned color mode must be present in the supported_color_modes property.`

In the case of the L530, these are:
```
supported_color_modes:
  - color_temp
  - hs
```

However, if I use the entity card in HA, choose color and use the picker to select the centre of the colour circle, I get the following state

```
min_mireds: 153
max_mireds: 400
supported_color_modes:
  - color_temp
  - hs
friendly_name: tapoB1
supported_features: 19
color_mode: unknown   <<<<<<<
brightness: 122
```

The same thing happens if I programmatically set RGB to [255,255,255]

Since "unknown" is an unsupported mode, I must assume this is a bug, as no error message is returned, and the only way forward is to go back to the colour picker tool.

This in itself was caused by attempting to try to find a way to change color_modes via programmatic means.
As a sub-goal of this issue, any help you could provide would be much appreciated.

## Debug log

```text

Please let me know which logs, if any, would be useful.
```

Many thanks!

**Comment by bwims** [comment]
Hi!  Thanks for doing the work!  I'm very grateful.  When do you think I will be able to update HACS?  Is there any way for me to tell Home Assistant to check for a new version of this integration?

Thanks again!

B.

**Comment by bwims** [comment]
There seems to be another problem.  Can I reopen  https://github.com/petretiandrea/home-assistant-tapo-p100/issues/301 please?

**Comment by petretiandrea** [comment]
Please open a new one, cause is another issue
