### ISSUE TITLE
Tapo P100 not showing current/month energy after update

### ISSUE THREAD

**Issue by shiva979** [petretiandrea/home-assistant-tapo-p100#312]
Current Energy and This Month Energy giving "no longer provided by this integration" error after recent update

**Comment by clicky73** [comment]
Same issue here with my P100's

**Comment by petretiandrea** [comment]
Please update to v1.3.3

**Comment by clicky73** [comment]
Sorry, should have mentioned that i am on v1.3.3.

**Comment by aspades** [comment]
Same here, running 1.3.3 and Current energy is no longer available

**Comment by pjw345** [comment]
On my installation I've added my P100 as monitored devices and the current daily/monthly figures are always the same

**Comment by petretiandrea** [comment]
I suggest you to update to v1.3.4. Anyway this month energy is no longer available due to missing data from tapo device, see #264

**Comment by clicky73** [comment]
I have updated to V1.3.4 but still not working.
<img width="561" alt="image" src="https://user-images.githubusercontent.com/47227361/210326838-5cb31516-00af-4598-894a-001f7d6b282f.png">

**Comment by clicky73** [comment]
Should also mention I am running HA 2022.12.8

**Comment by pjw345** [comment]
> On my installation I've added my P100 as monitored devices and the current daily/monthly figures are always the same

Actually mine are P110 and on the dashboard it shows me two different values for daily/monthly usage, but on the energy dashboard the values for daily/monthly are the same,  I've double checked the energy dashboard is using the correct entities
