### ISSUE TITLE
V1.2.19 Has Introduced New, Undocumented Color Modes and can no longer use color picker to switch modes

### ISSUE THREAD

**Issue by bwims** [petretiandrea/home-assistant-tapo-p100#317]
## Version of the integration

V1.2.19
## Configuration

L530 H/W V 2.0 F/W V1.0.9 Build 220526 Rel 203202
```yaml
Add your logs here.
```

## Describe the bug

It is easy to put the L530 into a mode which does not conform to the
[Light Entity](https://developers.home-assistant.io/docs/core/entity/light/) specifications, which documentation says that:
the color_mode property must Return the color mode of the light. The returned color mode must be present in the supported_color_modes property.

In the case of the L530, these are:

```
supported_color_modes:
  - color_temp
  - hs
```
After updating the integration the developer states tool shows the following supported modes:

`supported_color_modes: brightness, color_temp, hs, onoff`

But "brightness" and "onoff" are not part of the aforementioned documentation.

This patch has apparently replaced the prior color_mode state of "unknown", which was what was returned when using the color picker at the centre, or programmatically with RGB=[255,255,255] with "brightness" rather than "color_temp".  I'm not sure what the purpose of "onoff" is.

An additional problem, which I don't think was present with the previous version, is that, once "color_temp" mode is achieved, (either with the HA color picker, or programmatically) to move back to "hs" mode.   That can only be achieved, so far,  with the TAPO application on my smartphone.  This seems to be a bug.

## Debug log

```text

Please let me know what logs are useful.

```

**Comment by christhebizz** [comment]
> An additional problem, which I don't think was present with the previous version, is that, once "color_temp" mode is achieved, (either with the HA color picker, or programmatically) to move back to "hs" mode. That can only be achieved, so far, with the TAPO application on my smartphone. This seems to be a bug.

Same here on v 1.3.2

Can't change color on my L530s anymore :/

**Comment by petretiandrea** [comment]
`onoff` and `brightness` ColorMode are described here https://developers.home-assistant.io/docs/core/entity/light/#color-modes

**Comment by bwims** [comment]
`onoff and brightness ColorMode are described here`

Ah, ok, I must have misunderstood the documentation.  Apologies for that.  However, the problem with getting stuck in color_temp which needs the Tapo app to fix is still a problem.  I guess that's why you put the Bug label on it?

Thanks!

**Comment by petretiandrea** [comment]
Update to v1.3.4. I can change color in the right way

**Comment by christhebizz** [comment]
Updated to 1.3.4

Still not able to change color on my L530s :(

**Comment by petretiandrea** [comment]
Can you send a photo or video which describe the issue better?

**Comment by christhebizz** [comment]
When I want to change the color of a L530 nothing happing. The color on the icon changes to the color i picked. The bulb stays in temperature mode. 

Changing temperature works very well. 

btw; on my L900s every thing works just fine.

![Bildschirmfoto 2023-01-02 um 21 03 47](https://user-images.githubusercontent.com/120646267/210274227-af14a82c-377b-4bb7-af00-0223b8c94b6c.png)

**Comment by eliothearld** [comment]
I have the exact same problem!

**Comment by petretiandrea** [comment]
> btw; on my L900s every thing works just fine.

Can you provide hw version and sw version of L900?

**Comment by christhebizz** [comment]
L900:

Hardware Version
1.0

Firmware Version
1.0.16 Build 220902 Rel. 151030

L530:

Hardware Version 
2.0

Firmware Version
1.0.9 Build 220526 Rel. 203202


Hope this helps

**Comment by petretiandrea** [comment]
It's an issue related to HW Version like here #133. I will investigate on it

**Comment by eliothearld** [comment]
Chris, all my L530`s are the same as yours. I also have 2 x L900`s and one L930.
After updating, one of my L900`s and the L930 still work with the colour wheel.
They were both unplugged at the mains at the time of the update but the none working L900 was turned on. Is that the case with you?

**Comment by christhebizz** [comment]
> It's an issue related to HW Version like here #133. I will investigate on it

Thanks buddy. I really do appreciate that! (y) 



> Chris, all my L530`s are the same as yours. I also have 2 x L900`s and one L930.
> After updating, one of my L900`s and the L930 still work with the colour wheel.
> They were both unplugged at the mains at the time of the update but the none working L900 was turned on. Is that the case with you?

To be honest, I can't remember. I ran the update and on the next day my daughter came to me telling she can't change colors on here lamp. So I tried mine and recognized it also won't work :(

**Comment by christhebizz** [comment]
Maybe the following is related. 

Scenes I created in HomeKit don't work properly either. The icons show the lights as "on", but in reality they stay off. 

When I go to the lights directly in HomeKit, I can turn them on perfectly.

**Comment by christhebizz** [comment]
Now it gets weird. 

I have started a scene from HomeKit. All four lights in the scene are also lit in reality. However, two of the four are displayed as "off" in Home Assistant. In HomeKit as "on". 

We are talking about two L530 and two L900. The L530s are displayed as "off" in Home Assistant, but as I said, they actually light up and are also displayed as "on" in HomeKit.

**Comment by bwims** [comment]
Sorry to be dumb, but how do I get HACS to upgrade ?

This shows that it knows there is a new version

![image](https://user-images.githubusercontent.com/18516073/210389300-dbdcc908-6486-46fd-a3cf-5e80a2308301.png)


```
============================
However the system doesn't act like it
============================

```

![image](https://user-images.githubusercontent.com/18516073/210389510-7a5b53f8-3d43-44a0-867a-793f04afe28b.png)


Am I missing something?

Thanks!

**Comment by bwims** [comment]
oops!  Never mind.
![image](https://user-images.githubusercontent.com/18516073/210400059-82648f47-20bf-40a0-ac43-ce2b16965b94.png)

**Comment by christhebizz** [comment]
![Bildschirmfoto 2023-01-03 um 18 45 09](https://user-images.githubusercontent.com/120646267/210412342-2ba3765e-fbd6-465b-a852-5587c9a718ef.png)

Maybe this helps

**Comment by petretiandrea** [comment]
> I have now upgraded to 1.3.4 and the problem remains, for which I have appended an MP4 video.
> 
> Before the video starts, I use the Tapo phone app to establish color mode.
> Although the quality is not high, you can see the color of the bulb change as the palette is clicked.
> You then see the mode change to Temperature and see the color of the bulb change with the slider
> Lastly, you see the failure of the attempt to change into color mode, whereby the pallette has no effect, and requires another use of the Tapo phone app to get back to that mode.
> 
> Thanks!
> Update:  The video was too big to include.  Here is a shareable link to google photos.  Apologies for the 4 second glitch at 4 seconds in, but there is still enough detail to show the problem
> 
> https://photos.app.goo.gl/ERoGePkz4WAfpKCG6
> 

Thanks for video. I've a fix ready to be published. https://user-images.githubusercontent.com/25798293/210650391-e535cb92-9ab5-497a-abd6-e2f5f314f134.mp4 Its right?

**Comment by christhebizz** [comment]
Thank you @petretiandrea 🙏 

I really appreciate your work 👍

**Comment by petretiandrea** [comment]
Release v1.3.5 should resolve this issue
