### ISSUE TITLE
Tapo P110 does not show current energy in HA

### ISSUE THREAD

**Issue by pjannink** [petretiandrea/home-assistant-tapo-p100#321]
I am using HA 2022.12.8, Latest Tapo integration and Tapo firmware 1.1.6. Build 221114
Current Energy is now showing as Unavailable in Home Assistant. (Same case for This Month Energy but that is a known issue). Not sure when the issue with Current Energy started for me. I guess with soime update in December.

**Comment by Sub-7** [comment]
Same problem since last update.

**Comment by pektommy** [comment]
Same problem for me

**Comment by lkernan** [comment]
Seems to be same for me since the most recent update

**Comment by GpsM2** [comment]
Same bug here since the last update via HACS

**Comment by spydoor17** [comment]
> Me three. Any easy way of rolling it back?

HACS > Integrations > Tapo Controller > three dots (top right) > Redownload > select a previous version

**Comment by similair** [comment]
> > Me three. Any easy way of rolling it back?
> 
> HACS > Integrations > Tapo Controller > three dots (top right) > Redownload > select a previous version

Thanks for that, I thought it would just redownload.
Also
I just added a new P110 today and that did NOT have any sensor reporting issues

**Comment by pjannink** [comment]
Hi Similair, what are the firmware versions of your devices?

**Comment by similair** [comment]
> Hi Similair, what are the firmware versions of your devices?

They are all on 1.1.6 Build 221114 Rel.203339

**Comment by pjannink** [comment]
> > Hi Similair, what are the firmware versions of your devices?
> 
> They are all on 1.1.6 Build 221114 Rel.203339

Weird.  I downgraded to 1.3.2 and then upgraded to 1.3.3 but in all cases NO solution on the Current Energy issue for the P110. Hope that Petretiandrea jumps in soon :-) to look at the Tapo integration. I have some automations running with this entity and would love to have them back active again…

**Comment by similair** [comment]
Hi.
Yes me too, I have loads of stuff that runs on the power values. Washing machine, dryer, dishwasher, tvs etc etc. I was thinking I might just re add them as I am fully convinced it will sort the problem but I do have about 30 of them. So that will delete a day of my life hahahaha

**Comment by petretiandrea** [comment]
I need some information, from those who are experiencing the issue:
- Home Assistant Version
- Tapo Device and firmware
- Integration Version
- From which version of integration or home assistant are experiencing the issue.

Anyway, try the following steps:
- remove tapo device
- update to latest integration version
- RESTART HOME ASSISTANT
- add tapo device

**Comment by similair** [comment]
Hi.

P110 1.1.6 Build 221114 Rel.203339

Home Assistant 2023.1.1
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

Integration V1.3.4

Since Integration V1.3.4

**Comment by similair** [comment]
As i mentioned in my earlier post, I fully believe removing and re-adding would fix the problem anyway.

**Comment by similair** [comment]
Ok I have NOT updated to Integration V1.3.4
Deleted TAPO P110 FR1 (My front room device 1)
restarted HA, and as suspected it works fine..

I just dont want to do that for 27 devices

**Comment by pjannink** [comment]
Upgrading to 1.3.5 did NOT resolve the issue.
I removed my devices, removed the integration and restarted HA
I reinstalled the TAPO integration v1.3.3 but that did not resolve. I see 7 sensors but NOT Current Energy.
Further, I am up2date with all versions, running HA 2023.1.1

One remark: when installing the integration, I have to enter a username (email). When typing, it starts with a capital (Paul…@….). That is rejected. So I have to use a trick to remove that leading capital in order to be able to add a device. May be something to look at too…

**Comment by similair** [comment]
I have notice this though.

comparing a device that isnt working correctly (Device A1) there are 2 less sensores on the added device.

FR1  (READDDED DEVICE)                              A1
Sensors                                        Sensors
                                                    Current energy Unavailable
Current power 24.283 W             Current power 67.408 W
Month energy 0.47 kWh             Month energy 3.065 kWh
Month runtime 12:03:00             Month runtime 54:41:00
Overheat False                             Overheat False
Signal level -52 dBm                    Signal level -58 dBm
                                                    This month energy Unavailable
Today energy 0.005 kWh             Today energy 0.09 kWh
Today runtime 14:00                    Today runtime 2:18:00

**Comment by similair** [comment]
Is this just a label change?
The current power sensor is in watts so it is effectively the same as current energy was, and the month energy doesnt work because it is a time/w multiplier of month energy and that label doesnt exist anymore.
So just rename the current power back to current energy.

**Comment by petretiandrea** [comment]
@similair you're right, there is an old PR #280 which replace "current energy" with "current power". So, you had not updated for a long time.

**Comment by similair** [comment]
What about the others above, and I have updated every time an update has been made available (as it always asks me to update everything when intergrations etc need updating, I still dont know how to actually fix this ( I edited the __init__.py file and changed it back to energy for now) I uncommented the "This month energy" code in the python file also, but this isnt working I am sur its not a big deal to fix.
I dont understand why it was changed anyway or what the PR #280 is actually about.

Please can you explain just so I do understand. I really appreciate your help

Thanks

**Comment by petretiandrea** [comment]
As you can see on PR #280 there was a label change, from "current energy" to "current power". As the author of PR reports this rename: "This change is not backward compatible (so old entity will go away and a new one will be installed), so I will let the maintainer to decide what to do.". So for this reasong the "current energy" is unavailable, cause now is called "current power".

Differently "This month energy" is no longer supported cause the tapo devices no longer send this information.

**Comment by similair** [comment]
Ok Thank you
