### ISSUE TITLE
P115 doesn't report energy usage without internet connection

### ISSUE THREAD

**Issue by Sbte** [petretiandrea/home-assistant-tapo-p100#329]
## Version of the integration
Current git

## Configuration
P115, 1.1.6 build 221114

## Describe the bug
The Tapo app is able to get the current power (but nothing else) when the device is not connected to the internet. So no historic data, just the current power usage. plugp100 returns -1003 from `get_energy_usage`, so nothing is displayed in HA (but it works fine when connected to the internet). The app must do something else instead. I'd like to do the same as the app, but not sure how to debug this. Do I have to make my phone connect through my PC and snoop all HTTP requests from there?

## Debug log

```text
DEBUG:plugp100.tapo_protocol.tapo_protocol_client:Method request: {"method": "get_energy_usage", "params": null}
...
DEBUG:plugp100.tapo_protocol.tapo_protocol_client:Device responded with: {'error_code': 0, 'result': {'response': 'DtRbKH83iIeol1m+0SusZrW80UI7qDYpUpVKJz5iK+0='}}
DEBUG:plugp100.tapo_protocol.tapo_protocol_client:Device inner response: {'error_code': -1003}
```

**Comment by petretiandrea** [comment]
Excatly you must sniff http requests. For example you can use Charles http proxy to sniff http requests

**Comment by Sbte** [comment]
Ok, I have that working now. But now I assume I need the private key that the Tapo app generated and the one used by the plug to actually decode the securePassthrough messages? The method name is in there. Is that even possible?

**Comment by petretiandrea** [comment]
Yes you need private key, but how?

**Comment by Sbte** [comment]
I have no idea.

Instead I just wrote a script iterating over the most likely names for the method, and I found it! It's `get_current_power`. I'll submit a pull request later.

**Comment by petretiandrea** [comment]
Great works! Thanks
