### ISSUE TITLE
L510 Bulb, Call service lights.turn_on with brightness set cause non responsive bulb

### ISSUE THREAD

**Issue by Plutoaurus** [petretiandrea/home-assistant-tapo-p100#331]
## Version of the integration
Version 1.3.6

## Configuration
Device: Tapo L510
Firmware:  1.0.9 Build 220256  rel: 203202

```yaml
Add your logs here.
```

## Describe the bug

Controlling the bulb on/off from its device seting works perfectly.
The log shows it calls the service lights.turn_on and lights.turn_off. 
Adjusting brightness when light is turned on is not a problem

With the bulb off, turning on by tapping the brightness, or with a automation to lights.turn_on with brightness set causes the bulb to turn on at that brightness but both HA and the tapo app are unable to see the bulb is on and other turn_on service requests with brightness no longer function.
In HA, Turning the already on bulb and then off allows the bulb to work again

## Debug log

```text

In progress

```

**Comment by petretiandrea** [comment]
v1.3.7 should fix the issue
