### ISSUE TITLE
P110 lost switch and current energy entity since latest update

### ISSUE THREAD

**Issue by hssmith76** [petretiandrea/home-assistant-tapo-p100#340]
Seems that since the latest Home Assistant the integration is no longer returning the switch or current energy values for Tapo P110 smart plugs. Worked fine before then, Anmyone else seeing this?

**Comment by hssmith76** [comment]
Just one update - the switch element seems to have returned with a full restart but the current energy is still missing

**Comment by jamesonuk** [comment]
I came here for the same as the plugs had dropped off my Energy dashboard.
I however switched to using Today Energy and this has worked (and populated some historic data)
Thinking about it current energy makes little sense.   You have current power (in W) which is being populated.
I am presuming that current energy should never have actually been there and the rest of the fields you see in the app are now correctly showing

**Comment by petretiandrea** [comment]
This #339 should fix the issue
