### ISSUE TITLE
L920 color change issues

### ISSUE THREAD

**Issue by LooperX** [petretiandrea/home-assistant-tapo-p100#343]
## Version of the integration

1.4.0
## Configuration

L920-5 HW 1.0, FW 1.0.9

## Describe the bug
Unable to change the strip color by using the color wheel of the entity. Brightness instead is working properly.
It’s my first time with this integration, cannot say if with older versions it worked. 
Even with a python command like:
`service_data = {'entity_id': entity_id, 'rgb_color': rgb_color, 'brightness': 255 } `
it doesn’t work.

**Comment by darkmatter24** [comment]
Same here, color changing of the L920 via the color wheel or via script calls was broken with the upgrade to v1.4.0.

if you downgrade back to v1.3.8 all is working again

**Comment by luixal** [comment]
Same here but with a different device.

I think this is bug is affecting several lights at the color feature. I have a "Smart WiFi Light Bulb Multicolor" (L530, not sure if B or E) and color setting stopped working with the last version. Can't see any error in the logs.

Going back to 1.3.8 also fixed it for me.

**Comment by chriscore** [comment]
Same here, RGB and colour temperature change is no longer is working with the TP Link L530 bulb on:
Firmware: 1.0.9, 
Build 220526 Rel.203202 
Hardware: 2.0. 

The functionality is working in v1.3.7, and not working in v1.4.0, so for the time being I have rolled back.

**Comment by Plutoaurus** [comment]
Same on L530.  
It was fixed but broke again.
Gone back to 1.3.6 to get it working

**Comment by Random-Cookie** [comment]
Can confirm I am also having this issue with L530 colour wheel not setting the light colour.

**Comment by alenoi** [comment]
+1 with the issue of the L530 color issue (v1.4.0)

**Comment by christhebizz** [comment]
+1 on L530

**Comment by Derweis** [comment]
v 1.6.1

There is no option to change colors. There are no problems with effects. And the color is only white and you can only change the brightness. It does not change from the interface, I tried to send it manually through the services - it also did not give results. What am I doing wrong? The latest tape firmware is 1.0.9 Build 220422 Rel.150004.

**Comment by Derweis** [comment]
https://user-images.githubusercontent.com/15996927/230762636-eecfa569-e5d3-4f49-b059-3ba21d491644.mp4
