### ISSUE TITLE
P110 No Current Energy

### ISSUE THREAD

**Issue by teshiburu2020** [petretiandrea/home-assistant-tapo-p100#349]
## Version of the integration
Stable 1.4.0

## Configuration
P110
by TP-Link
Firmware: 1.1.6 Build 221114 Rel.203339
Hardware: 1.0

## Describe the bug

Since the most recent version of the integration there is no current energy sensor #340 was meant to fix this, but doesnt appear to have done for my plugs?

**Comment by teshiburu2020** [comment]
ignore me :)

**Comment by marcforn** [comment]
I've experienced the same. Since update not able to see the energy
