### ISSUE TITLE
Cannot access my tapo smart plug on home assistant 2023.1.

### ISSUE THREAD

**Issue by marcopi** [petretiandrea/home-assistant-tapo-p100#356]
I upgraded plugp100 with version 2.4.1 on home assistant and used latest tapo-p100 custom_components.
Now my smart plug cannot be controlled anymore.

The log says:
Logger: homeassistant.setup
Source: setup.py:210
First occurred: 08:16:59 (1 occurrences)
Last logged: 08:16:59

Setup failed for custom integration tapo: Unable to import component: cannot import name 'TapoApiClientConfig' from 'plugp100' (/config/deps/lib/python3.10/site-packages/plugp100/__init__.py)

These are the info from my homeassistant container:
bash-5.1# pip show plugp100
Name: plugp100
Version: 2.4.1
Summary: Controller for TP-Link Tapo P100 and other devices
Home-page: https://github.com/petretiandrea/plugp100
Author: @petretiandrea
Author-email: petretiandrea@gmail.com
License: GPL3
Location: /usr/local/lib/python3.10/site-packages
Requires: aiohttp, certifi, cryptography, jsons, requests, semantic-version
Required-by:

**Comment by rambo19997** [comment]
Same problem after upgrade

**Comment by yognspoon** [comment]
This could be same issue i'm having.

Able to control the device (power state) and observe sensors for Signal Level and Overheat.

Not able to observe sensors for power/runtime.

**Comment by petretiandrea** [comment]
v1.5.1 should fix this issue

**Comment by marcopi** [comment]
Great!
I tried it now and all seems fine.
Thanks for your fast response

**Comment by yognspoon** [comment]
Perfect.  Thank you!!!
