### ISSUE TITLE
Error in HA Log

### ISSUE THREAD

**Issue by pjannink** [petretiandrea/home-assistant-tapo-p100#364]
I am running HA 2023.2 in Docker on Synology. Following in System/Log:

This error originated from a custom integration.

Logger: custom_components.tapo.common_setup
Source: custom_components/tapo/common_setup.py:46
Integration: tapo_p100 (documentation, issues)
First occurred: 16:54:06 (1 occurrences)
Last logged: 16:54:06

Failed to setup Unexpected exception:

**Comment by toketin** [comment]
Hi, I confirm that since today I'm having the same error, until yesterday it was working fine. After this blackout I've updated the integration to the last revision 1.5, but it isn't working yet.

**Comment by toketin** [comment]
Hi, I've just upgraded the Home Assistant core to 2022.2 (docker container) and now the Tapo integration is working again, no errors.

**Comment by luca-angemi** [comment]
I'm on 2023.2.2 and still see the message in the log

```
2023-02-06 09:13:38.782 ERROR (MainThread) [custom_components.tapo.common_setup] Failed to setup Unexpected exception:
2023-02-06 09:13:38.836 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Tapo' for tapo integration not ready yet: Unexpected exception: ; Retrying in background
```

**Comment by petretiandrea** [comment]
Version 1.6.1 should fix this issue or log more detailed error
