### ISSUE TITLE
Changing effect Brightness Tapo L920-5

### ISSUE THREAD

**Issue by thedotor** [petretiandrea/home-assistant-tapo-p100#365]
Thank you for getting the Effects to work, when choosing a effect from the list and then changing the brightness of the effect, it gets overwritten and changes to white at that brightness.
When choosing the effect again it just goes to full brightness.

Many thanks !

**Comment by vk2him** [comment]
This is still occurring for me 
 Device info
L930
by TP-Link
Firmware: 1.0.10 Build 220927 Rel.175141
Hardware: 1.0

**Comment by petretiandrea** [comment]
Try with v2.0.0

**Comment by vk2him** [comment]
I see same issue as thedotor 

L930
by TP-Link
Firmware: 1.0.10 Build 220927 Rel.175141
Hardware: 1.0
