### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by djdarlo** [petretiandrea/home-assistant-tapo-p100#366]
## Configuration

```yaml
Add your logs here.
```

## Describe the bug

After I've connected a P110 plug via the integration when I try to look at the entities it says they are unavailable. I then get this error. 

Retrying setup: Error communication with API: Cannot connect to host 192.168.1.138:80 ssl:default [Connect call failed ('192.168.1.138', 80)]

I have checked my router and the plug is on that IP address. 

## Debug log

```text

Add your logs here.

```

**Comment by chrisss1983** [comment]
I have the same problem since yesterday, until then everything worked perfectly...
All the sensors became unavailable in HomeAssistant

**Comment by iacorenx** [comment]
I have the exact same problem since i have upgraded to the new Home assistant OS 9.5.
I have a P115 Tapo smart plug.

**Comment by Billy421** [comment]
I've the same Problem. Since I updated to 9.5 all TAPO devices are unavailable.

**Comment by petretiandrea** [comment]
Version 1.6.1 should fix this issue.
