### ISSUE TITLE
L530 attributes change issue

### ISSUE THREAD

**Issue by sharpmindstudio** [petretiandrea/home-assistant-tapo-p100#368]
Hello,

First of all, thanks for your work. you are the best

I have an issue that I just notices (probably this is since last update), I can not send multiple data to change the attributes for L530.
My usage: I change the attributes of the bulb via NodeRed (not really relevant) and send light On and some data in JSON, and worked perfect in the past.
Simple eg: {	"brightness": 100,	"color_temp": 168	}  - Now in this case it dose not set anything. only turns the light on 

Workaround: I send data in 2 consecutive events:  {"brightness": 100}   and then { "color_temp": 168	} 

integration: v1.5.1
Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest
Nodered: 14.0.2

PS: for other lights type (nonTapo)  there are no issues.

Thanks 3000!

**Comment by sharpmindstudio** [comment]
Downgraded to tapo v1.4.0 and it works perfect as before

**Comment by dcsilva0** [comment]
Same issue. works perfectly on v1.4.0

**Comment by quadroluxinator** [comment]
Same problem here, will try to downgrade.

**Comment by sharpmindstudio** [comment]
v1.6.0 - This dose not fix the described issue
