### ISSUE TITLE
L930 Odd Issues

### ISSUE THREAD

**Issue by macflyhub** [petretiandrea/home-assistant-tapo-p100#370]
I have 3x L930 LED Tapo Light Strips outdoors in waterproof track. {1x 10m the 5m+5m version and 2x 5m versions}
This is what is suppose to happen after I created a SCENE for each action on Home Assistant.
In automations the following happens.
1: Sunset - Lights turn on to 60% brightness with color temp 2500k [Seems to work but occasionally it picks the wrong color]
2: If motion sensor activates then lights go 80% bright (also 2500k) and return to 60% after 1 min [This fails to work most of the time by not setting to 80% (100% instead) or going to wrong color or flash 100% for 1 second and not change or not activating at all or not returning to 60%]
3: Sunrise - Lights turn off [This works perfectly]
If I manually control via the Home Assistant integration it works most of the time but often it will flash bright for 1sec and not change. 
I also tried using preset effects instead but it does the same thing at random.
Other lights with same automations and scenes all work like a peach.
There is something funny with the controlling of the L930's
Help - SOS - Can't remove these now as they took ages to physically install.

**Comment by macflyhub** [comment]
Updated to v1.6 but no improvements for L930
Just need to automate a scene change where the brightness actually changes and ultimately I can set a color temp.
Anyone else with the L930 that knows of a solution?

**Comment by quadroluxinator** [comment]
I habe similar problems with the L530 bulbs. They only seem to work randomly with scenes and automations, most of the time they just witch on but dont adapt brightness and/or color settings. I cant find a reproducible pattern yet. When adressed via the Android Tapo App, all bulbs work as expected.

**Comment by petretiandrea** [comment]
> 

Can you provide the scene code?

**Comment by quadroluxinator** [comment]
`name: 'Master: Warmes Licht'
  entities:
    **light.lampe_f1:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      friendly_name: Lampe F1
      supported_features: 0
      color_temp_kelvin: 2500
      color_temp: 400
      state: 'on'**
    **light.lampe_f2:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      friendly_name: Lampe F2
      supported_features: 0
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      color_temp_kelvin: 2500
      color_temp: 400
      state: 'on'
    switch.stehlampe_am_fenster:
      friendly_name: 'Stehlampe am Fenster '
      state: 'on'
    switch.projektor:
      current: true
      raw_state: true
      friendly_name: Stehlampe am Schreibtisch
      state: 'on'**
    light.schreibtischlampe:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 370
      effect_list: []
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.391
      - 65.659
      rgb_color:
      - 255
      - 166
      - 87
      xy_color:
      - 0.526
      - 0.387
      raw_state: true
      friendly_name: Schreibtischlampe
      supported_features: 23
      color_temp_kelvin: 2702
      color_temp: 370
      state: 'on'
    light.stehlampe_an_der_couch:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 370
      effect_list: []
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.391
      - 65.659
      rgb_color:
      - 255
      - 166
      - 87
      xy_color:
      - 0.526
      - 0.387
      raw_state: true
      friendly_name: Stehlampe an der Couch
      supported_features: 23
      color_temp_kelvin: 2702
      color_temp: 370
      state: 'on'
    light.couchecke:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 370
      effect_list: []
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.391
      - 65.659
      rgb_color:
      - 255
      - 166
      - 87
      xy_color:
      - 0.526
      - 0.387
      raw_state: true
      friendly_name: Couchecke
      supported_features: 23
      color_temp_kelvin: 2702
      color_temp: 370
      state: 'on'
    **light.weisse_kugel:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      friendly_name: Weiße Kugel
      supported_features: 0
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      color_temp_kelvin: 2500
      color_temp: 400
      state: 'on'`**

**Comment by quadroluxinator** [comment]
name: 'Master: Warmes Licht'
  entities:
    **light.lampe_f1:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      friendly_name: Lampe F1
      supported_features: 0
      color_temp_kelvin: 2500
      color_temp: 400
      state: 'on'
    light.lampe_f2:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      friendly_name: Lampe F2
      supported_features: 0
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      color_temp_kelvin: 2500
      color_temp: 400
      state: 'on'**
    switch.stehlampe_am_fenster:
      friendly_name: 'Stehlampe am Fenster '
      state: 'on'
    switch.projektor:
      current: true
      raw_state: true
      friendly_name: Stehlampe am Schreibtisch
      state: 'on'
    light.schreibtischlampe:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 370
      effect_list: []
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.391
      - 65.659
      rgb_color:
      - 255
      - 166
      - 87
      xy_color:
      - 0.526
      - 0.387
      raw_state: true
      friendly_name: Schreibtischlampe
      supported_features: 23
      color_temp_kelvin: 2702
      color_temp: 370
      state: 'on'
    light.stehlampe_an_der_couch:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 370
      effect_list: []
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.391
      - 65.659
      rgb_color:
      - 255
      - 166
      - 87
      xy_color:
      - 0.526
      - 0.387
      raw_state: true
      friendly_name: Stehlampe an der Couch
      supported_features: 23
      color_temp_kelvin: 2702
      color_temp: 370
      state: 'on'
    light.couchecke:
      min_color_temp_kelvin: 2702
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 370
      effect_list: []
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.391
      - 65.659
      rgb_color:
      - 255
      - 166
      - 87
      xy_color:
      - 0.526
      - 0.387
      raw_state: true
      friendly_name: Couchecke
      supported_features: 23
      color_temp_kelvin: 2702
      color_temp: 370
      state: 'on'
    **light.weisse_kugel:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      friendly_name: Weiße Kugel
      supported_features: 0
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      color_temp_kelvin: 2500
      color_temp: 400
      state: 'on'**

Lights integrated via Tapo are marked in bold.

**Comment by macflyhub** [comment]
And here is my scene code: 

`- id: '1675809517516'
  name: LED Strips ON
  entities:
    light.driveway_garage_led_strip:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 400
      effect_list:
      - aurora
      - bubbling cauldron
      - christmas
      - candy cane
      - flicker
      - grandma's christmas lights
      - hanukkah
      - haunted mansion
      - icicle
      - lightning
      - ocean
      - rainbow
      - raindrop
      - spring
      - sunrise
      - sunset
      - valentines
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: color_temp
      brightness: 128
      color_temp_kelvin: 2500
      color_temp: 400
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      friendly_name: LED Strips
      supported_features: 4
      state: 'on'
    light.driveway_led_right_side:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 400
      effect_list:
      - aurora
      - bubbling cauldron
      - christmas
      - candy cane
      - flicker
      - grandma's christmas lights
      - hanukkah
      - haunted mansion
      - icicle
      - lightning
      - ocean
      - rainbow
      - raindrop
      - spring
      - sunrise
      - sunset
      - valentines
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: color_temp
      brightness: 128
      color_temp_kelvin: 2500
      color_temp: 400
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      friendly_name: LED Right 
      supported_features: 4
      state: 'on'
    light.driveway_led_strip_left:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 400
      effect_list:
      - aurora
      - bubbling cauldron
      - christmas
      - candy cane
      - flicker
      - grandma's christmas lights
      - hanukkah
      - haunted mansion
      - icicle
      - lightning
      - ocean
      - rainbow
      - raindrop
      - spring
      - sunrise
      - sunset
      - valentines
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: color_temp
      brightness: 128
      color_temp_kelvin: 2500
      color_temp: 400
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      friendly_name: LED Strip Left
      supported_features: 4
      state: 'on'`

**Comment by petretiandrea** [comment]
Version 1.6.1 should fix this issue.
