### ISSUE TITLE
Tapo p125M not showing socket control

### ISSUE THREAD

**Issue by wash3re** [petretiandrea/home-assistant-tapo-p100#383]
I know the 125M is technically a matter device (and I can't get Matter to work with my container install) but mine is not setup with Matter.  It connects, and shows the overheat status, and the wifi strength, but not the load, which is obviously what matters.
repeating in Logs:
Failed to setup Error communication with API: Cannot connect to host x.x.x.x:80 ssl:default [Connect call failed ('x.x.x.x', 80)]
Config entry 'Smart Plug' for tapo integration not ready yet: Error communication with API: Cannot connect to host x.x.x.x:80 ssl:default [Connect call failed ('x.x.x.x', 80)]; Retrying in background

**Comment by petretiandrea** [comment]
Is the ip address reachable?

**Comment by wash3re** [comment]
> Is the ip address reachable?

Yep, that all works fine.  It is talking to the device (and I have two of them, same issue) since I can see the wifi signal for the device (as an example).

**Comment by irubnich** [comment]
I'm seeing the same

**Comment by irubnich** [comment]
I patched it in this PR: https://github.com/petretiandrea/home-assistant-tapo-p100/pull/405
