### ISSUE TITLE
L920 - Unable to set colour using colour wheel

### ISSUE THREAD

**Issue by cammcnab** [petretiandrea/home-assistant-tapo-p100#389]
Running v1.6.1 of this integration
for L920 / HW 1.0 / FW 1.0.9

Brightness ✅
Off / On ✅
Effects ✅ 
Change color via color wheel ❌

**Comment by moritzbindewald** [comment]
> Running v1.6.1 of this integration
> 
> for L920 / HW 1.0 / FW 1.0.9
> 
> 
> 
> Brightness ✅
> 
> Off / On ✅
> 
> Effects ✅ 
> 
> Change color via color wheel ❌

Same issue. Last workin version is 1.3.7

**Comment by Fruitsmart** [comment]
> Running v1.6.1 of this integration for L920 / HW 1.0 / FW 1.0.9
> 
> Brightness white_check_mark Off / On white_check_mark Effects white_check_mark Change color via color wheel x

Hello i have the Same issue.

**Comment by acs-lux** [comment]
Same issue

**Comment by gemmaker** [comment]
> Same issue v1.6.1
> 
> FX, On/Off and brightness work but no colour change.
> 
> Setting RGB via service also doesn't work

Same for me
L920
by TP-Link
Firmware: 1.0.9 Build 220422 Rel.150004
Hardware: 1.0

**Comment by ronsumst** [comment]
Same here with Device L920TP-Link Tapo 

I am also unable to change color via color wheel.
Other functions work OK :)

Firmware: 1.0.9 Build 220422 Rel.150004

**Comment by Armitage00** [comment]
Same with L920TP-Link Tapo

I can't change color via color wheel.
Other functions are OK :P

Firmware: 1.0.9 Build 220422 Rel.150004

**Comment by Derweis** [comment]
Ставлю +

Так же на последней прошивке

**Comment by hbarudin** [comment]
Just installed the integration and same issue here. Thank you for all your work!

**Comment by Sp0nsje** [comment]
> > Running v1.6.1 of this integration
> > for L920 / HW 1.0 / FW 1.0.9
> > Brightness ✅
> > Off / On ✅
> > Effects ✅
> > Change color via color wheel ❌
> 
> Same issue. Last workin version is 1.3.7

Got the same isseu fw and build. is it possible to downgrade to 1.3.7? i can only install: 
Main 1.4 - 1.6.1

**Comment by ashantyk** [comment]
same issue

L920
Firmware: 1.0.9 Build 220422 Rel.150004
Hardware: 1.0

Tapo Controller 1.6.1

**Comment by moritzbindewald** [comment]
Patch didn't solve the issue

**Comment by gemmaker** [comment]
> Patch didn't solve the issue

It didn't fix it but the behaviour is slightly different. Now, when using the colour wheel, you can try to select a different colour. But the selection pointer now snaps back to the colour it is actually displaying 
So it's 'half' working by displaying the correct colour in the integration that the light is actually displaying. Just can't change the colour itself except by the effects.

**Comment by Derweis** [comment]
Не работает на последнем обновлении / not working on last update

**Comment by gemmaker** [comment]
It's fixed!

**Comment by alp82** [comment]
I  confirm that v2.0.0 solves the color problems!

**Comment by petretiandrea** [comment]
Fixed in v2.0.0.
