### ISSUE TITLE
Problema tapo integration after remove and reinstall in ha 2023.03

### ISSUE THREAD

**Issue by soysnorre** [petretiandrea/home-assistant-tapo-p100#390]
Hi all,
After install HA 2023.03 begin mybtoroubles with tapo integration.
Removind and reinstalling I get this error:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

Anu known solution?
Thans in advance 
Br

**Comment by selvasalus** [comment]
Hi,
I have the same problem

**Comment by Tirzono** [comment]
I can confirm this issue happens to me as well. For me it hangs indefinitely:

![image](https://user-images.githubusercontent.com/8750041/222977576-f6bcb6fc-b31a-4096-b0ea-e9a08f75f075.png)

**Comment by mattogodoy** [comment]
Same problem here after upgrading to 2023.3.0. I have now updated HA to 2023.3.2, and the problem persists.

**Comment by kaanbrs** [comment]
Hello First of all, greetings from Turkey,
I think the solution is easy Tapo Brand Products are constantly causing problems. To fix this situation, we just need to determine a fixed ip address from our modem. I don't have problems such as being unreachable every time the connection is broken, I hope I helped, goodbye.

**Comment by soysnorre** [comment]
> Hello First of all, greetings from Turkey, I think the solution is easy Tapo Brand Products are constantly causing problems. To fix this situation, we just need to determine a fixed ip address from our modem. I don't have problems such as being unreachable every time the connection is broken, I hope I helped, goodbye.

Hi, this is notnthe problem. I have all my iot items with static ip at home and TAPO integration doesn't work from first HA Update in March.

Thanks in advance
Br

**Comment by darkusone** [comment]
Hi, same here, 

I have 5 switches, 4 are unavailable after update but one with hw version 2.0 is working fine.

I tried remove one of them, and when i try to add integration again...: 

![image](https://user-images.githubusercontent.com/21168136/224493063-bdced3a8-a955-4bac-a141-5b6d397a1fbc.png)

After some reboots another switch have started working, now i have 2 of 5 working, but I can't add any new..

All IP addresses are static and all was double checked to avoid hardware/network issues

**Comment by snakedm** [comment]
I've same problem too.... any solutions?

**Comment by DanielLaubeABB** [comment]
Hi, I am on 2023.3.6.
When I try to use the UI to add a device, I get 
Config flow could not be loaded: {"message":"Invalid handler specified"}

The config.yaml validation gives
Platform error switch.tapo - No module named 'plugp100'

Best regards!

**Comment by petretiandrea** [comment]
Try to update to 1.7.1
