### ISSUE TITLE
Failed to connect.

### ISSUE THREAD

**Issue by danecct** [petretiandrea/home-assistant-tapo-p100#394]
Hi Guys.
  I having trouble is shown failed to connecting. Even though I changed my password.

**Comment by SkoobyDu** [comment]
Does your device work in the TAPO app? I have problems with P100 plugs that become "unavailable" in HA; the fix I have found which works best is to delete the device in the TAPO app and then set it back up using the original name, when complete restart HA and the device should be available again without having to set it back up in HA.

I have no idea why HA loses it, but the above is the quickest method I have found to re-add.

**Comment by mrjrozycki** [comment]
Yeah I am having the same issue :/

**Comment by ldehner** [comment]
Removing and readding the plug in the tapo app solved the issue for me. Bevore I couldn't even ping the plug, after the ping was successful

**Comment by petretiandrea** [comment]
Try v2.0.0
