### ISSUE TITLE
L530 - Homeassistant icon and device info doesn't sync ok when changing colors

### ISSUE THREAD

**Issue by BunpGhost** [petretiandrea/home-assistant-tapo-p100#404]
Hi,

Changing color in my L530 lamp works, however, on homeassistant frontend, the icon and device related info are not reflecting what was done.

## Version of the integration

1.6.1

## Configuration

Device: L530
Firmware: 1.0.10 Build 221129 Rel. 193015
```yaml
I had troube finding the logs. I'm sorry
```

## Describe the bug

Ok, so, I'm going to try and describe in steps:

1. In the Tapo App or via homeAssistant automation change the color of the light to RED
2. The light changes to RED
3. In the Tapo app, visual feedback is RED
4. In Homeassistant, icon and device description do not update to RED but to default color
5. Change back to 2700k, for example.
6. In the Tapo app, visual feedback is 2700k
7. In Homeassistant, icon and device description do update to 2700 k correctly
8. Now in Homeassistant, change color to RED
9. Homeassistant: the icon and device info are correct, in RED.
10. Tapo App: Visual feedback is RED.

## Debug log

```text

I couldn't find the logs, correctly, sorry!

```

**Comment by petretiandrea** [comment]
Tried and 1.7.1 fix this issue. So remembers that polling period is 30seconds
