### ISSUE TITLE
Version 2.0.0 breaks all devices, unable to fix

### ISSUE THREAD

**Issue by lyricnz** [petretiandrea/home-assistant-tapo-p100#423]
Installed the new version from HACS today. All devices immediately unavailable. Deleted and readded, appears success, and overheat+signal sensors are working, but all others unknown

<img width="1008" alt="image" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/122371/eeb2fdc8-6f52-4f7d-a849-3c108b9fd39b">

HA logs show polling with success

```
2023-07-06 18:36:44.278 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.028 seconds (success: True)
2023-07-06 18:36:44.301 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.038 seconds (success: True)
2023-07-06 18:36:44.319 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.031 seconds (success: True)
2023-07-06 18:36:44.486 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.025 seconds (success: True)
2023-07-06 18:36:44.529 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.035 seconds (success: True)
```

What other config do you need? This all work previously.

I attempted to downgrade integration, this didn't help.  Also tried applying latest firmware updates.  Didn't help

**Comment by lyricnz** [comment]
[tapo-logs.txt](https://github.com/petretiandrea/home-assistant-tapo-p100/files/11966257/tapo-logs.txt)

**Comment by lyricnz** [comment]
Device was working before upgrade

<img width="1416" alt="image" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/122371/960a3df4-a4ad-40d9-8912-a8384c282872">

**Comment by lyricnz** [comment]
Adding some debug to the code, it looks like PlugTapoCoordinator() is setup with `self.has_power_monitor = True` and nothing is calling enable_power_monitor() to turn it on.

If I hack the code to set `self.has_power_monitor = True` in the init then it all starts working again

```python
class PlugTapoCoordinator(TapoCoordinator[PlugDeviceState]):
    def __init__(
        self,
        hass: HomeAssistant,
        device: PlugDevice,
        polling_interval: timedelta,
    ):
        super().__init__(hass, device, polling_interval)
        self.has_power_monitor = True # <==== here
        self.power_info = None
        self.energy_info = None

```

**Comment by Gilbertonl** [comment]
Yes, Confirmed that's working. Thanx

**Comment by XRedShark** [comment]
> Aggiungendo un po 'di debug al codice, sembra che PlugTapoCoordinator() sia configurato `self.has_power_monitor = False`e nulla stia chiamando enable_power_monitor() per accenderlo.
> 
> Se hackero il codice da impostare `self.has_power_monitor = True`nell'init, tutto ricomincia a funzionare
> 
> ```python
> class PlugTapoCoordinator(TapoCoordinator[PlugDeviceState]):
>     def __init__(
>         self,
>         hass: HomeAssistant,
>         device: PlugDevice,
>         polling_interval: timedelta,
>     ):
>         super().__init__(hass, device, polling_interval)
>         self.has_power_monitor = True # <==== here
>         self.power_info = None
>         self.energy_info = None
> ```

I confirm. Thank you!

**Comment by guru-gubbins** [comment]
Would someone kindly explain how to get to this bit of code to modify. It's not configuration.yaml

**Comment by RaidentaylorFilipeLeite85** [comment]
> Would someone kindly explain how to get to this bit of code to modify. It's not configuration.yaml

In "custom_components" you have a "tapo" folder. There you have a file called "coordinators.py". This fix is in this file.
And this worked.

**Comment by guru-gubbins** [comment]
Excellent - working fine now. Thanks very much indeed.

**Comment by rursache** [comment]
had the same issue, the fix above worked for me as well. thanks!

**Comment by petretiandrea** [comment]
Thanks for hints, have you right.
