### ISSUE TITLE
P110 not obtaining Energy or runtime data with V2 integration 

### ISSUE THREAD

**Issue by spetrie13** [petretiandrea/home-assistant-tapo-p100#425]
## Version of the integration
NAME = "tapo"
DOMAIN = "tapo"
VERSION = "2.0.0"

## Configuration
Device info
P110
by TP-Link
Firmware: 1.2.3 Build 230425 Rel.142542
Hardware: 1.0

## Describe the bug
Updated to the new version and now all existing entries are not reading any energy or runtime data.
Tried removing a device and adding it again. Device appears but with only 8 entities where it had 10 previously. Still no energy or runtime data. 

Sensors:
Chest Freezer (Switch is available)
Current power Unknown
Month energy Unknown
Month runtime Unknown
Overheat False
Signal level -52 dBm
Today energy Unknown
Today runtime Unknown

I can still control the device as a switch.

## Debug log

```

**Comment by RaidentaylorFilipeLeite85** [comment]
I have the same problem.

**Comment by lyricnz** [comment]
I'm not sure about all your exceptions, but your symptoms match #423

**Comment by RaidentaylorFilipeLeite85** [comment]
> I'm not sure about all your exceptions, but your symptoms match #423

Yes, you are right

**Comment by spetrie13** [comment]
yes same issue. Will try the fix.

**Comment by guru-gubbins** [comment]
same problem here

**Comment by spetrie13** [comment]
Fix in #423 
[](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/423)
