### ISSUE TITLE
TAPO Hub not connecting 

### ISSUE THREAD

**Issue by jonathanoakley** [petretiandrea/home-assistant-tapo-p100#431]
#### Bug
Following the update to 2.0.1 (Tapo integration), the Tapo Hub was reporting as not configured and further will not reinstall even when deleted and with a clean install

#### Log

Logger: homeassistant.config_entries
Source: custom_components/tapo/utils.py:15 
Integration: Tapo Controller ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/)) 
First occurred: 21:21:49 (5 occurrences) 
Last logged: 22:03:55

Error setting up entry Tapo Hub for tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 48, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 37, in async_setup_entry
    coordinator = value_or_raise(
                  ^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/utils.py", line 15, in value_or_raise
    raise value_or_error
custom_components.tapo.common_setup.DeviceNotSupported: Device 192.168.68.70 not supported!

**Comment by patfelst** [comment]
I have the same issue on 3 tapo devices which now won't set up. I think this integration  broke after the 2023.7.0 update, here is the log I see:
<img width="1148" alt="image" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/11342773/02adb88d-31e1-46e2-8462-f76894bee97c">

```log
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tapo/utils.py:15
Integration: tapo_p100 (documentation, issues)
First occurred: 8:38:28 AM (4 occurrences)
Last logged: 8:40:56 AM

Error setting up entry Spare Tapo Smart Plug for tapo
Error setting up entry Washing machine for tapo
Error setting up entry Pool pump for tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 48, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 37, in async_setup_entry
    coordinator = value_or_raise(
                  ^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/utils.py", line 15, in value_or_raise
    raise value_or_error
custom_components.tapo.common_setup.DeviceNotSupported: Device 192.168.20.202 not supported!
```

**Comment by patfelst** [comment]
Never mind, I deleted the integration, then re-installed, re-added my switches, and everything is working ok again now.

**Comment by Stevehans** [comment]
Same issue here, any idea what the underlying cause is?

I'll take a look at the code and see why that exception is thrown

**Comment by petretiandrea** [comment]
As integration says: `custom_components.tapo.common_setup.DeviceNotSupported: Device 192.168.20.202 not supported!`. Actually the hub is not supported, I will work on it.

**Comment by Stevehans** [comment]
My issue is different, I've got two p100 that were fine and now aren't, I'll open a new issue.

**Comment by jonathanoakley** [comment]
@Stevehans yeah it was the same for me - they were supported prior to the update but then seem not to be now
