### ISSUE TITLE
P110 Get Voltage values

### ISSUE THREAD

**Issue by iz8mbw** [petretiandrea/home-assistant-tapo-p100#438]
Hello, just asking if it's possible to get Voltage (Volt) from Tapo P110.

Thanks.
Ciao!

**Comment by Kisty** [comment]
Just checked the official Tapo app and there doesn't seem to be a voltage reading, unless I've missed something.

**Comment by codingneko** [comment]
> Is not possible to have the real-time Active Power (Watt) if the device doesn't know the real-time Voltage values.

It probably knows, just doesn't necessarily send it over the API, so the integration can't know. You'd have to modify the smart plug's firmware.

**Comment by KartoshaHv** [comment]
You can get voltage from the P110 without touching the firmware. The documented API calls don't include it, but the plug answers an undocumented `get_emeter_data` request over the same local protocol:

```python
import asyncio, os
from kasa import Discover  # pip install python-kasa

async def main():
    dev = await Discover.discover_single("192.168.1.135",
        username=os.environ["TAPO_EMAIL"], password=os.environ["TAPO_PASSWORD"])
    print(await dev.protocol.query({"get_emeter_data": None}))

asyncio.run(main())
```

Output on P110 (EU, fw 1.4.6):

```json
{"get_emeter_data": {"current_ma": 744, "voltage_mv": 234120, "power_mw": 141916, "energy_wh": 124}}
```

Needs "Third-Party Compatibility" enabled in the Tapo app. Undocumented, so it might disappear in a future firmware.

I built a small logger + dashboard around this: https://github.com/KartoshaHv/tapo-voltage-monitor
