### ISSUE TITLE
Invalid authentication error

### ISSUE THREAD

**Issue by Clairyfy** [petretiandrea/home-assistant-tapo-p100#44]
## Version of the custom_component

Newest

## Describe the bug

When trying to add a device, the window times out after a while and I get "invalid authentication" even though the credentials are correct.

**Comment by petretiandrea** [comment]
I Need more informazioni. Can you post here the log? And what is the type of device? 

:)

**Comment by Clairyfy** [comment]
I am super new here so what log?

**Comment by petretiandrea** [comment]
Go to <your_home_assistant_ip>:<port>/config/logs

**Comment by Clairyfy** [comment]
There is nothing there [
![Uploading Capture.PNG…]()
](url)

**Comment by Clairyfy** [comment]
![Capture](https://user-images.githubusercontent.com/84933127/120696482-e62c1600-c4ac-11eb-9479-0c801d7facbc.PNG)

**Comment by petretiandrea** [comment]
Try to associate your tapo, when the login fail, go here, press refresh and
post it

Il gio 3 giu 2021, 20:47 Clairyfy ***@***.***> ha scritto:

**Comment by Clairyfy** [comment]
No new issue :( but got this.
![Capture](https://user-images.githubusercontent.com/84933127/120744273-e7842f80-c4fa-11eb-9492-e13ea7dff475.PNG)

**Comment by petretiandrea** [comment]
Mmmm...this not help me ti understand what's wrong. This screenshot is acquired after a login attempt? Please try again

**Comment by Clairyfy** [comment]
![image](https://user-images.githubusercontent.com/84933127/120926005-5f10b500-c6db-11eb-8771-824d2239a2ea.png)
Same. Sorry for late respons

**Comment by marcusrivera1** [comment]
hi,  i have the same problem.
yesterday the integration worked fine, but today one of mi lights didnt work, so i deleted it and try to add again, but always says "invalid authentication". Im sure the IP, username and password are ok.  :(.. . I refreshed integration and restarted HA 3 times, but i cant add my ligth again :(

sorry 4 my english, im from chile (southamerica), thanks 4 all

**Comment by petretiandrea** [comment]
Hi, can you post a log? Without it I can't fix

**Comment by Clairyfy** [comment]
Please.

**Comment by petretiandrea** [comment]
Please, send me a video or something similar, without log I don't known what its going wrong. Not every user have that problem.

**Comment by pgpais** [comment]
just adding that I had a similar issue. However, in my case I noticed that the IP I was inserting was wrong. Check that again.

I actually had to restart the router because it was showing me two devices with the same IP, and the Tapo plug had the incorrect one.

**Comment by mikebroom** [comment]
I'm having a similar issue. My log shows nothing other than the "warning  we have found a custom integration that has not been tested by home assistant...

Unable to add my plugs or bulbs....

**Comment by MCarey2** [comment]
I was having the same problem. I found the issue to be that my email address in the username field was case sensitive. first letter capitalised no other caps. Hope this helps someone :)

**Comment by ludgart** [comment]
Hello, I have the same problem. Error log file: https://pastebin.com/g9UVkDNR

**Comment by petretiandrea** [comment]
Duplicate of #106
