### ISSUE TITLE
Names of entities messed up

### ISSUE THREAD

**Issue by saschaabraham** [petretiandrea/home-assistant-tapo-p100#446]
## Version of the integration

Version 2.2.0
## Configuration
Tapo Switch P110, Firmware 1.2.3 Rel 142542

## Describe the bug

After integration the switch with version 2.2.0, the names of the entities are messed up, the name of the device is doubled.

The device name ist Stecktdose_Powerventilator:

sensor.steckdose_powerventilator_steckdose_powerventilator_month_energy

Two other switches, integrated with a version <2.0 , are correct.

**Comment by saschaabraham** [comment]
Well, still not right, know all entities got the same name:



sensor.steckdose_powerventilator
sensor.steckdose_powerventilator_2
sensor.steckdose_powerventilator_3
sensor.steckdose_powerventilator_4
sensor.steckdose_powerventilator_5
sensor.steckdose_powerventilator_6

The Type of entities in the name is now missing.

**Comment by petretiandrea** [comment]
Have you try to remove and re-add device?

**Comment by saschaabraham** [comment]
Yes, because the names didn't change from "sensor.steckdose_powerventilator_steckdose_powerventilator_month_energy" to
"sensor.steckdose_powerventilator_month_energy" that i have expected.

So after the removal and readd the names where "sensor.steckdose_powerventilator", "sensor.steckdose_powerventilator_2" and so on.

**Comment by Harys-CZ** [comment]
> Well, still not right, now all entities got the same name:
> 
> sensor.steckdose_powerventilator sensor.steckdose_powerventilator_2 sensor.steckdose_powerventilator_3 sensor.steckdose_powerventilator_4 sensor.steckdose_powerventilator_5 sensor.steckdose_powerventilator_6
> 
> The Type of entities in the name is now missing.

Its the same for me.

**Comment by petretiandrea** [comment]
> 

I don't understand if you are using version 2.3.0? The issue is related to 2.2.0

**Comment by petretiandrea** [comment]
> Yes, because the names didn't change from "sensor.steckdose_powerventilator_steckdose_powerventilator_month_energy" to "sensor.steckdose_powerventilator_month_energy" that i have expected.
> 
> So after the removal and readd the names where "sensor.steckdose_powerventilator", "sensor.steckdose_powerventilator_2" and so on.

Sorry, I don't understand: are you using version 2.3.0? The issue is related to 2.2.0

**Comment by saschaabraham** [comment]
Yes, i used 2.3.0.

**Comment by petretiandrea** [comment]
@saschaabraham I'm working on a fix, this is that:

1. New version of home assinstant handles entity name in a different way. So in your device resume you will get the entity name of plug and sensor are without "Portatile" prefix cause relates to same device:
![Schermata del 2023-07-21 20-08-25](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/25798293/78c64606-15b7-4bc9-8c93-a0dece17e2fb)

2. The section "All entites" show you entities with prefix "Portatile":
![Schermata del 2023-07-21 20-08-53](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/25798293/16fe0d20-5619-4928-a9f0-20f9ce0d4dcc)

3. The dashboard behaves differently. If you create a group of entity (or  the ones created automatically created by dashboard) you will see something like point 1.
If you add a specific entity the dashboard assign a complete friendly name (left side of image below)
![Schermata del 2023-07-21 20-09-45](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/25798293/9aaf3166-9325-4032-bc8d-2454e168003f)

**Comment by saschaabraham** [comment]
I have checked the 446 branch and now the entities are correct.

switch.steckdose_powerventilator
sensor.steckdose_powerventilator_current_power
sensor.steckdose_powerventilator_month_energy
sensor.steckdose_powerventilator_month_runtime
binary_sensor.steckdose_powerventilator_overheat
sensor.steckdose_powerventilator_signal_level
sensor.steckdose_powerventilator_today_energy
sensor.steckdose_powerventilator_today_runtime
