### ISSUE TITLE
invalid auth out of nowhere

### ISSUE THREAD

**Issue by IIV-NATHAN-VII** [petretiandrea/home-assistant-tapo-p100#448]
Failed to setup, invalid auth

Was working fine today, all of a sudden my setup stopped connecting to my bulbs as another user seems to have posted.
https://github.com/petretiandrea/home-assistant-tapo-p100/issues/447

Thought i'd try re-installing but now getting this.

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 176, in _try_setup_api
    return value_or_raise(
           ^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/helpers.py", line 12, in value_or_raise
    raise value_or_error
plugp100.responses.tapo_exception.TapoException: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 91, in async_step_user
    api = await self._try_setup_api(user_input)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 180, in _try_setup_api
    self._raise_from_tapo_exception(error)
  File "/config/custom_components/tapo/config_flow.py", line 187, in _raise_from_tapo_exception
    raise InvalidAuth from exception
custom_components.tapo.errors.InvalidAuth

**Comment by IIV-NATHAN-VII** [comment]
> Same here
> 
> ![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/132147743/fb47e660-92fc-48e3-8fa6-c1db5e9f0347)
> 
> 

I'm glad it's not just my end! No more pulling my hair out I guess time to sit and wait lol.

**Comment by MrJamsn** [comment]
Same here. In the loggs it tells me that the device is not supported but i did not do a device update. Was working fine this morning, now ir is broken

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 48, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 37, in async_setup_entry
    coordinator = value_or_raise(
                  ^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/utils.py", line 15, in value_or_raise
    raise value_or_error
custom_components.tapo.common_setup.DeviceNotSupported: Device 192.168.178.59 not supported!

**Comment by IIV-NATHAN-VII** [comment]
2.3.0 is still broken

**Comment by MrJamsn** [comment]
What do you mean with 2.3.0? Was there an update on tapo hacs?

**Comment by IIV-NATHAN-VII** [comment]
> What do you mean with 2.3.0? Was there an update on tapo hacs?

8 hours ago it seems

**Comment by MrJamsn** [comment]
I am running 2.0.1

maybe he is running an proxy server and it has a problem..

**Comment by IIV-NATHAN-VII** [comment]
> I am running 2.0.1
> 
> 
> 
> maybe he is running an proxy server and it has a problem..
> 
> 

I was finishing a disco script for my lights, does dawn on me now, it says this communicates via LAN and I hope it does otherwise his server may have got flooded by me (if there is one and) (this wouldn't exactly be my fault though as I see 0 mention of this anywhere and am led to believe it's only MY network I'd be spamming..)

**Comment by petretiandrea** [comment]
> Same here. In the loggs it tells me that the device is not supported but i did not do a device update. Was working fine this morning, now ir is broken
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tapo/__init__.py", line 48, in async_setup_entry
>     raise error
>   File "/config/custom_components/tapo/__init__.py", line 37, in async_setup_entry
>     coordinator = value_or_raise(
>                   ^^^^^^^^^^^^^^^
>   File "/config/custom_components/tapo/utils.py", line 15, in value_or_raise
>     raise value_or_error
> custom_components.tapo.common_setup.DeviceNotSupported: Device 192.168.178.59 not supported!
> 
> 
> Reinstalling brings me the same error:invalid auth. email has no capital letters

What type of device?

**Comment by IIV-NATHAN-VII** [comment]
> > Same here. In the loggs it tells me that the device is not supported but i did not do a device update. Was working fine this morning, now ir is broken
> > Traceback (most recent call last):
> > File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
> > result = await component.async_setup_entry(hass, self)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/config/custom_components/tapo/**init**.py", line 48, in async_setup_entry
> > raise error
> > File "/config/custom_components/tapo/**init**.py", line 37, in async_setup_entry
> > coordinator = value_or_raise(
> > ^^^^^^^^^^^^^^^
> > File "/config/custom_components/tapo/utils.py", line 15, in value_or_raise
> > raise value_or_error
> > custom_components.tapo.common_setup.DeviceNotSupported: Device 192.168.178.59 not supported!
> > Reinstalling brings me the same error:invalid auth. email has no capital letters
> 
> What type of device?

I have Bulbs: L530 and L630 and plug P110, was working fine, got the same error as this person did initially. then invalid auth on re-install attempt. 

Weird as they were working absolutely fine.

**Comment by IIV-NATHAN-VII** [comment]
[@petr](https://github.com/petretiandrea) If there's anything I can run for you to help diagnose please let me know, I'd like to contribute but am fairly new to this home-assistant game.

**Comment by Damiasroca** [comment]
Same here, I have two P110 and four P100.
P110 are working, P100 throw the "custom_components.tapo.common_setup.DeviceNotSupported".
Deleted and tried to re-add them, and now I get the invalid credentials error. 

All of them are working just fine on the android Tapo app.

**Comment by IIV-NATHAN-VII** [comment]
> Same here, I have two P110 and four P100. P110 are working, P100 throw the "custom_components.tapo.common_setup.DeviceNotSupported". Deleted and tried to re-add them, and now I get the invalid credentials error.
> 
> All of them are working just fine on the android Tapo app.

Interesting how some of your devices are working, all of mine simply seemed to die (except from Tapo app), perhaps TP-Link rolled out a new firmware, are you also located in the UK? Sometimes they roll out by country.

None of my L530 or L630 bulbs work with home-assistant anymore and neither does my P110. :(

**Comment by Damiasroca** [comment]
> > Same here, I have two P110 and four P100. P110 are working, P100 throw the "custom_components.tapo.common_setup.DeviceNotSupported". Deleted and tried to re-add them, and now I get the invalid credentials error.
> > All of them are working just fine on the android Tapo app.
> 
> Interesting how some of your devices are working, all of mine simply seemed to die (except from Tapo app), perhaps TP-Link rolled out a new firmware, are you also located in the UK? Sometimes they roll out by country.
> 
> None of my L530 or L630 bulbs work with home-assistant anymore and neither does my P110. :(

Located in Spain,

I dont think It has anything to do with any new firmware. Mine are down on Homeassistant since 2 hours ago, and they are scheduled to autoupdate at night, so I discarded that

In my opinion it has something to do with TP-Link cloud, something has changed on their side.

**Comment by IIV-NATHAN-VII** [comment]
> > > Same here, I have two P110 and four P100. P110 are working, P100 throw the "custom_components.tapo.common_setup.DeviceNotSupported". Deleted and tried to re-add them, and now I get the invalid credentials error.
> > > All of them are working just fine on the android Tapo app.
> > 
> > 
> > Interesting how some of your devices are working, all of mine simply seemed to die (except from Tapo app), perhaps TP-Link rolled out a new firmware, are you also located in the UK? Sometimes they roll out by country.
> > None of my L530 or L630 bulbs work with home-assistant anymore and neither does my P110. :(
> 
> Located in Spain,
> 
> I dont think It has anything to do with any new firmware. Mine are down on Homeassistant since 2 hours ago, and they are scheduled to autoupdate at night, so I discarded that
> 
> In my opinion it has something to do with TP-Link cloud, something has changed on their side.

I'd reluctantly have to agree with you, I saw there was a big fuss about TP-Link KASA and TP-Link disabling the Local API a few years back, think they restored it in the end because so many people were rightly peed off about it. 

I've left feedback in the Tapo app for every one of their product categories suggesting they make an integration to home-assistant and that thousands of their users are already using an un-official integration. (you should too, we should try make some noise about this).

**Comment by Damiasroca** [comment]
Now my P110 went down with same error

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 40, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 38, in async_setup_entry
    return await device.initialize_device(hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/tapo_device.py", line 32, in initialize_device
    raise DeviceNotSupported(f"Device {host} not supported!")
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.3.99 not supported!`

I found the next error on logs from 9 hours ago, I think it has something to do with Tapo API, maybe it's related to the invalid auth error:

`Logger: custom_components.tapo.config_flow`
`Source: custom_components/tapo/config_flow.py:91`
`Integration: TP-Link Tapo ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100)[issues]`
`(https://github.com/petretiandrea/home-assistant-tapo-p100/issues))`
`First occurred: 00:30:06 (1 occurrences)`
`Last logged: 00:30:06`

`Tapo exception -1501`

No way to add any Tapo smart plugs on Homeassistant now for me. Everything works fine on the Tapo app

**Comment by IIV-NATHAN-VII** [comment]
Random one, but I noticed I have 2FA (two factor authentication) enabled on my Tapo app, it wasn't a problem before and I'm pretty sure it's always been enabled, but could this be the issue if they implemented it into their API?
Just a thought.

**Comment by petretiandrea** [comment]
> Random one, but I noticed I have 2FA (two factor authentication) enabled on my Tapo app, it wasn't a problem before and I'm pretty sure it's always been enabled, but could this be the issue if they implemented it into their API?
> Just a thought.
> Edit: Tested with 2FA disabled, still invalid auth. (Tapo app works fine, and nothing has changed in my setup since it was working before)

I think could be a problem, I've 2FA disabled and I'm able to connect without any issue

**Comment by IIV-NATHAN-VII** [comment]
> > Random one, but I noticed I have 2FA (two factor authentication) enabled on my Tapo app, it wasn't a problem before and I'm pretty sure it's always been enabled, but could this be the issue if they implemented it into their API?
> > Just a thought.
> > Edit: Tested with 2FA disabled, still invalid auth. (Tapo app works fine, and nothing has changed in my setup since it was working before)
> 
> I think could be a problem, I've 2FA disabled and I'm able to connect without any issue

Hey, I disabled 2FA to test and still got the invalid credentials error, was working fine before.

**Comment by petretiandrea** [comment]
Your tapo device has access to internet connection?

**Comment by IIV-NATHAN-VII** [comment]
> Your tapo device has access to internet connection?

Yeah, I can control them over 4G using Tapo app (just tested).

**Comment by petretiandrea** [comment]
Try to remove and re-add to tapo app

**Comment by IIV-NATHAN-VII** [comment]
> Try to remove and re-add to tapo app

Okay, will post back results.

**Comment by IIV-NATHAN-VII** [comment]
> Try to remove and re-add to tapo app

Interestingly, my removed and re-added device in Tapo app now shows up in Home-Assistant, god knows why that's the case, but thank you! I will buy you a coffee at some point.

**Comment by petretiandrea** [comment]
> 

Coffee is always welcome ;)

General warning: The Tapo device needs to be synchronized with the cloud, so when you do account-related operations: activate/deactivate 2FA, change password or something similar, then you experience some problems logging in again.

**Comment by Alaskapclos** [comment]
got the same issues every time when i have to reboot my hass installation. And the issue comes when there was a power outage in my server room.
No power outage in the rooms where all my P110 plugs are installed.
So i deleted all my plugs in the Tapo app...there are many plugs...and put it back in the app...and after that they were able to show up in HomeAssistant. No upper case in the email, even in the password...and no 2FA. 
This procedure was 7 times in the last few days, sometimes because of reboot, one time power outage. After every event, all entities of the Tapo devices are gone, and every time i have to delete and re-add them to the app, and then to HA...this behaviour is since 2 weeks...before power outages or reboots had no effect to the HA.
Just for your interest...

**Comment by petretiandrea** [comment]
> got the same issues every time when i have to reboot my hass installation. And the issue comes when there was a power outage in my server room.
> No power outage in the rooms where all my P110 plugs are installed.
> So i deleted all my plugs in the Tapo app...there are many plugs...and put it back in the app...and after that they were able to show up in HomeAssistant. No upper case in the email, even in the password...and no 2FA. 
> This procedure was 7 times in the last few days, sometimes because of reboot, one time power outage. After every event, all entities of the Tapo devices are gone, and every time i have to delete and re-add them to the app, and then to HA...this behaviour is since 2 weeks...before power outages or reboots had no effect to the HA.
> Just for your interest...

The integration is based from ip address, so be sure your router don't change the ips of your device when the events you describe happens

**Comment by MuddyLoggins** [comment]
> > Try to remove and re-add to tapo app
> 
> Interestingly, my removed and re-added device in Tapo app now shows up in Home-Assistant, god knows why that's the case, but thank you! I will buy you a coffee at some point.

Thank You for posting the fix, same thing happened to myself with the P100 plugs. Removing and re adding them in the tapo app fixed the issue.

**Comment by MrJamsn** [comment]
I did a reconnect, device (P115) was working yesterday and this morning same error again.

**Comment by Alaskapclos** [comment]
Same here, removed from app and re-added to app worked...but only for a few hours...the game starts every few hours....re-add all my plugs to the app....then reload all plugs in hassio...wait a few hours, and repeat...
it is like in the move edge of tomorrow: remove - re-add - repeat

in the Tapo-App and in the app "Watt" on iOS everything works fine.

`2023-07-26 07:41:00.003 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Gefriertruhe for tapo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/__init__.py", line 40, in async_setup_entry
raise error
File "/config/custom_components/tapo/__init__.py", line 38, in async_setup_entry
return await device.initialize_device(hass)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/tapo_device.py", line 32, in initialize_device
raise DeviceNotSupported(f"Device {host} not supported!")
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.188.125 not supported!
2023-07-26 07:41:00.006 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Trockner for tapo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/__init__.py", line 40, in async_setup_entry
raise error
File "/config/custom_components/tapo/__init__.py", line 38, in async_setup_entry
return await device.initialize_device(hass)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/tapo_device.py", line 32, in initialize_device
raise DeviceNotSupported(f"Device {host} not supported!")
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.188.122 not supported!
2023-07-26 07:41:00.008 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Kaffeemaschine for tapo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/__init__.py", line 40, in async_setup_entry
raise error
File "/config/custom_components/tapo/__init__.py", line 38, in async_setup_entry
return await device.initialize_device(hass)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/tapo_device.py", line 32, in initialize_device
raise DeviceNotSupported(f"Device {host} not supported!")
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.188.120 not supported!`

**Comment by IIV-NATHAN-VII** [comment]
I can confirm all but 4 of my devices have lost connection to home-assistant @petretiandrea I've not changed any settings in tapo app or account, when I try to re-add the devices I get invalid credentials again. This issue is not solved. :-( 

Another coffee if it gets fixed?

**Comment by rmeena21** [comment]
Cant connect my P110. Invalid creds

All has static IP
I can see and control them on tapo mobile app
reinstalled hacs and tapo integration. no luck

I dont know what to do next
