### ISSUE TITLE
Changing effect Brightness Tapo L920 

### ISSUE THREAD

**Issue by thedotor** [petretiandrea/home-assistant-tapo-p100#458]
Brightness change of a single colour is working, favourite colours is working & colour wheel select is working, brightness change is working for these. Still has the issue of selecting an effect, appears to be every effect, jumping to full brightness when selected & when you adjust the brightness for the effect it jumps back to the last full colour at the brightness that was selected.

Brightness can be changed in the app for an effect but does not update in home assistant, if a solid colour is selected via the app or home assistant both are updated and show the correct info. 

Firmware: 1.0.9 Build 220422 Rel.150004
Hardware: 1.0

With v2.3.1 Release

**Comment by petretiandrea** [comment]
Fixed in [2.5.0](https://github.com/petretiandrea/home-assistant-tapo-p100/commit/fb8ab1dff26f72ba990f13c9bd0580063552b368)
