### ISSUE TITLE
home-assistant-tapo-p110 integration devices regularly become a status ' Failed to Set-up'

### ISSUE THREAD

**Issue by PaulTheBlur** [petretiandrea/home-assistant-tapo-p100#464]
I have just upgraded Home Assistant to 2023.8, and on doing so 13 of my TAPO P110 devices now show 'Failed to Set-up'.

They were working before the Upgrade.

This also happened on a previous minor upgrade.  Then I have to remove the TAPO device from the TP=Link app and then add it again is Home Assistant found it, but this is not only a real pain but I am losing valuable Power usage data when I reset the devices to re-add to the app, and also I look these devices from any schedules/routines set-up in either Alexa or TP-Link App.

Please fix so this does not happen.

All devices are on the same Firmware (1.2.3 Build 230425 Rel.142542).

Hardware: 1.0

**Comment by paterson37** [comment]
I had the same issue with one device after upgrading as per my discussion thread posted earlier.

**Comment by kimvognsen** [comment]
same her

**Comment by petretiandrea** [comment]
The upgrade to homeassistant 2023.8 requires python 11, there is a issue related to python 11 migration #417
