### ISSUE TITLE
Cant connect with H200 Hub 

### ISSUE THREAD

**Issue by cha2hyun** [petretiandrea/home-assistant-tapo-p100#465]
I already checked https://github.com/petretiandrea/home-assistant-tapo-p100/issues/354
But it seems not work with H200 
any updates with tapo hub and accessories which doesnt have ip addrress?

**Comment by petretiandrea** [comment]
Actually, only H100 is partially supported

**Comment by petretiandrea** [comment]
Release 2.10.0 now support it

**Comment by pektommy** [comment]
> I already checked #354 But it seems not work with H200 any updates with tapo hub and accessories which doesnt have ip addrress?

Hello,

did you manage to connect with the latest version? me and some of my partners still can't connect

**Comment by cha2hyun** [comment]
> > I already checked #354 But it seems not work with H200 any updates with tapo hub and accessories which doesnt have ip addrress?
> 
> Hello,
> 
> did you manage to connect with the latest version? me and some of my partners still can't connect

Still cant connect with h200

**Comment by Omnichannel-nz** [comment]
Likewise with H200, repo says it's still a work in progress -  is that still the case?
