### ISSUE TITLE
Tapo integration fail to login on every HA reboot

### ISSUE THREAD

**Issue by simonefiorini01** [petretiandrea/home-assistant-tapo-p100#467]
Hello Andrea,

I'm facing an issue regarding your Tapo integration: every time I reboot HA, the integration fail to login.

Here some informations:
- Version of the integration: 2.4.0
- Configuration: I've only one L900 led strip configured, last version available

In order to solve the error I remove the led strip from the official Tapo app, the I re-add it.
Returning to Tapo HA integration, I click refresh and all works correctly.

As you can imagine, I can consider this only as a workaround and no as a solution.

Account email has no capital letters.

Log file attached.

Please let me know if you need some further information.

Thanks,
Simone
[home-assistant_tapo_2023-08-04T23-20-40.797Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/12265138/home-assistant_tapo_2023-08-04T23-20-40.797Z.log)

**Comment by IIV-NATHAN-VII** [comment]
I thought this was fixed but I can also report half my devices have just been disconnected from HA again ☹️. 

I think TP-Link doesn't approve.
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/3885026/ca0e0f0f-b1f8-4034-b4f4-70ece1b8cbfb)

**Comment by IIV-NATHAN-VII** [comment]
I still feel like this could be rate limits, is it possible to get an API key for every device with one API call? 

I'm also assuming it stores the device type right and doesn't request it each time? Just brainfarting here

**Comment by IIV-NATHAN-VII** [comment]
@petretiandrea do you think there's a limit to the amount of API keys one can request before tapo starts refusing?

Is it possible to store the keys given by API instead of requesting new ones each reboot?

Think that could be our issue.

**Comment by petretiandrea** [comment]
Doing some reverse-engineering on app, there is no mechanismi for rate-limiting API on local network side. I'm working to make integration more stable

**Comment by petretiandrea** [comment]
2.5.0 improve logging error, so retry with this new version and post here the log

**Comment by simonefiorini01** [comment]
Just updated to 2.5.0 version.
Log attached.

[home-assistant_tapo_2023-08-12T18-01-06.872Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/12327996/home-assistant_tapo_2023-08-12T18-01-06.872Z.log)

**Comment by simonefiorini01** [comment]
Following a log that show the integration working correctly (using the workaround explained before).
I don't know if it can be usefull for throubleshooting.
[home-assistant_tapo_2023-08-13T10-47-28.368Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/12329347/home-assistant_tapo_2023-08-13T10-47-28.368Z.log)

**Comment by ThiSchmidt** [comment]
Here my Log after Update to 2.5.0 and restart
[home-assistant_2023-08-14T07-59-09.511Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/12332693/home-assistant_2023-08-14T07-59-09.511Z.log)

**Comment by IIV-NATHAN-VII** [comment]
> Doing some reverse-engineering on app, there is no mechanismi for rate-limiting API on local network side. I'm working to make integration more stable.
> 
> 
> 
> Is your home assistant running through wifi or cable connection?

I was using Ethernet, I've since replaced my Tapo products with WiZ, had issues with bulbs dimming for 60 seconds when power cycled and flashing on first command (even from tapo app). 

Hope everyone manages to get their stuff sorted.

**Comment by simonefiorini01** [comment]
> Doing some reverse-engineering on app, there is no mechanismi for rate-limiting API on local network side. I'm working to make integration more stable.
> 
> Is your home assistant running through wifi or cable connection?

Sorry, I didn’t read this question.
I have a Proxmox client, connected with ethernet, that virtualize Home Assistant VM.

**Comment by ThiSchmidt** [comment]
My Homeassistant is running on a Synology NAS VM connected by ethernet.

**Comment by petretiandrea** [comment]
The issues seems to be related to `TapoError.ERR_SESSION_TIMEOUT`

**Comment by petretiandrea** [comment]
https://github.com/petretiandrea/home-assistant-tapo-p100/pull/481 and version 2.6.1 should fix timeout session issue
