### ISSUE TITLE
Tapo P110 keeps switching from available to unavailable (and vice versa) in seconds.

### ISSUE THREAD

**Issue by Pippo1989** [petretiandrea/home-assistant-tapo-p100#470]
DESCRIPTION/BUG:
As the title says, I have a Tapo P110 plug which some days ago started to switch from available to unavailable (and vice versa) in seconds, continuing to do so 24 hours a day.
Rebooting the plug won't solve the issue.

VERSION OF THE INTEGRATION:
v2.4.0

CONFIGURATION:
Tapo P110 - 1.2.3 Build 230425 Rel.142542 (latest update available).
HASSIO running on Raspberry Pi 4.

CRITICAL LOGS:
Here you can find the critical logs from start to boot completed:
[home-assistant_profiler_2023-08-08T06-36-20.982Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/12288171/home-assistant_profiler_2023-08-08T06-36-20.982Z.log)

![Tapo P110](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/98611451/c5b23e64-11cf-4559-9ca8-49422aa6d19c)

**Comment by acamposcar** [comment]
Same problem with my P100 and P110

**Comment by geidorei** [comment]
Snap, seamed to fic previous few core updates, but started again...

**Comment by richee123** [comment]
Yes, i am experiencing the same issue now with P110 plugs. I switched from meross 310 after they limited my queries for the power sensor.

**Comment by 1ndecis** [comment]
Hello, i have the same problem, my switch are often unavailable
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/142091724/bfcdd58f-8dc2-4265-9505-195eca929079)

**Comment by Javirln** [comment]
Reported the same behavior a while back https://github.com/petretiandrea/home-assistant-tapo-p100/issues/387

The new suggested version did not solve it though.
