### ISSUE TITLE
Adding the Integration

### ISSUE THREAD

**Issue by ChrisMarriott38** [petretiandrea/home-assistant-tapo-p100#476]
Trying to get this working but when i click Add integration. Select TP-Link Tapo - A message pops up saying "Error
Config flow could not be loaded: {"message":"Invalid handler specified"}"

Wondering if you had any ideas? Thanks
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/142601601/fc643a29-2032-4641-a8d6-b769a9cd786b)

**Comment by petretiandrea** [comment]
I need more log data

**Comment by Barbo91** [comment]
Ciao/Hello,
I Think i have the same problem, where i find logs to upload that you need? Here is a screenshot
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/22633159/6db3e110-05e4-4f40-bc21-743ebdfe5ef5)

Errore
Impossibile caricare il flusso di configurazione: Unknown error

**Comment by sarkarautomate** [comment]
Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 11:09:18 PM (3 occurrences)
Last logged: 11:09:58 PM

Unable to install package plugp100==3.7.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a08cd0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a096d0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a0a290>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a0add0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a0b650>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ ERROR: Could not find a version that satisfies the requirement plugp100==3.7.1 (from versions: none) ERROR: No matching distribution found for plugp100==3.7.1 [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip
Unable to install package plugp100==3.7.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861e89d0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861e9350>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861e9ed0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861ea990>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861eb110>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ ERROR: Could not find a version that satisfies the requirement plugp100==3.7.1 (from versions: none) ERROR: No matching distribution found for plugp100==3.7.1 [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip
Unable to install package plugp100==3.7.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900ac710>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900ace10>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900adc10>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900ae710>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900aef90>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ ERROR: Could not find a version that satisfies the requirement plugp100==3.7.1 (from versions: none) ERROR: No matching distribution found for plugp100==3.7.1 [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

**Comment by sarkarautomate** [comment]
> 

Logger: aiohttp.server
Source: requirements.py:290
First occurred: 11:09:58 PM (1 occurrences)
Last logged: 11:09:58 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 149, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 847, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 865, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 967, in async_create_flow
    await _load_integration(self.hass, handler_key, self._hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2034, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 420, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 252, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 290, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for tapo not found: ['plugp100==3.7.1'].

**Comment by petretiandrea** [comment]
> Logger: homeassistant.util.package Source: util/package.py:107 First occurred: 11:09:18 PM (3 occurrences) Last logged: 11:09:58 PM
> 
> Unable to install package plugp100==3.7.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a08cd0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a096d0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a0a290>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a0add0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f90a0b650>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ ERROR: Could not find a version that satisfies the requirement plugp100==3.7.1 (from versions: none) ERROR: No matching distribution found for plugp100==3.7.1 [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip Unable to install package plugp100==3.7.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861e89d0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861e9350>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861e9ed0>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861ea990>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f861eb110>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ ERROR: Could not find a version that satisfies the requirement plugp100==3.7.1 (from versions: none) ERROR: No matching distribution found for plugp100==3.7.1 [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip Unable to install package plugp100==3.7.1: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900ac710>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900ace10>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900adc10>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900ae710>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f900aef90>: Failed to establish a new connection: [Errno 101] Network unreachable')': /simple/plugp100/ ERROR: Could not find a version that satisfies the requirement plugp100==3.7.1 (from versions: none) ERROR: No matching distribution found for plugp100==3.7.1 [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip

You having some issue with your connection: "Network unreachable". Can you ping 8.8.8.8 from your home assistant running device's?

**Comment by ChrisMarriott38** [comment]
My log just says this. But it's odd. Im sure i'm entering it right? Username, Key, Secret key, Station ID. Usuaing manual install method as i'm running it on a Synology

This error originated from a custom integration.

Logger: custom_components.solis.soliscloud_api
Source: custom_components/solis/soliscloud_api.py:216
Integration: Solis Inverter (documentation, issues)
First occurred: 13:38:25 (2 occurrences)
Last logged: 13:39:30

No inverters found

**Comment by ChrisMarriott38** [comment]
I've tried remove and add again and I just see this in the log. Using HA via Docker on a Synology. So Can't use HACKS to install.

My log just shows this 

Logger: homeassistant.config_entries
Source: config_entries.py:865
First occurred: 13:45:40 (1 occurrences)
Last logged: 13:45:40

Error occurred loading flow for integration tapo: No module named 'custom_components.tapo.hub'

**Comment by ChrisMarriott38** [comment]
This was my mistake, the sub folders did not upload. It's working now :) Thanks!

**Comment by Viper0183** [comment]
Hi, I am having the same error, How did you resolve this?
