### ISSUE TITLE
Controll devices installed other location than HA installed

### ISSUE THREAD

**Issue by Korte68** [petretiandrea/home-assistant-tapo-p100#483]
**Is your feature request related to a problem? Please describe.**

I have HA installed at home. I would like to use Tapo devices at my weekend house, where I do not want to install HA.
Current souluten works only on local network.

**Describe the solution you'd like**

It would be great if we can control the devices over tapo cloud.

Thank you

**Describe alternatives you've considered**

**Device Info**
Please execute this python script. You can save it as `main.py` and run it by using `python main.py`.
Be sure to have the latest version of `plugp100` library, by installing it through `pip install plugp100`.
```python
import asyncio

from plugp100 import TapoApiClient, TapoApiClientConfig, LightEffect

async def main():
    # create generic tapo api
    config = TapoApiClientConfig("<ip>", "<email>", "<passwd>")
    sw = TapoApiClient.from_config(config)
    await sw.login()
    await sw.on()
    await sw.set_brightness(100)
    state = await sw.get_state()
    print(state.get_unmapped_state())

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.run_until_complete(asyncio.sleep(0.1))
loop.close()

if __name__ == "__main__":
    main()
```

**Comment by petretiandrea** [comment]
The integration relies on local network communication, so you can't communicate with a remote network in a simple way. 
I'd suggest you to install home assistant on your second house and relies on https://github.com/custom-components/remote_homeassistant to connect the two home assistant instances.

More complex way require strong networking knowledge, for example you can use a VPN to connect your first and second house and create a new network where devices of both houses are reachable from each one.
