### ISSUE TITLE
v2.6.1 fails to report data

### ISSUE THREAD

**Issue by jsuelwald** [petretiandrea/home-assistant-tapo-p100#485]
After updating to v2.6.1 my device doesn't report current power anymore. Downgraded to v2.6.0 via HACS and the Plug works again as usual.

<img width="493" alt="image" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/2499585/99e6a99a-7911-4fba-8217-6893bb0c244d">
(This is v2.6.0)

<img width="514" alt="image" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/2499585/f58268c0-d005-45ab-ac55-3bde60dac360">
And this is with v2.6.1

**Comment by TommisGR** [comment]
Same issue and fix with my p110
Downgrading to 2.6.0 fixes it.

**Comment by petretiandrea** [comment]
v2.7.0 should fix
