### ISSUE TITLE
Tapo Control not found in Integration

### ISSUE THREAD

**Issue by avviano** [petretiandrea/home-assistant-tapo-p100#49]
Hi, I installed through HACS and your Github repo and restarted the server. Seemed like all went well. I can see that the folder TAPO was created. But when I go to integration and search for TAPO, nothing comes up. Any idea what the issue could be?

I looked in HACS AND Configuration > Integration. No Tapo found. 

I have Tapo Control version 1.1.2 - Home Assistant Version core-2021-6-6 (newest version).

**Comment by petretiandrea** [comment]
Please send me a screenshots with search box and post here log after installation from hacs :)

**Comment by jaytrannn** [comment]
+1
Facing it today.  Log post after install "Tapo Control" is fine, no problem. But when search "Tapo" in integration, i don't see anymore

**Comment by zephirus** [comment]
It's not showing for me either. I installed using HACS.

**Comment by TeDeVPrime** [comment]
i can confirm that it is not showing in the integrations.

**Comment by BunpGhost** [comment]
I had to delete my Tapo_camera integration from hacs and then this worked.
When I added this after the tapo_camera it create a "tapo_control" folder and I guess it was expecting the "tapo" folder instead.

**Comment by petretiandrea** [comment]
Try new version `1.2.0` and follow the [video ](https://github.com/petretiandrea/home-assistant-tapo-p100/blob/main/README.md) to install the integration

**Comment by BunpGhost** [comment]
> Try new version `1.2.0` and follow the [video ](https://github.com/petretiandrea/home-assistant-tapo-p100/blob/main/README.md) to install the integration

Excellent work. It works very well now! Thank you
