### ISSUE TITLE
L530 failed setup

### ISSUE THREAD

**Issue by rhortal** [petretiandrea/home-assistant-tapo-p100#496]
## Version of the integration

2.6.1

## Configuration

L530 firmware build 2390721 rel 224802

```yaml
Add your logs here.
```

## Describe the bug

I have 2 L520 bulbs and 2 P100 plugs that work fine. However, since the latest update of this repo the 2 L530 bulbs appear in a state of "failed setup, will retry".
The Tapo app still works correctly with them.
I have updated HomeAssistant to the latest version, as well as the HomeAssistant OS.

## Debug log

```text

Add your logs here.

```

**Comment by HillmanImp** [comment]
I think I had the same problem, but it seems to have gone away with upgrading the integration to 2.7.0

**Comment by rhortal** [comment]
2.7.0 seems to fix the issue
