### ISSUE TITLE
Feature request: changing plug IP address in UI or config file

### ISSUE THREAD

**Issue by nickbuhling** [petretiandrea/home-assistant-tapo-p100#497]
It seems currently impossible to reconfigure a plug's IP address, which results in the hassle of removing and adding the integration again. It would be great if there was a way to quickly change the device's IP address. This is useful when changing to another internet provider and you are no longer able to use the previous reserved IP addresses. 

Thanks for your consideration.

**Comment by petretiandrea** [comment]
Absolutely, I'm working on a Mac address resolution using ARP to get ip address dynamically. The best way is to use tapo discovery bu Udp, but a lot of tapo devices not support it
