### ISSUE TITLE
L900 brightness settings being miswritten to scenes.yaml

### ISSUE THREAD

**Issue by mwpmorris** [petretiandrea/home-assistant-tapo-p100#499]
## Version of the integration
2.7.0

## Configuration
Tapo L900-5, fw 1.0.16

```yaml
Add your logs here.
```

## Describe the bug

When setting the brightness for my Tapo LED strips in a scene, the new value does not "stick" and is written incorrectly to the scenes.yaml file. I.e. I set a brightness of 40% (102/255), the value written to scenes.yaml is 54 (21%).

The slider in the HA GUI works correctly, and sets the strip to the correct value (cross-referenced with the Tapo app), but the value is not saved to the scene correctly and recalls as an incorrect value.

## Debug log

```text

Add your logs here.

```

**Comment by ant415** [comment]
I have the same issue for the L900 5m led light strip. To add some more info on issues:

- I was using v2.7.0 when I first noticed the issue. Upgraded to v2.8.0 and the issue is still there
- The brightness setting is "stuck" for scenes. When editing the scene and changing the brightness with the slider, it will change. However, it won't save and instead defaults back to the previous brightness setting next time you enter the scene editor.
- I tried editing the scenes.yaml directly to a low brightness. It did not recongnise the change when I went back into the scene editor and instead was displaying 100% brightness. Therefore, I don't think it is reading from the yaml correctly either.
- After trying to make some changes in the scene editor, I reviewed the scenes.yaml again and the low brightness value I had manually put in there had not changed.

**Comment by mwpmorris** [comment]
With a bit of experimentation, I've found that if you edit the scenes.yaml file with your required brightnesses (as a percentage of 255), the settings do stick. Just make sure to restart Home Assistant after editing the file and make no further changes to the scene in the GUI.

**Comment by ant415** [comment]
Thanks for the temp work-around. Restarting home assistant was what I missed!

Main issue still exists. I found that when entering the scene editor, brightness dimmed to 35/255 (which I had edited in the yaml) but the slider was saying 100%.

**Comment by hwalker928** [comment]
Is this the issue you are experiencing, or is it a separate issue?
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/63236817/8a5c4e37-8f0e-43ec-9916-ea1f3fd67cc9)
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/63236817/8c12d4e1-644e-4190-92c0-a1df4e54a9a9)

**Comment by braymullo** [comment]
+1 for my l920. Let us know if we can help with debugging

**Comment by petretiandrea** [comment]
I need a scene to reproduce it

**Comment by braymullo** [comment]
Sure, here's a scene, the brightness value is 128, should be 255. Manually storing it as 255 and not touching the scene from the GUI gives the correct real world brightness. Touching it in HA resets it back to 128.

The light in question is at the bottom, called "light.studio_right_strip"

`- id: '1687783375727'
  name: Studio Light Warm 100%
  entities:
    light.studio_gold:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      friendly_name: Studio Gold
      supported_features: 0
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 2500
      color_temp: 400
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      state: 'on'
    light.studio_back:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      supported_color_modes:
      - brightness
      - color_temp
      - hs
      - onoff
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 2500
      color_temp: 400
      hs_color:
      - 28.874
      - 72.522
      rgb_color:
      - 255
      - 159
      - 70
      xy_color:
      - 0.546
      - 0.389
      friendly_name: Studio Back
      supported_features: 0
      state: 'on'
    light.studio_right_strip:
      effect_list:
      - bubblingcauldron
      - aurora
      - candycane
      - christmas
      - flicker
      - christmaslight
      - hanukkah
      - hauntedmansion
      - icicle
      - lightning
      - ocean
      - rainbow
      - raindrop
      - spring
      - sunrise
      - sunset
      - valentines
      supported_color_modes:
      - brightness
      - hs
      - onoff
      color_mode: hs
      brightness: 128
      hs_color:
      - 30
      - 94
      rgb_color:
      - 255
      - 135
      - 15
      xy_color:
      - 0.6
      - 0.381
      friendly_name: Studio Right Strip
      supported_features: 4
      state: 'on'
  icon: mdi:globe-light
  metadata: {}

`
