### ISSUE TITLE
Adding this repo as custom repo is not possible (repo info file is missing)

### ISSUE THREAD

**Issue by HerrB92** [petretiandrea/home-assistant-tapo-p100#50]
It is not possible to add this repo as a custom repository in - I guess - the new HACS.

If I understand the dev guidelines correctly, a repository.(json/yaml/yml) file has to be added to the repo root, please see
https://developers.home-assistant.io/docs/add-ons/repository/
for details.

I will try to install it manually, thank you so much for your work!

Regards,
HerrB92

**Comment by petretiandrea** [comment]
> It is not possible to add this repo as a custom repository in - I guess - the new HACS.
> 
> If I understand the dev guidelines correctly, a repository.(json/yaml/yml) file has to be added to the repo root, please see
> https://developers.home-assistant.io/docs/add-ons/repository/
> for details.
> 
> I will try to install it manually, thank you so much for your work!
> 
> Regards,
> HerrB92

Thanks for your report, but add-ons are different from HACS custom integration. To install this integration follow this steps:
- Install HACS store
- Go to HACS > Integration > Press the 3 dots on top corner > Add repository > Paste this repository as URL and select Integration as Category
- After that, still in Hacs Store and press the floating button "explore & add repository" now search for tapo and install it.
- Restart Home Assistant
- Go to Home Assistant Integration and try to search tapo :) will be ;)

If by following these steps you can solve the problem, close this issue, thanks

**Comment by HerrB92** [comment]
Hi petretiandrea,

yes, I  am sorry, I needed some additional time to recognize that HACS is an additional integration and not the same as the Custom Repos in the default system.

Thank you!
