### ISSUE TITLE
Affter update to core-2021.7.0

### ISSUE THREAD

**Issue by mikegikas** [petretiandrea/home-assistant-tapo-p100#51]
After i update the core version from core 2021.5.5 to 2021.7.0 the tapo entity not working.
I got the following errors:

> Logger: homeassistant.setup
Source: setup.py:173
First occurred: 5:55:50 PM (1 occurrences)
Last logged: 5:55:50 PM
Setup failed for tapo: Requirements for tapo not found: ['plugp100==2.1.6'].

And 

> Unable to install package plugp100==2.1.6: ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i305p3fb/pycares/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i305p3fb/pycares/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-y07pk1ty cwd: /tmp/pip-install-i305p3fb/pycares/ Complete output (22 lines): running bdist_wheel running build running build_py creating build creating build/lib.linux-armv7l-3.9 creating build/lib.linux-armv7l-3.9/pycares copying src/pycares/__init__.py -> build/lib.linux-armv7l-3.9/pycares copying src/pycares/utils.py -> build/lib.linux-armv7l-3.9/pycares copying src/pycares/__main__.py -> build/lib.linux-armv7l-3.9/pycares copying src/pycares/_version.py -> build/lib.linux-armv7l-3.9/pycares copying src/pycares/errno.py -> build/lib.linux-armv7l-3.9/pycares running build_ext generating cffi module 'build/temp.linux-armv7l-3.9/_cares.c' creating build/temp.linux-armv7l-3.9 building '_cares' extension creating build/temp.linux-armv7l-3.9/build creating build/temp.linux-armv7l-3.9/build/temp.linux-armv7l-3.9 creating build/temp.linux-armv7l-3.9/deps creating build/temp.linux-armv7l-3.9/deps/c-ares creating build/temp.linux-armv7l-3.9/deps/c-ares/src gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -DHAVE_CONFIG_H=1 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -I/usr/local/include/python3.9 -Ideps/c-ares/src -Ideps/c-ares/src/config_linux -c build/temp.linux-armv7l-3.9/_cares.c -o build/temp.linux-armv7l-3.9/build/temp.linux-armv7l-3.9/_cares.o error: command 'gcc' failed: No such file or directory ---------------------------------------- ERROR: Failed building wheel for pycares ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpb_lwqb0d cwd: /tmp/pip-install-i305p3fb/multidict Complete output (44 lines): ********************** * Accellerated build * ********************** running bdist_wheel running build running build_py creating build creating build/lib.linux-armv7l-3.9 creating build/lib.linux-armv7l-3.9/multidict copying multidict/_multidict_py.py -> build/lib.linux-armv7l-3.9/multidict copying multidict/_multidict_base.py -> build/lib.linux-armv7l-3.9/multidict copying multidict/_compat.py -> build/lib.linux-armv7l-3.9/multidict copying multidict/_abc.py -> build/lib.linux-armv7l-3.9/multidict copying multidict/__init__.py -> build/lib.linux-armv7l-3.9/multidict running egg_info writing multidict.egg-info/PKG-INFO writing dependency_links to multidict.egg-info/dependency_links.txt writing top-level names to multidict.egg-info/top_level.txt reading manifest file 'multidict.egg-info/SOURCES.txt' reading manifest template 'MANIFEST.in' warning: no previously-included files matching '*.pyc' found anywhere in distribution warning: no previously-included files found matching 'multidict/_multidict.html' warning: no previously-included files found matching 'multidict/*.so' warning: no previously-included files found matching 'multidict/*.pyd' warning: no previously-included files found matching 'multidict/*.pyd' no previously-included directories found matching 'docs/_build' adding license file 'LICENSE' writing manifest file 'multidict.egg-info/SOURCES.txt' copying multidict/__init__.pyi -> build/lib.linux-armv7l-3.9/multidict copying multidict/_multidict.c -> build/lib.linux-armv7l-3.9/multidict copying multidict/py.typed -> build/lib.linux-armv7l-3.9/multidict creating build/lib.linux-armv7l-3.9/multidict/_multilib copying multidict/_multilib/defs.h -> build/lib.linux-armv7l-3.9/multidict/_multilib copying multidict/_multilib/dict.h -> build/lib.linux-armv7l-3.9/multidict/_multilib copying multidict/_multilib/istr.h -> build/lib.linux-armv7l-3.9/multidict/_multilib copying multidict/_multilib/iter.h -> build/lib.linux-armv7l-3.9/multidict/_multilib copying multidict/_multilib/pair_list.h -> build/lib.linux-armv7l-3.9/multidict/_multilib copying multidict/_multilib/views.h -> build/lib.linux-armv7l-3.9/multidict/_multilib running build_ext building 'multidict._multidict' extension creating build/temp.linux-armv7l-3.9 creating build/temp.linux-armv7l-3.9/multidict gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.9 -c multidict/_multidict.c -o build/temp.linux-armv7l-3.9/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic error: command 'gcc' failed: No such file or directory ---------------------------------------- ERROR: Failed building wheel for multidict ERROR: Could not build wheels for multidict which use PEP 517 and cannot be installed directly WARNING: You are using pip version 20.2.4; however, version 21.1.3 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.

any idea what happened?

**Comment by swisswebxperts** [comment]
Same problem here + Tapo doesn't appear in HACS

**Comment by justintrann** [comment]
+1 
Cannot use anymore . Reinstalled but still fail

**Comment by petretiandrea** [comment]
thanks guys for report. HA 2021.7 have some breaking changes regarding python. I'm working to fix the break. Probably some dependecies not have proper wheels for python 3.9

**Comment by petretiandrea** [comment]
Please try with the newest version v1.1.3

**Comment by swisswebxperts** [comment]
> Please try with the newest version v1.1.3

Updated integration with HACS and Tapo P100 and L530 devices work.

Thanks for the fast update.
