### ISSUE TITLE
Tapo integrtion failed + password change

### ISSUE THREAD

**Issue by L0bit0** [petretiandrea/home-assistant-tapo-p100#516]
Hi

Most of my Tapo integration was failing (I have 4 pugs and 1 bulb), I changed my password on Tapo application (not sure why had issues to login into the Tapo application, so I had to rest)

After this all are failing.

I tried to find where passwords was stored, and i just found this on custom_components > tapo > string.json:
```
{
  "title": "tapo",
  "config": {
    "step": {
      "user": {
        "data": {
          "host": "[%key:common::config_flow::data::host%]",
          "username": "[%key:common::config_flow::data::username%]",
          "password": "[%key:common::config_flow::data::password%]"
        }
      }
    },
```

But not able to find where file is referring to.

I additionally got these errors on the home assistant logs:
  
```
This error originated from a custom integration.
  
  Logger: plugp100.api.tapo_client
  Source: custom_components/tapo/setup_helpers.py:97
  Integration: TP-Link Tapo (documentation, issues)
  First occurred: 2:15:48 PM (550 occurrences)
  Last logged: 8:19:38 PM
  
  Default protocol not working, fallback to KLAP ;)
```

```

Logger: homeassistant.config_entries
Source: config_entries.py:429
First occurred: 2:15:49 PM (6 occurrences)
Last logged: 2:15:52 PM

Config entry 'Enchufe_Bano' for tapo integration not ready yet: 'NoneType' object has no attribute 'handshake_complete'; Retrying in background
Config entry 'Bombilla_Salon' for tapo integration not ready yet: Cannot connect to host 192.168.1.189:80 ssl:default [Connect call failed ('192.168.1.189', 80)]; Retrying in background
Config entry 'TermometroBano' for switchbot integration not ready yet: Could not find Switchbot hygrometer with address C4:FC:2F:73:F6:EF; Retrying in background
Config entry 'Enchufe_Cocina' for tapo integration not ready yet: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials; Retrying in background
Config entry 'Enchufe_Salon_B' for tapo integration not ready yet: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials; Retrying in background

```

```

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:124
First occurred: 2:15:48 PM (1 occurrences)
Last logged: 2:15:48 PM

Detected integration that closes the Home Assistant aiohttp session. Please report issue to the custom integration author for tapo using this method at custom_components/tapo/setup_helpers.py, line 97: api = await TapoClient.connect(credentials, ip_address, session)

```

I would like to first being able to change the password, then I will keep investigating initial issue (if still happens)

Can anyone help me?

Thanks in advance

**Comment by L0bit0** [comment]
Hi

Some updates, I tried to add again one of my plugs, and I can not as it is already added: Device is already configured.
I also exported the log on debug mode in case it helps.

I assume I can always remove the devices and add again (as a workarround), but not sure if this involves i have to recreate all automations and cards I have for this.

Thanks

**Comment by L0bit0** [comment]
Hi

Can anyone help me to at least locate were Tapo integration password is stored?

Thanks in advance

**Comment by dgquejada** [comment]
\config\configuration.yaml

**Comment by L0bit0** [comment]
@dgquejada thanks, but are not there. I checked from the beginning and did not find. Not even on any of the “include” files. Do you have an example string?

thanks!

**Comment by babblerz** [comment]
Should be at /config/.storage/core.config_entries

**Comment by L0bit0** [comment]
@babblerz thanks, it was there and are working now. Wired thing is that couple of them works first time, but other ones take some restarts.

thanks again.
