### ISSUE TITLE
LED strip L900 failed to connect with error "INVALID_CREDENTIAL"

### ISSUE THREAD

**Issue by simonefiorini01** [petretiandrea/home-assistant-tapo-p100#517]
Hello,

I return to open a case for the "Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials" error.

Here some information:
- Version of the integration: 2.8.2
- Tapo LED strip L900 version: 1.0.16 Build 220902 Rel.151030 (last version available)

Here is the debug log:
[home-assistant_tapo_2023-09-12T22-35-05.678Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/12591445/home-assistant_tapo_2023-09-12T22-35-05.678Z.log)

**Comment by simonefiorini01** [comment]
Do you have any update for the issue?
Thank you!

**Comment by petretiandrea** [comment]
Are you using 2FA on Tapo App? If yes, you must disable it

**Comment by simonefiorini01** [comment]
No, 2FA is disabled.
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/43265928/6af52cd2-a979-4ee8-95cc-6513f8db8d71)
