### ISSUE TITLE
Add Support For Tapo L535 Bulb

### ISSUE THREAD

**Issue by shortlurker** [petretiandrea/home-assistant-tapo-p100#519]
**Is your feature request related to a problem? Please describe.**
Add support for Tapo L535 bulb

**Describe the solution you'd like**
Added the following line under SUPPORTED_DEVICE_AS_LIGHT in const.py and was able to detect and control the bulb (on/off, brightness, temperature, color) with release 2.8.2.

`"l535": [ColorMode.ONOFF, ColorMode.BRIGHTNESS, ColorMode.COLOR_TEMP, ColorMode.HS],`

**Device Info**
If needed, script info dump using plugp100 2.5.1. I couldn't get the info dump script working with latest version.

```
{'device_id': '8023196C648AF90F6B8FE5FCA45785CB217377F1', 
'fw_ver': '1.0.8 Build 230810 Rel.140202', 
'hw_ver': '3.0', 
'type': 'SMART.TAPOBULB', 
'model': 'L535', 
'mac': xx-xx-xx-xx-xx-xx, 
'hw_id': '75A579FB67A2FFBEB6DB027CCBE46D1D', 
'fw_id': '00000000000000000000000000000000', 
'oem_id': 'F311A36CB0C8A2958AE0753DFA7C9746', 
'color_temp_range': [2500, 6500], 
'overheated': False, 
'ip': '192.168.1.80', 
'time_diff': -480, 
'ssid': xxxxxx, 
'rssi': -55, 
'signal_level': 2, 
'latitude': xxxxxx, 
'longitude': xxxxxx, 
'lang': 'en_US', 
'avatar': 'bulb', 
'region': 'America/Los_Angeles', 
'specs': '', 
'nickname': 'U21hcnQgQnVsYiBMNTM1RQ==', 
'has_set_location_info': True, 
'device_on': True, 
'brightness': 100, 
'hue': 0, 
'saturation': 0, 
'color_temp': 4405, 
'dynamic_light_effect_enable': False, 
'default_states': {'re_power_type': 'last_states', 'type': 'last_states', 'state': {'brightness': 100, 'hue': 0, 'saturation': 0, 'color_temp': 4405}}}

```
![l535](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/33041660/ac1e4ef0-18bd-497d-9023-70207cbfe325)
![tapo_home_assisnt](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/33041660/1ff2ec35-88a4-4ff2-8c75-2268a1ed9d87)

**Comment by petretiandrea** [comment]
2.9.0 now supports L535
