### ISSUE TITLE
Overheat Sensors all changed

### ISSUE THREAD

**Issue by jamesonuk** [petretiandrea/home-assistant-tapo-p100#529]
Just upgraded to 2.9.0 and noticed that all devices (I only have four...) seem to have changed their overheat sensors.
Largely cosmetic but I do have some old entities to delete now.
The old overheat sensors (with a fire icon) have been replaced with an _2 sensor with a thermometer icon
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/1040621/99063e73-bebf-4c37-8b4d-7bc158cef6f8)
this is across some lights and smart plugs

**Comment by petretiandrea** [comment]
Upgrade to 2.9.1 which fixes overheat icon. Remove both entity and reload integration
