### ISSUE TITLE
Am i doing something wrong?

### ISSUE THREAD

**Issue by voxituk** [petretiandrea/home-assistant-tapo-p100#532]
Hi All

Thanks for your time reading this, I’ll try and keep it concise.

I’m running the latest version of home assistant and the Tapo integration and the devices themselves are up to date:

**Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest**

After adding my P110 plugs (11 of them) and L630 bulbs (5 of them) various devices become unavailable anywhere from an hour to a day later. Sometimes a reload brings them back but now I have a few devices that after being removed, due to not reloading, now won’t re-add and I get Invalid Credential errors.  

_Config entry 'S4 - Lights' for tapo integration not ready yet: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials; Retrying in background_

**Tapo P110 - Hardware Version 1.2
Firmware: 1.2.3 Build 230425 Re;. 142542**

_Error fetching tapo data: Error communication with API: Cannot connect to host 192.168.1.254:80 ssl:default [Connect call failed ('192.168.1.254', 80)]
Error fetching tapo data: Error communication with API: Cannot connect to host 192.168.1.147:80 ssl:default [Connect call failed ('192.168.1.147', 80)]
Error fetching tapo data: Error communication with API: Cannot connect to host 192.168.1.93:80 ssl:default [Connect call failed ('192.168.1.93', 80)]_

I have removed all my devices, factory reset them and reconnected them with a brand new account (all lowercase) in the Tapo app.

All devices are connected to a Ubiquiti Dream Machine on 2.4Ghz network and all devices have static IP addresses with MAC tracking unticked in the device in the Tapo Integration to avoid any potential network issues. Each device sends the http 200 OK so i know its connected and working as all devices never have issues in the Tapo App.

What am I missing??

thank you so much in advance.

Many Thanks
Scott

**Comment by idan** [comment]
The readme says to check #122 if you're getting "invalid credentials"

**Comment by idan** [comment]
(no idea if that will help, I am also struggling to figure out why stuff isn't working)

**Comment by petretiandrea** [comment]
Have you 2FA enabled?

**Comment by voxituk** [comment]
Thanks for the replies.

I setup a new account all in lowercase to be sure it wasn't the login info I also do not have 2FA enabled.

Since posting this all my devices bar 3 are now showing setup failed INVALID_CREDENTIAL error. They are all still working in TAPO app and I have purchased and added a new one with the same login info and it accepts it.

"tapo integration not ready yet: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials; Retrying in background"

So very frustrating but I still appreciate the skill, i just don't know what is going.

**Comment by voxituk** [comment]
Removed the integration, restarted, reinstalled integration with all latest stable versions etc and now cannot re-add anything :-(

This error originated from a custom integration.

Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:118 
Integration: TP-Link Tapo (documentation, issues) 
First occurred: 13:45:27 (2 occurrences) 
Last logged: 13:45:45

Tapo exception -1501

Login username and password are all lower case and 100% correct.

Many Thanks
Scott

**Comment by petretiandrea** [comment]
-1501 is a generic error login, not related to invalid credentials. Have you 2FA enabled?
