### ISSUE TITLE
Tapo hacs integration

### ISSUE THREAD

**Issue by ArifMontoya** [petretiandrea/home-assistant-tapo-p100#537]
I've just installed the template for Tapo integration via hacks on my Home Assistant. Everything is up-to-date. It seems to install properly asks for reboot, but when I reboot I cannot see the integration  anywhere? 

- [ ] Not sure if what im doing anything wrong?

**Comment by Goatieman1** [comment]
Hey ArifMontoya, Sounds like you may need to got to Settings -> Devices & Services and then click on the add integration button, then start typing Tapo and it should appear. Hope that works for you.

**Comment by ArifMontoya** [comment]
Hi thereThanks for that ive sorted it I’m a newbie and it probably shows . Thanks for your promt replyArif Sent from my iPhoneOn 26 Sep 2023, at 6:25 pm, Goatieman ***@***.***> wrote:﻿
Hey ArifMontoya, Sounds like you may need to got to Settings -> Devices & Services and then click on the add integration button, then start typing Tapo and it should appear. Hope that works for you.
