### ISSUE TITLE
[New Device Support Request] T300 leak sensor

### ISSUE THREAD

**Issue by compton2012** [petretiandrea/home-assistant-tapo-p100#541]
When time allows please could we added T300 leak sensors to the hub devices code please.

**Comment by petretiandrea** [comment]
I need you runs https://github.com/petretiandrea/home-assistant-tapo-p100/issues/542#issuecomment-1751677377

**Comment by compton2012** [comment]
Hi,

Please see output of run (anonymised), let me know if you need more.

Thanks

`Success(ChildDeviceList(child_device_list=[{'parent_device_id': '...', 'hw_ver': '1.0', 'fw_ver': '1.6.0 Build 230512 Rel.144517', 'device_id': '...', 'mac': '...', 'type': 'SMART.TAPOSENSOR', 'model': 'T300', 'hw_id': '...', 'oem_id': '...', 'specs': 'EU', 'category': 'subg.trigger.water-leak-sensor', 'bind_count': 1, 'status_follow_edge': False, 'status': 'online', 'lastOnboardingTimestamp': 1696606000, 'rssi': -84, 'signal_level': 1, 'jamming_rssi': -117, 'jamming_signal_level': 1, 'in_alarm': False, 'water_leak_status': 'normal', 'at_low_battery': False, 'nickname': '...', 'avatar': 'sensor_t300', 'report_interval': 16, 'region': 'Europe/London'}, {'parent_device_id': '...', 'hw_ver': '1.0', 'fw_ver': '1.6.0 Build 230512 Rel.144517', 'device_id': '...', 'mac': '...', 'type': 'SMART.TAPOSENSOR', 'model': 'T300', 'hw_id': '...', 'oem_id': '...', 'specs': 'EU', 'category': 'subg.trigger.water-leak-sensor', 'bind_count': 1, 'status_follow_edge': False, 'status': 'online', 'lastOnboardingTimestamp': 1696167041, 'rssi': -82, 'signal_level': 1, 'jamming_rssi': -115, 'jamming_signal_level': 1, 'in_alarm': False, 'water_leak_status': 'normal', 'at_low_battery': False, 'nickname': '...=', 'avatar': 'sensor_t300', 'report_interval': 16, 'region': 'Europe/London'}], start_index=0, sum=2))`

`Success({'device_id': '...', 'fw_ver': '1.3.9 Build 230522 Rel.103415', 'hw_ver': '1.0', 'type': 'SMART.TAPOHUB', 'model': 'H100', 'mac': '...', 'hw_id': '...', 'fw_id': '00000000000000000000000000000000', 'oem_id': '...', 'overheated': False, 'ip': '...', 'time_diff': 0, 'ssid': '...', 'rssi': -53, 'signal_level': 2, 'in_alarm': False, 'in_alarm_source': '', 'latitude': 0, 'longitude': 0, 'lang': 'en_US', 'avatar': 'hub', 'region': 'Europe/London', 'specs': 'UK', 'nickname': '...', 'has_set_location_info': True})`

**Comment by JaidevDPendse** [comment]
The sensor shows in Home Assistant but it does not have any sensor values associated with it, here is the screenshot for the same. 
![t300](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/159750956/50e5caf0-23b4-4edc-9e90-77dd643eaa8d)

**Comment by petretiandrea** [comment]
> The sensor shows in Home Assistant but it does not have any sensor values associated with it, here is the screenshot for the same. Please help ![t300](https://private-user-images.githubusercontent.com/159750956/303976359-50e5caf0-23b4-4edc-9e90-77dd643eaa8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzAwMDAsIm5iZiI6MTcwODc2OTcwMCwicGF0aCI6Ii8xNTk3NTA5NTYvMzAzOTc2MzU5LTUwZTVjYWYwLTIzYjQtNGVkYy05ZTkwLTc3ZGQ2NDNlYWE4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxMDE1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjRlM2IzOTNmZDNiMDZjZTMyZTJhNzFkOWEwZDRhZTQ1M2Q0ZWIxZDNiNDg4OGRkM2Y4YWNhN2FmNzIzMzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W0e27Uvu66O_z03X5Lco_wOSB7olESStLvbIsEMerZA)

Try to refresh page?
