### ISSUE TITLE
S220 Device support

### ISSUE THREAD

**Issue by Mandrake1967** [petretiandrea/home-assistant-tapo-p100#542]
Please add full support for the Tapo S200 switch series so that entities can be revealed and utilised within Home Assistant

**Comment by wavemop** [comment]
Same here -  the S210 has no listed entities in the Integration.

**Comment by miumer** [comment]
This would be great!

**Comment by petretiandrea** [comment]
As reported [here](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/354#issuecomment-1706967148) buttons in general doesn't allow getting a "live click event". This is especially true for S200B button which doesn't report "is_on", but if S220 support "is_on" and report it, I will add suport for this

**Comment by T8DAGR8** [comment]
Same here the S220 switch has no entities.

**Comment by wavemop** [comment]
> "As reported [here](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/354#issuecomment-1706967148) ..."

Wow, thanks man - that's explaining so much. Couldn't believe it's truly a full non-local device in the moment of purchase.
Damn wrong hardware ... AGAIN!

**Comment by Mandrake1967** [comment]
The Tapo s200b is simply a low power button and completely different. I can understand that this will simply act as a trigger and no more and is not stateful. The hub cannot know a state since its just a 'pulse' of 'on-off'.

The s220 is a stateful power switch, which certainly should support entities in home assistant via the hub since it has defined on and off states and also battery level.

**Comment by petretiandrea** [comment]
If s220 is stateful, I can integrate It

**Comment by wavemop** [comment]
> If s220 is stateful, I can integrate It

s210 is also stateful (has single switch instead of twin switch S220)

**Comment by petretiandrea** [comment]
I need your support to integrate them. You must run a python snippet and report here the state of your connected devices to hub

Install `pip install plugp100==3.11.0` and then use the following [script ](https://github.com/petretiandrea/plugp100#code-example) but after `initialize` use these lines
```
# - hub example
hub = HubDevice(client)
print(await hub.get_children())
print(await hub.get_state_as_json())
```

**Comment by miumer** [comment]
Im only posting the s220 part of the response and hidding all the IDs and region stuff here, but getting a response something like this. Is this response enough:

{'parent_device_id': '...', 'hw_ver': '1.0', 'fw_ver': '1.7.0 Build 220620 Rel.170201', 'device_id': '...', 'original_device_id': '...', 'mac': '...', 'type': 'SMART.TAPOSWITCH', 'model': 'S220', 'hw_id': '...', 'oem_id': '...', 'specs': 'EU', 'category': 'subg.plugswitch.switch', 'bind_count': 2, 'slot_number': 2, 'position': 1, 'status_follow_edge': False, 'status': 'online', 'is_low': False, 'lastOnboardingTimestamp': 1687434540, 'rssi': -70, 'signal_level': 2, 'jamming_rssi': -118, 'jamming_signal_level': 1, 'nickname': '...', 'avatar': 'switch', 'device_on': False, 'led_off': 0, 'region': '...', 'latitude':..., 'longitude': ..., 'has_set_location_info': True}

**Comment by petretiandrea** [comment]
> Im only posting the s220 part of the response and hidding all the IDs and region stuff here, but getting a response something like this. Is this response enough:
> 
> {'parent_device_id': '...', 'hw_ver': '1.0', 'fw_ver': '1.7.0 Build 220620 Rel.170201', 'device_id': '...', 'original_device_id': '...', 'mac': '...', 'type': 'SMART.TAPOSWITCH', 'model': 'S220', 'hw_id': '...', 'oem_id': '...', 'specs': 'EU', 'category': 'subg.plugswitch.switch', 'bind_count': 2, 'slot_number': 2, 'position': 1, 'status_follow_edge': False, 'status': 'online', 'is_low': False, 'lastOnboardingTimestamp': 1687434540, 'rssi': -70, 'signal_level': 2, 'jamming_rssi': -118, 'jamming_signal_level': 1, 'nickname': '...', 'avatar': 'switch', 'device_on': False, 'led_off': 0, 'region': '...', 'latitude':..., 'longitude': ..., 'has_set_location_info': True}

Thanks, I can integrate it

**Comment by wavemop** [comment]
You also need that script on the s210 or can you take data from s220 log ?

_Thanks for all your efforts!_

**Comment by petretiandrea** [comment]
> You also need that script on the s210 or can you take data from s220 log ?
> 
> _Thanks for all your efforts!_

Having both is better ;)

**Comment by miumer** [comment]
THe devices seem to have no controls related to them. Does it work somehow differently than a plug? Can't see any info about it in the UI. Only that it exists

**Comment by Mandrake1967** [comment]
Agree, that this is not closed.
S220 is not showing any entities at all still
Also I note that the H100 hub has now also lost the siren function.

**Comment by T8DAGR8** [comment]
Agreed still no entities for a s220 switch

**Comment by DimiTerz** [comment]
Only S210 switches are working for me also. And I noticed another limitation as explained in issue #570

**Comment by Mandrake1967** [comment]
Working , much appreciated!

**Comment by T8DAGR8** [comment]
I've found it now.
And it works with all entities and the battery level sensors.
Thanks

**Comment by wavemop** [comment]
perfectly working on s210, much appreciated!🎉

**Comment by T8DAGR8** [comment]
Also the siren feature on the h100 hub is back.

**Comment by ashwinikalantri** [comment]
These devices should be added to the [supported devices list](https://github.com/petretiandrea/home-assistant-tapo-p100/blob/main/README.md#supported-devices).
