### ISSUE TITLE
Support for S505 and S505D - Tapo Matter switches

### ISSUE THREAD

**Issue by petretiandrea** [petretiandrea/home-assistant-tapo-p100#545]
### Discussed in https://github.com/petretiandrea/home-assistant-tapo-p100/discussions/504

<div type='discussions-op-text'>

<sup>Originally posted by **mehrafamily** September  2, 2023</sup>
Hi there,

I'm trying to add the new Tapo matter switches, but the integration fails to load. It seems the devices are not supported. I saw that S500 and S500D support was recently added, so wondering if this is easy to extend to this device too.

I've been trying to add the switches directly as a matter device, but that doesn't work either.

Thanks much!

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 42, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 40, in async_setup_entry
    return await device.initialize_device(hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/tapo_device.py", line 28, in initialize_device
    ).get_or_raise()
      ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/functional/tri.py", line 159, in get_or_raise
    raise self.value
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.1.121 not supported!
```</div>

**Comment by mehrafamily** [comment]
One thing I've noticed is that whenever HA restarts I need to go back in and reload each of the integrations for it to work. I don't know if its due to another bug in the tapo integration, or something to do with the S505 and S505D

**Comment by jonahwh** [comment]
I noticed this was marked as completed, but I don't see any related changes to the codebase. Is this still coming?

**Comment by petretiandrea** [comment]
> I noticed this was marked as completed, but I don't see any related changes to the codebase. Is this still coming?

Is in 2.10.0

**Comment by jonahwh** [comment]
I'm running 2.10.1 and I'm still not able to add my S505 devices. Also see #586 where another user is still experiencing this in 2.10.1
