### ISSUE TITLE
Support for Tapo S200D!

### ISSUE THREAD

**Issue by jacobeliason** [petretiandrea/home-assistant-tapo-p100#549]
Would love to use the Tapo S200D which is readily available in NZ for my HA. Much easier to get these than to wait a month for Aliexpress ones! Ideally the tap function, but also the turn if available. Easy to control volume of my sonos from this, plus turn my lights on and off using the button.

**Comment by petretiandrea** [comment]
Please refer to #556

**Comment by cburkins** [comment]
Also excited about the possibilities of the Tapo S200D button in Home Assistant.   Was hoping to be able to access the rotating knob to change the color of a light bulb or change the brightness of another brand of light.
