### ISSUE TITLE
2023.10.0 error aiohttp

### ISSUE THREAD

**Issue by sagitt** [petretiandrea/home-assistant-tapo-p100#554]
I found this warning in my logs.
I think need a fix.

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 22:58:12 (1 occurrences)
Last logged: 22:58:12

Detected integration that closes the Home Assistant aiohttp session. Please report issue to the custom integration author for tapo using this method at custom_components/tapo/setup_helpers.py, line 97: api = await TapoClient.connect(credentials, ip_address, session)
```

## Version of the integration

2.9.1

**Comment by petretiandrea** [comment]
> I found this warning in my logs. I think need a fix.
> 
> ```
> Logger: homeassistant.helpers.frame
> Source: helpers/frame.py:103
> First occurred: 22:58:12 (1 occurrences)
> Last logged: 22:58:12
> 
> Detected integration that closes the Home Assistant aiohttp session. Please report issue to the custom integration author for tapo using this method at custom_components/tapo/setup_helpers.py, line 97: api = await TapoClient.connect(credentials, ip_address, session)
> ```
> 
> ## Version of the integration
> 2.9.1

I'm going to delve into the problem, but is related to automatically discover of right communication protocol of tapo device
