### ISSUE TITLE
Support for Away mode Entity for Tapo P110

### ISSUE THREAD

**Issue by joaosobreira** [petretiandrea/home-assistant-tapo-p100#555]
**Is your feature request related to a problem? Please describe.**
I just integrated my Tapo P110's and notice there's no way to setup away mode like you do in the app.

**Describe the solution you'd like**
I would like to be able to configure Away Mode from HA like I do with the app

**Describe alternatives you've considered**
It's weird to think of implementing it manually when the option already exists in the app.

**Comment by frank777777** [comment]
On HA - automation >projects . There are couple of projects already created for that. ;-)

**Comment by joaosobreira** [comment]
> On HA - automation >projects . There are couple of projects already created for that. ;-)

Thanks for the response, but I can't find it on HA. Could you help me?
