### ISSUE TITLE
Tapo P100 Unresponsive Since Update

### ISSUE THREAD

**Issue by JS0N-B0urne** [petretiandrea/home-assistant-tapo-p100#557]
Hi all

Looks like there was a big app update recently. I've got 4 tapo P100s with slighlty different firmwares:

3 x not working are - Firmware: 1.1.5 Build 230324 Rel.143956 (hardware 2.0)

1 x working is: Firmware: 1.2.3 Build 230425 Rel.142542 (Hardware 1.0).

I had to open the app after it updated to be able to use the lights in there again.

**Comment by ant415** [comment]
Same issue for me

**Comment by beanonymous** [comment]
Getting the same results… native Tapo app still works. Just not in HA

**Comment by karpiq24** [comment]
I'm having same issue with  1.1.5 Build 230324 Rel.143956;
1.2.1 Build 230804 Rel.190922  works fine.

**Comment by petretiandrea** [comment]
Try to reload config entry. 1003 is due to KLAP protocol upgrade

**Comment by simphide** [comment]
For me the Firmware: 1.2.3 Build 230425 Rel.142542 is not working on one device (Tapo P110). Current power consumptions works fine, but turning on and off is not working...

**Comment by karpiq24** [comment]
> Try to reload config entry. 1003 is due to KLAP protocol upgrade

This fixed the issue for me.

**Comment by pedroguima** [comment]
Hey, same issue here:

`Logger: custom_components.tapo.common_setup
Source: helpers/update_coordinator.py:258
Integration: Tapo Controller ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/))
First occurred: 12:28:17 (18 occurrences)
Last logged: 12:35:11

Failed to setup Error tapo exception: Returned unknown error_code: 1003`

Tried reloading config and rebooting but no luck. Any ideas?

**Comment by canuckjacq** [comment]
Reloading not working for me either

**Comment by dan-stanton** [comment]
Same issue, reloading not working either

**Comment by beanonymous** [comment]
I got it working for me.
Make sure you update the TAPO “integration” in HACS and then restart home assistant.

Hopefully this solves it for a lot of people.

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/2655523/7e682b8b-77a7-4b17-ad25-c73a2f1e4098)

**Comment by pedroguima** [comment]
thanks @beanonymous, that fixed the issue!
