### ISSUE TITLE
Unable to connect to P110 devices

### ISSUE THREAD

**Issue by ImNotAlexxGH** [petretiandrea/home-assistant-tapo-p100#558]
## Version of the integration
integration installation: v2.9.1
HACS installation: v1.33.0
HA installation: v2023.10.1

## The Issue
I cannot seem to connect my P110 devices that were previously working fine. 
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/53872579/9cd83599-7e14-4ea5-97d3-2d11caf196e0)

## Configuration
Trying to connect three P110 devices. lowercase email, no 2fa, static IPs defined. My setup was previously working, I recently looked and noticed all three devices were unresponsive in HA. Today, I looked at fixing this, so I updated HA. HACS and the tapo integration. I tried readding the P110 devices after removing them, but get an error each time and cannot add them.

(I have replaced my actual devices IP with 'MY_IP'):
```yaml
Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:117
Integration: tapo (documentation, issues)
First occurred: 11:36:51 AM (2 occurrences)
Last logged: 11:42:53 AM

Failed to setup cannot connect
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('MY_IP', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 210, in _try_setup_api
    return await TapoClient.connect(credential, user_input[CONF_HOST], session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 43, in connect
    response = await api.execute_raw_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 84, in execute_raw_request
    return (await self._protocol.send_request(request)).map(lambda x: x.result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 42, in send_request
    response = await self._send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 62, in _send_request
    await self._login_with_version(self._credential)
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 81, in _login_with_version
    session_or_error = await self._passthrough.handshake(self._url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/securepassthrough_transport.py", line 70, in handshake
    response = await self._http.async_make_post(url, json=request_body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 18, in async_make_post
    async with self.session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host MY_IP:80 ssl:default [Connect call failed ('MY_IP', 80)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 117, in async_step_user
    tapo_client = await self._try_setup_api(user_input)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 214, in _try_setup_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect
```

**Comment by Roger-The-Paradox** [comment]
I just opened my Tapo app and there was an announcement that it has been updated to 'Version 3'.
I can now see my TP-Link Kasa devices (I have a bunch of KP105's) in the app as well (Same user account)

**Comment by petretiandrea** [comment]
> I just opened my Tapo app and there was an announcement that it has been updated to 'Version 3'. I can now see my TP-Link Kasa devices (I have a bunch of KP105's) in the app as well (Same user account)

Could you explain better what happening?

**Comment by Ashtlind** [comment]
Facing the same issue here, previously had 4x Tapo P100 up and connected, we believe this was after the recent firmware update of the plugs automatically (lesson learned disabling auto update..). The plugs have updated to v1.2.1

Control of the devices still works in the tapo app but no longer locally.

**Comment by ImNotAlexxGH** [comment]
So, I managed to get round this issue by removing my plugs from the app and then readding them. I then did the usual tapo - home assistant setup and it worked, theyve been up for about a day now without issues. :)

**Comment by frank777777** [comment]
ready to do the today home assistant core update, restart and see all vanishing?

**Comment by Roger-The-Paradox** [comment]
> > I just opened my Tapo app and there was an announcement that it has been updated to 'Version 3'. I can now see my TP-Link Kasa devices (I have a bunch of KP105's) in the app as well (Same user account)
> 
> Could you explain better what happening?

Sorry. Just noticed this.

It was just an obsevation.  Looks like TP-Link is merging the Tapo/Kasa devices into the Tapo app.
Probably not relevant, but it seems to be a change that s happening behind the scenes.

**Comment by d-zalewski** [comment]
+1

**Comment by gazzaman22** [comment]
same with me

**Comment by petretiandrea** [comment]
Can you reach the device from homeassistant by using `ping`?
This `OSError: [Errno 113] Connect call failed ('MY_IP', 80)` means "No route to host"

**Comment by gazzaman22** [comment]
> Can you reach the device from homeassistant by using `ping`? This `OSError: [Errno 113] Connect call failed ('MY_IP', 80)` means "No route to host"

Yes I can ping

**Comment by petretiandrea** [comment]
Have you try with new 2.10.1?

**Comment by gazzaman22** [comment]
> Have you try with new 2.10.1?

Yes I have

**Comment by D-clik43** [comment]
Hello. 
sale problem with version 2.11 : my p110 Fail to configure.

**Comment by mirtes99** [comment]
I have 2.11, but it is still not working; 'Failed to connect'

**Comment by mirtes99** [comment]
> Can you reach the device from homeassistant by using `ping`? This `OSError: [Errno 113] Connect call failed ('MY_IP', 80)` means "No route to host"

no, I can't

**Comment by junyan-rippling** [comment]
same problem here. I can ping the device in home assistant OS

**Comment by D-clik43** [comment]
Hello. 

No I can’t ping

**Comment by madmalkav** [comment]
Same problem, device can be pinged from HAOS

**Comment by mirtes99** [comment]
is there someone that could tell us why we cannot ping the device? is it something misconfigured in HA?

**Comment by petretiandrea** [comment]
The device is in a different network?

**Comment by jajera** [comment]
The easiest way is HAOS is on the same subnet with your TAPO devices. It can be on a different network but you have to ensure that HAOS can reach them.

**Comment by RobFisher** [comment]
This issue might be closed but it is not resolved. I have multiple P110s on version 1.3.0 Build 230905 Rel. 152200 and some of them work perfectly and others just say "failed to connect" when I try to add them with their IP addresses in the UI. I can ping them from HA (on the console; typing login; then ping <ip address>). I tried removing them from the tapo app and re-adding but that did not work.

**Comment by FrankC-BEL** [comment]
Unfortunately here too.....

Firmware 1.4.0 Build 250901 Rel. 175625

Device(s) are auto detected, but when trying to 'connect' login fails with 'Failed to connect'.  No capitals in email or whatsoever :-(

**Comment by borosf** [comment]
Just use the official integration, TP-Link Tapo. Third-Party compatibility must be enabled in-app (you don't need to be near the outlet). And it just works.

**Comment by Marius-Ar** [comment]
> Just use the official integration, TP-Link Tapo. Third-Party compatibility must be enabled in-app (you don't need to be near the outlet). And it just works.

This issue remains
Which integration are you using exactly please? Is it the "Tapo" one under "TP-Link"

Edit: Enabling "Third party compatibility" from Me > Third-Party Services fix the "Failed to connect" error

**Comment by feuggin** [comment]
I was struggling trying to access trying different python libraries but afterall Enabling "Third party compatibility" from Me > Third-Party Services solve it
