### ISSUE TITLE
P100 missing switch entity but has overheat and signal level entity

### ISSUE THREAD

**Issue by jbsmith96** [petretiandrea/home-assistant-tapo-p100#561]
## Version of the integration
2.9.0

## Configuration
Tapo P100 (HW 2.0)
1.2.1 Build 230804 Rel 190922

## Describe the bug

P100 switch was working reliably for many months until it automatically updated firmware versions. It then stopped responding in HASS so I removed and tried to re-add, getting the authentication issue #122 

I deleted the Tapo integration and reinstall 2.9.0 fresh. I was then able to add the P100 successfully, but it is missing the actual switch entity. It shows the overhead and signal level entity although I'm not sure if they are responding properly.
<img width="670" alt="Screenshot 2023-10-13 at 4 25 39 pm" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/38416464/85be06cd-cb92-4702-b67d-629238530774">

**Comment by jbsmith96** [comment]
Well, after waiting 5 mins the switch entity automatically appeared. So patience is just needed!

**Comment by Aidan-Chey** [comment]
For those finding the issue and waiting isn't correctign the issue, like myself. Another solution I found to work is to attempt to add the device to a new script as a toggle action from the device's page.
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/6834594/1edda6c6-d317-4c57-889b-6099ed919b8a)
Pressing the plus in the scripts panel prompts for a type of action (toggle). It adds the action as `toggle unkown entity`. Running the script did toggle the plug and looking at the device again, the integration had added the switch control.
