### ISSUE TITLE
Access Tapo L510 brightness programmatically

### ISSUE THREAD

**Issue by gattilorenz** [petretiandrea/home-assistant-tapo-p100#563]
Ciao, I have a L510 lightbulb and in the home assistant scripts I can only select "increase brightness" or "decrease brightness", both of which change it in 10% increments. 

I would like to have a way of finding the current brightness and updating it precisely, as you can do via the interface, but programmatically from a script instead. Is that already possible and I'm just not finding it, or is it a new feature?

Grazie!

**Comment by gattilorenz** [comment]
Figured it out, I can do it if I call a service

**Comment by gattilorenz** [comment]
Sure, the solution is actually quite simple but I'm an homeassistant n00b and it took a while to figure it out :)
If you want to use the visual automation editor, don't select your tapo light as a service: add action "call service", and select "Light: Turn on" as the service.
From there you can select a specific target (your Tapo lightbulb), and once you do that you can specify either a specific brightness, or a brightness increase in percentage, etc.
Here is the documentation for the service: https://www.home-assistant.io/integrations/light

In YAML, this (increasing current brightness by 1%) looks like:
```
service: light. turn_on
data:
  brightness_step_pct:1
target:
  device id: <your device ID>
```

Is this clear enough?

**Comment by AxeMaster99** [comment]
Yes, perfect. Thank you so much!
