### ISSUE TITLE
Only 10 Devices from Hub working simultaneously

### ISSUE THREAD

**Issue by DimiTerz** [petretiandrea/home-assistant-tapo-p100#570]
After the integration of S210 Switches I noticed that only 10 devices work at a time. I digged a bit around and I think the issue is that `hub.get_children()` only returns the first 10 jsons responses despide giving the correct total of devices. 

Could you please have a look at this?

**Comment by petretiandrea** [comment]
Bug confirmed, I'm working on a fix

**Comment by DimiTerz** [comment]
I think it was working fine before the update in the Tapo app but I am not sure. I suspect some sort of pagination in the request since having exactly 10 is somewhat suspicious. 
I hope this helps.

**Comment by DimiTerz** [comment]
I tested it just now. It works better but still not perfect. Now all but one devices are listed.

**Comment by Saftlad** [comment]
Unfortunately, I am also now coming across this issue.  I thought it was something I was doing wrong
