### ISSUE TITLE
Add calibration factor

### ISSUE THREAD

**Issue by fl4p** [petretiandrea/home-assistant-tapo-p100#585]
Hi,
it would be handy if the integration implements current and voltage single point calibration. This is very straight forward to implement, just ask the user for 2 floats, one current factor and one voltage factor. Then multiply the readings with it.
(The hard part is actually finding these 2 values with a reference meter)

What do you think?

**Comment by petretiandrea** [comment]
You can use home assistant helpers component to derive a new measure from the one provided by sensor
