### ISSUE TITLE
Multiple instance of integration messing with devices

### ISSUE THREAD

**Issue by jokok0** [petretiandrea/home-assistant-tapo-p100#588]
Since 4 days, I encounter multiple problems with my TAPO devices with Home Assistant
Only one service is shown on Integration pannel, but all my devices are not listes in first level, some are encapsuled into others (have P110 into Bulbs, for example)
Tried to update (last version of integration + last version of HA + hard reboot done)
I'm losing connection to some device, integration keep reloading, and sometime the disconnected devices appear, sometime other get offline...

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/78665358/9d071381-1365-4239-b106-3be8d8ab785f)

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/78665358/d8992a6d-8fce-47f7-87bb-5df2d2ba6867)

**Comment by jokok0** [comment]
Removed all the devices and added them again, let's hope this won't happend again

**Comment by petretiandrea** [comment]
You need a static IP for the devices
