### ISSUE TITLE
Become online/offline trigger for Tapo P115

### ISSUE THREAD

**Issue by QuAzI** [petretiandrea/home-assistant-tapo-p100#591]
Would it be possible to add a new trigger or state to check that device become online?
To trigger automatization, which was skipped while the device was offline.

To process next flow
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/1897605/2bd1f98a-337a-4839-8588-da9c6e8cf55e)

Currently, I have to use "Become switch off" to check that device returned online. And as a result, I can't stop the scenario by pressing a button.

**Comment by petretiandrea** [comment]
Same issue of #597
