### ISSUE TITLE
Error fetching tapo data: Unexpected exception:

### ISSUE THREAD

**Issue by codyc1515** [petretiandrea/home-assistant-tapo-p100#597]
## Version of the integration
v2.10.2

## Configuration
P110 Outlet with Energy Monitoring (AU/NZ)
Firmware: 1.2.3 Build 230425 Rel.142542
Hardware: 1.0

## Describe the bug
The device is going unavailable often. It's in more or less the same place as another device which is not facing the same issue. Seems to have omly started since 2023.11 HA release.

```
This error originated from a custom integration.

Logger: custom_components.tapo.coordinators
Source: helpers/update_coordinator.py:322
Integration: TP-Link Tapo (documentation, issues)
First occurred: 19:19:06 (4 occurrences)
Last logged: 20:11:45

Error fetching tapo data: Unexpected exception:
```

## Debug log
[home-assistant_tapo_2023-11-03T07-16-51.722Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/13247707/home-assistant_tapo_2023-11-03T07-16-51.722Z.log)

**Comment by codyc1515** [comment]
Possibly same issue as #591.

**Comment by codyc1515** [comment]
I think this is Wi-Fi Connectivity related. Recently did some works in garage where the Wi-Fi extender is located and the Tapo was not connecting to the Garage AP. Have blocked it Deco and unblocked and it's now connecting to that Garage Deco, so will monitor it. Checking signal level on an adjacent P110 and both are now showing -19 dBm (as opposed to the -70 of before). Perhaps we should add some exception handling suggesting to check network connectivity if it disconnects in that circumstance.

**Comment by delatt** [comment]
I'm also seeing a lot of these errors, be good if we could get some more logging around it

**Comment by codyc1515** [comment]
Did you check your devices wi-fi signal?

**Comment by delatt** [comment]
Yeah, all very strong

**Comment by codyc1515** [comment]
Please share a screenshot of your wi-fi signal from the `Devices and services` area.

**Comment by delatt** [comment]
You might be onto something there, the signal is all over the place - sometimes dropping past -80 dBm. I'll tweak some AP settings and keep an eye on things
