### ISSUE TITLE
Could the S505D model be added to the supported devices?

### ISSUE THREAD

**Issue by cbarham84** [petretiandrea/home-assistant-tapo-p100#601]
**Is your feature request related to a problem? Please describe.**
Trying to set up S505D devices and the debug logs state Device Not Supported

**Describe the solution you'd like**
Would love to see the Tapo S505D smart dimmers be supported with this integration if possible

**Describe alternatives you've considered**
I have tried the TP Link integration but the Tapo devices are housed in the Tapo app only.

Error Log:

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 1:39:06 AM (1 occurrences)
Last logged: 1:39:06 AM

Error setting up entry Office Light Left for tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 52, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 50, in async_setup_entry
    return await device.initialize_device(hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/tapo_device.py", line 28, in initialize_device
    ).get_or_raise()
      ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/functional/tri.py", line 159, in get_or_raise
    raise self.value
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.1.244 not supported!

**Comment by jvmahon** [comment]
The S500 and S505D can both be added to HomeAssistant directly using the Matter integration.

You should start by first adding to Apple iOS Home or Google Home using the Matter QR code.  That code can only be used for the first device you add to. You can then generate additional codes from within Apple iOS Home or Google Home which are used with the Home Assistant phone app to pair the device to HomeAssistant.

The process on Apple iOS is, for the accessory you want to add to HomeAssistant, 
1: Open Home App on iOS Device 
2: Go to the settings/detail section of the Matter Device, scroll to the bottom and select Turn on Pairing Mode. This will generate a new Matter pairing code
3. Go to the HomeAssistant iPhone App, Devices section, and select Add Device. Then choose "Matter" and enter your pairing code.

**Comment by petretiandrea** [comment]
> S500

I will add in next release
