### ISSUE TITLE
Tapo integration

### ISSUE THREAD

**Issue by Le-Syl21** [petretiandrea/home-assistant-tapo-p100#603]
Hi,

I've just install my PI4 with Home Assistant 2023.11.1

When I search TAPO in integration, I can't find it.
![Capture d’écran du 2023-11-06 15-36-07](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/67423638/b75459bb-2235-415b-9b30-0838da74d8af)

When I search TAPO plugin I can't find it.
![Capture d’écran du 2023-11-06 15-37-13](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/67423638/bdef2a2c-b2ba-4d75-afc7-c1ec215a3254)

When I try to had repo, I've got an error:
![Capture d’écran du 2023-11-06 15-36-57](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/67423638/247e8621-fea8-462b-9dea-9e67d56a956a)

I want to control my Tapo P100, if somebody can help me

**Comment by cbarham84** [comment]
Are you searching in "Devices & Services" or are you searching in HACS?

You'll need HACS configured on your Home Assistant instance in order to download this integration, so if you don't have it downloaded and installed then you'll need to go here. [HACS Link](https://hacs.xyz/)

**Comment by Le-Syl21** [comment]
Ok, I was thinking HACS is the HA store. I will try to install it this
evening. Thx for answer
