### ISSUE TITLE
Lights keep going missing when i restart HA

### ISSUE THREAD

**Issue by jimmisavage** [petretiandrea/home-assistant-tapo-p100#608]
## Configuration

Tapo L510 bulb
1.1.0 Build 230721 Rel.224802

## Describe the bug

I have 5 of these Tapo bulbs but every time i restart HA i lose a couple of them at random. They all have a static IP on my network. This has been ongoing for 6 months+ (since i first started using HA). It's just a bit annoying.

**Comment by petretiandrea** [comment]
What means "lose"? It disappears or there are some errors?

**Comment by au51gtm** [comment]
I have the same issue.  After a restart, these devices go offline from HA but are still active on the Tapo app.  One is a bulb, the other is a switch.
![Tapo HA Restart Issue](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/123373912/2b2405eb-a153-4679-a8d4-3cc783144e9c)

**Comment by petretiandrea** [comment]
Can you post logs?

**Comment by au51gtm** [comment]
Hi,
Yesterday, I removed the device and added it again and normal function was restored, however this morning I checked and it is back to the same 'Failed Setup' error.  Attached is the debug file.

[home-assistant_tapo_2023-11-28T08-20-12.796Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/13485397/home-assistant_tapo_2023-11-28T08-20-12.796Z.log)

**Comment by au51gtm** [comment]
Sorry, some more detail.  Even though it says that the status is 'Failed Setup', I can still switch it on an off via HA.  I hope this information and the above log file helps you.

**Comment by petretiandrea** [comment]
> Hi, Yesterday, I removed the device and added it again and normal function was restored, however this morning I checked and it is back to the same 'Failed Setup' error. Attached is the debug file.
> 
> [home-assistant_tapo_2023-11-28T08-20-12.796Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/13485397/home-assistant_tapo_2023-11-28T08-20-12.796Z.log)

This is probably due to change of ip address of your device. You need to make the tapo device ip static, or try to enable mac tracking, which is an experimental feature.
