### ISSUE TITLE
Tapo P110 result error

### ISSUE THREAD

**Issue by bignellrp** [petretiandrea/home-assistant-tapo-p100#639]
After a recent auto firmware update this python module has stopped working.

Device: Tapo P110
Firmware Version: 1.3.0 Build 230905 Rel.152200
Python 3.9
PyP100==0.1.2

Python Error:

python3 test_plug.py
{'error_code': 1003}
Traceback (most recent call last):
  File "test_plug.py", line 32, in <module>
    control_smart_plug("off")
  File "test_plug.py", line 16, in control_smart_plug
    plug.handshake() #Creates the cookies required for further methods
  File "env/lib/python3.9/site-packages/PyP100/PyP100.py", line 128, in handshake
    encryptedKey = r.json()["result"]["key"]
KeyError: 'result'

Device works in the Tapo app. But python gives the error above.

**Comment by MWLaw** [comment]
Seems to be similar issue with Tapo T100 motion sensor!

**Comment by petretiandrea** [comment]
PyP100 is not my library

**Comment by eocula** [comment]
Has anybody a solution for this? As I have the same issue/error

**Comment by bignellrp** [comment]
I have a work around for now until the library is fixed. Install the real home assistant docker image, pair the Tapo with it, use the home assistant api to control the plug.

**Comment by eocula** [comment]
I found the solution meanwhile, by using the updated PyP100-package from https://github.com/almottier/TapoP100 instead of the original one of https://github.com/fishbigger/TapoP100

**Comment by petretiandrea** [comment]
PyP100 is not my library (plugp100 Is) and this integration is based on my library, so this issue is not related to this repository

**Comment by bignellrp** [comment]
Yes you said that. Thanks.

**Comment by raucal** [comment]
Hello, I still have the same problem, any solution?

**Comment by saepien** [comment]
Same issue, now 1 year later......
