### ISSUE TITLE
Don't delete the complete content of the session's cookie_jar - in HA a websession is shared across multiple integrations

### ISSUE THREAD

**Issue by marq24** [petretiandrea/home-assistant-tapo-p100#642]
Hi,

https://github.com/search?q=owner%3Apetretiandrea%20cookie_jar&type=code

The websession in home assistant is shared across multiple integrations - so when your integration (framework) requires some cookies to be deleted - then please don't flush all the other cookies (that other integrations need)...

So please don't clear the cookie_jar - or make sure that you use a exclusive aio-http session in your ha integration.

Kind Regards

**Comment by petretiandrea** [comment]
This issue is a nice catch, I think can resolve a lot of instability of integration itself, so thanks you

**Comment by marq24** [comment]
you can also checkout my "work around" - implementation, where I have overwritten the CookieJar.clear() method (when my integration gets a session) - and when then anybody calling clear(), I save at least my cookies and then proceed...
