### ISSUE TITLE
Failed to scan network - operation not permitted

### ISSUE THREAD

**Issue by Stono** [petretiandrea/home-assistant-tapo-p100#646]
Hello, 
I'm seeing the following warnings in my logs:

```
Logger: plugp100.discovery.local_device_finder
Source: lsiopy/lib/python3.11/site-packages/plugp100/discovery/local_device_finder.py:98
First occurred: 20:31:55 (4 occurrences)
Last logged: 20:31:55

Failed to scan network 192.168.4.67/22 error: [Errno 1] Operation not permitted
```

Guessing that's to do with the fact I enabled "Try to track device dynamic ip using MAC address" (which i appreciate is experimental).

I have a somewhat unique setup so it's likely my own fault, but i'm running `haas` in docker, using `kubernetes` / `k3s`.  I am running `hostNetwork: true` and `securityContext.privileged: true`, which effectively puts the process on my host network (it can see all other network devices, DNLA, etc), but I get this message with this extension.

**Comment by petretiandrea** [comment]
I suggest you to disable mac tracking, it's an experimental feature and a lot of cases are not actually handled. I will try to stabilize this functionality
