### ISSUE TITLE
Managing enities in configuration.yaml

### ISSUE THREAD

**Issue by komOrmand** [petretiandrea/home-assistant-tapo-p100#65]
Hi!
Thanks for your work! Im using it to manage my color bulb, works perfectly!
I think it should be nice to have a possibility to configure this integration via configuration.yaml like in old version. Didnt find this way in a new one, so think it you may return it :)

![Screenshot_3](https://user-images.githubusercontent.com/87458360/130615054-8b876ffa-7425-43c5-8b02-016d07e14971.png)

**Comment by petretiandrea** [comment]
Now supported into `1.2.0` try it :)
