### ISSUE TITLE
Unable to control L530 after upgrade to 11.2 Build 231212

### ISSUE THREAD

**Issue by virtualorg1** [petretiandrea/home-assistant-tapo-p100#652]
## Version of the integration
VERSION = "2.12.1"

## Configuration
L530 
Firmware: 11.2 Build 231212

## Describe the bug
Three L530 lights were working fine until I performed a firmware update to 11.2 Build 231212 on the device and now none of them are working in Home Assistant.

In Home Assistant, the devices are showing 'Failed setup, will retry'.
When selecting 'reload', it returns 'The integration was reloaded' but the status remains at 'Failed setup, will retry'.
They all work with the Tapo app and with Alexa.

## Debug log
2023-12-17 10:21:13.577 WARNING (MainThread) [plugp100.api.tapo_client] Default protocol not working, fallback to KLAP ;)

**Comment by nexusmaniac** [comment]
+1 (But for L930) 😇 

I've not updated the firmware on my device, I don't have Tapo installed anymore but I'll see if I can go and find the FW version.

`Firmware: 1.0.11 Build 231016 Rel.192144` (Reported by HA, not sure how old that info is, though)

```
Logger: plugp100.api.tapo_client
Source: lsiopy/lib/python3.11/site-packages/plugp100/api/tapo_client.py:253
First occurred: 02:02:42 (398 occurrences)
Last logged: 10:50:52

Default protocol not working, fallback to KLAP ;)
```

**Comment by jaward916** [comment]
> +1 (But for L930) 😇
> 
> I've not updated the firmware on my device, I don't have Tapo installed anymore but I'll see if I can go and find the FW version.
> 
> `Firmware: 1.0.11 Build 231016 Rel.192144` (Reported by HA, not sure how old that info is, though)
> 
> ```
> Logger: plugp100.api.tapo_client
> Source: lsiopy/lib/python3.11/site-packages/plugp100/api/tapo_client.py:253
> First occurred: 02:02:42 (398 occurrences)
> Last logged: 10:50:52
> 
> Default protocol not working, fallback to KLAP ;)
> ```

+1 for L930 too

**Comment by petretiandrea** [comment]
It's a bug related to new firmware version I will release a fix asap

**Comment by petretiandrea** [comment]
The hotfix is ready https://github.com/petretiandrea/home-assistant-tapo-p100/releases/tag/v2.12.2 :)

**Comment by virtualorg1** [comment]
It worked for me. That's totally brilliant and so quick. Thanks!

**Comment by Elarion245** [comment]
I still get the warning about the fallback for my three P115 plugs since upgrading the firmware to 1.3.0
