### ISSUE TITLE
HA 2024.1.0 deprecations

### ISSUE THREAD

**Issue by tjorim** [petretiandrea/home-assistant-tapo-p100#662]
## Version of the integration
2.12.2

## Configuration
n/a

## Describe the bug
Updated to HA version 2024.1.0b0 and saw the following warnings:

- [ ] STATE_CLASS_MEASUREMENT was used from tapo, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/petretiandrea/home-assistant-tapo-p100/issues
- [ ] STATE_CLASS_TOTAL_INCREASING was used from tapo, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please create a bug report at https://github.com/petretiandrea/home-assistant-tapo-p100/issues
- [ ] DEVICE_CLASS_SIGNAL_STRENGTH was used from tapo, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.SIGNAL_STRENGTH instead, please create a bug report at https://github.com/petretiandrea/home-assistant-tapo-p100/issues
- [ ] ENERGY_KILO_WATT_HOUR was used from tapo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/petretiandrea/home-assistant-tapo-p100/issues
- [ ] POWER_WATT was used from tapo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/petretiandrea/home-assistant-tapo-p100/issues
- [ ] TIME_MINUTES was used from tapo, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.MINUTES instead, please create a bug report at https://github.com/petretiandrea/home-assistant-tapo-p100/issues

**Comment by ChristophCaina** [comment]
#666
