### ISSUE TITLE
TS15 Switch shows as Light

### ISSUE THREAD

**Issue by aazam476** [petretiandrea/home-assistant-tapo-p100#663]
I recently bought and added a TS15 Tapo switch to home assistant using your integration, but it shows up as a light, and not as a switch. Is there anyway to fix this?

**Comment by petretiandrea** [comment]
Because many people have requested to integrate it as light

**Comment by aazam476** [comment]
Oh, that's weird, especially when HA allows you to change a switch to a light using a helper. Thanks so much for the response though!
