### ISSUE TITLE
Tapo H100 Failed setup

### ISSUE THREAD

**Issue by kinnoon123** [petretiandrea/home-assistant-tapo-p100#677]
## Version of the integration

Home Assistant Tapo Integration V2.13.0

## Configuration

Device info
H100
by TP-Link
Firmware: 1.5.4 Build 231121 Rel.105224
Hardware: 1.0
MAC: 5C:E9:31:CF:65:E8

## Describe the bug
this my first time with tapo integration,
when i connected Tapo H100 successful but device is not show entity (siren)
and it show fail setup,will retry!

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/155867658/9057ec5c-87c7-4d27-9d7e-934efc8c00ef)

## Debug log

2024-01-07 11:50:10.584 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 802D322CAEA29C0ED741F54C77E612FF21D472C6
2024-01-07 11:50:11.050 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.041 seconds (success: True)
2024-01-07 11:50:11.097 INFO (MainThread) [custom_components.tapo.hub.tapo_hub] Found 0 children associated to hub 802D322CAEA29C0ED741F54C77E612FF21D472C6

**Comment by andrea-patricelli** [comment]
I have the same issue. Might be the absence of any device connected withe the hub. I haven't any ATM. If so only error should be properly managed.

**Comment by petretiandrea** [comment]
Yes, I think it's an issue related to 0 device connected, I will fix

**Comment by glbnz** [comment]
Same issue here; no devices connected to the hub. Is the workaround to add the hub by adding a device first? Was just planning to use this hub as a doorbell. Thanks!

> 2024-01-21 17:00:42.090 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Re-using setup API to create a coordinator
2024-01-21 17:00:42.179 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.046 seconds (success: True)
2024-01-21 17:00:42.324 INFO (MainThread) [custom_components.tapo.hub.tapo_hub] Found 0 children associated to hub 802D16**********
2024-01-21 17:01:11.424 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Re-using setup API to create a coordinator
2024-01-21 17:01:11.570 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.084 seconds (success: True)
2024-01-21 17:01:11.593 INFO (MainThread) [custom_components.tapo.hub.tapo_hub] Found 0 children associated to hub 802D16**********

**Comment by nirajbhatt7** [comment]
Same issue. 0 devices connected to the hub and was planning to use it as a bell. In the controls, It shows "The device has no entities" message. I was expecting the bell to be the entity for H100 so that I can do automation for it.

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/3318439/78accd44-7f38-448b-8c73-7a52cd95600d)

**Comment by mathsteck** [comment]
Same issue here, I managed to add the first H100 successfully (with 6 devices attached to it) but the second one (with no devices on it) is failing 
<img width="514" alt="image" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/3390366/73f0daa1-165f-42eb-9ebf-2f238f4c024c">

**Comment by aymanibousi** [comment]
Same as @mathsteck    any idea how to fix without buying any other devices to link?

**Comment by DESOBAV** [comment]
Hello - as I understand the problem here is that it is not possible to activate the siren on the h100 to use it as a doorbell.

I have the same problem here - I have a h100 with 6 devices connected and all is working as expected. But I have no entity for the siren, so not able to activate through HA. In the description of the integration is explicit written that the siren is supported.

So - is this a problem on my side or is there a bug in the integration - not really sure.

Thanks a lot

**Comment by DESOBAV** [comment]
> Yes, I think it's an issue related to 0 device connected, I will fix

Hy - no, I have 6 devices connected and the siren is still missing. Checked it with my old HA server - same problem here.

**Comment by jamesg226** [comment]
Also seeing this issue. It was working fine on Friday and Saturday. I updated the integration in HACS and today (Sunday) it is no longer working. I doubt the H100 has auto updated its firmware in the last 24 hours, could it be something in the latest update to HACS?

**Comment by matt-cahill** [comment]
Thanks this is fixed for me in 3.0.0. My h100 registers with no devices attached, the siren device is present and successfully triggers the siren sound.

**Comment by jamesg226** [comment]
This is fixed for me also in v3.0.0, working perfectly. Thank you!

**Comment by DESOBAV** [comment]
Fixed also for me - thanks!

**Comment by kinnoon123** [comment]
Thank for support us!!!!!! 👍 
Now i can use chime entity without connected other device

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/155867658/8cd603b7-b261-4236-9f0d-3a1cc6fae683)
