### ISSUE TITLE
L920 no longer providing light entity. Only overheat.

### ISSUE THREAD

**Issue by mdot9** [petretiandrea/home-assistant-tapo-p100#697]
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/20266535/0070df3f-4763-47d3-9b3f-8814b9ffc955)

L920
by TP-Link
Firmware: 1.1.3 Build 231229 Rel.164316
Hardware: 1.0

Was working this morning, now even after re-adding it doesn't get the light entity and cannot control the device.

**Comment by JaidevDPendse** [comment]
Has the firmware for your device been updated before becoming unavailable

**Comment by apexcz1** [comment]
Same problem

**Comment by petretiandrea** [comment]
Firmware version?
