### ISSUE TITLE
Error while setting up tapo platform for switch

### ISSUE THREAD

**Issue by robtesch** [petretiandrea/home-assistant-tapo-p100#70]
## Version of the custom_component
v1.1.4

## Configuration
Item was set up with the UI, thus no YAML config available. Everything has worked perfectly for months. I have 2 tapo p100 plugs, no lights.

## Describe the bug
It seems that the latest version of HA (core-2021.9.4) and Supervisor (supervisor-2021.09.0) have broken this component. 
Not sure if relevant, but the OS is Home Assistant OS 6.3 and it's running on an RPi4.

## Debug log

```text
Logger: homeassistant.components.switch
Source: custom_components/tapo/switch.py:15
Integration: Switch (documentation, issues)
First occurred: 8:47:26 (2 occurrences)
Last logged: 8:47:26

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 15, in async_setup_entry
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
AttributeError: 'NoneType' object has no attribute 'model'
```

**Comment by petretiandrea** [comment]
Try new version `1.2.0` and follow the [video ](https://github.com/petretiandrea/home-assistant-tapo-p100/blob/main/README.md) to install the integration
