### ISSUE TITLE
H100 motion sensor delayed detection

### ISSUE THREAD

**Issue by MWOITC** [petretiandrea/home-assistant-tapo-p100#707]
I have setup automation in HACS for a Tapo Motion sensor and a Tapo smart light bulb using Tapo integration v2.14..0. Idea is that motion will turn the light on - very simple. However there is quite a delay in the light turning on hen using HA with TAPO integration. When using automation via the TAPO app it is instant.
Comparing when motion gets detected in HA and the actual TAPO app I noticed that there can be up to 15 seconds difference. If I enter the same room a couple of minutes later, the timings can be almost on par.

**Comment by deezid** [comment]
Same issue here. 
Matter integration is instant but Occupancy clear state doesn't work with automations either...
