### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by djdarlo** [petretiandrea/home-assistant-tapo-p100#716]
## Configuration

```yaml
Add your logs here.
```

## Describe the bug

I have just updated to the latest version of the integration and get migration error for all my devices. 

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/20640104/2aaf09c0-69cc-473e-b03d-432352c586e3)

## Debug log

```text

Add your logs here.

```

**Comment by petretiandrea** [comment]
Be sure your device are online

**Comment by a42wg** [comment]
Same issue here, only have one plug in the integration and it works from the Tapo android app

**Comment by djdarlo** [comment]
All devices are online and available through the iOS app.

**Comment by jojkopeter** [comment]
I have the same problem. Migration error

**Comment by petretiandrea** [comment]
You can do two things:
- post here your logs
- re-configure your device

**Comment by a42wg** [comment]
Well in my case it sort of solved itself. I restarted HA and after a while the integration found a "new device", which was actually the same as the one not migrating. I provided the app credentials and the integration works again, with same entity names and all.

So all good here

Reg Anders

**Comment by rbukholt** [comment]
> You can do two things:
> 
>     * post here your logs
> 
>     * re-configure your device

I would like to help - by posting my logs. I have reverted to the 2.x.x version though. Later today I will change to 3.0.0.
I have not posted logs before. Could you briefly describe where and how to get those?

The symptoms is like others descripe. In TAPO App - everything is fine. In Home Assistant - some devices are active and others are dead. I have more than 20 devices. Many the same product. Some of the same kind are active. And some dead.
I have observed that the dead one have had their name changed to non-capitals. Ex "Entre" changed to "entre".

Normally I can update the integration with no errors. But with change from 2 -> 3 is a different story. I would like to contribute to the solution.

**Comment by rbukholt** [comment]
> > You can do two things:
> > ```
> > * post here your logs
> > 
> > * re-configure your device
> > ```
> 
> I would like to help - by posting my logs. I have reverted to the 2.x.x version though. Later today I will change to 3.0.0. I have not posted logs before. Could you briefly describe where and how to get those?
> 
> The symptoms is like others descripe. In TAPO App - everything is fine. In Home Assistant - some devices are active and others are dead. I have more than 20 devices. Many the same product. Some of the same kind are active. And some dead. I have observed that the dead one have had their name changed to non-capitals. Ex "Entre" changed to "entre".
> 
> Normally I can update the integration with no errors. But with change from 2 -> 3 is a different story. I would like to contribute to the solution.

I have just gone to 3.0.0 again and now everything seem to work. Meaning I can't reproduce the error. When I updated in the more automatic manner something went wrong - but not now. Strange.

**Comment by eckley** [comment]
Hi,
Migrating to 3.0.0 appears to have given me the same error.
Currently on HA: 2024.4.2
If it helps HA and tapo devices are on different LANs
I've tried downgrading to 2.X.X and back to 3.0.0, with no change.

`Logger: homeassistant.config_entries
Source: config_entries.py:822
First occurred: 8:58:02 PM (3 occurrences)
Last logged: 8:58:02 PM

Error migrating entry cabinet display lights for tapo
Error migrating entry bookshelf display lights for tapo
Error migrating entry outside display lights for tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 822, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 74, in async_migrate_entry
    await migrate_entry_to_v8(hass, config_entry)
  File "/config/custom_components/tapo/migrations.py", line 25, in migrate_entry_to_v8
    raise Exception("Failed to fetch data to migrate entity")
Exception: Failed to fetch data to migrate entity`

**Comment by eckley** [comment]
In addition, when I removed and readded one of the devices and that worked.

**Comment by petretiandrea** [comment]
If you're having issue with migration, I suggest you to remove and re-add the device. With a new automatic discovery, there many breaking changes. Try with new version 3.1.0
