### ISSUE TITLE
non trova il p100

### ISSUE THREAD

**Issue by francuccello** [petretiandrea/home-assistant-tapo-p100#72]
Ho installato tapo e vedo tapo controller in hacs fra le integrazioni come devo fare a configurare il sistema in maniera che veda la mia presa ?? scusa ma sono un poì ignorante!!!

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by petretiandrea** [comment]
Prova a seguire il video che trovi [qui](https://github.com/petretiandrea/home-assistant-tapo-p100/blob/main/README.md) :)
