### ISSUE TITLE
T100 Motion Sensor

### ISSUE THREAD

**Issue by MatrixAustin** [petretiandrea/home-assistant-tapo-p100#722]
I cant seem to figure out how to add my Tapo T100 Motion Sensor. I added my hub and it comes up but i cant add the motion sensor and it does not come up through the hub. How should i add this?

Thank You

**Comment by MontyPud** [comment]
I seem to be in the same boat as MatrixAustin.  I have added the sensor to the app, waited a few hours and tried adding it to my HA.  Add Device only seems to want to add a new hub, which I already have working.  Rummaging around in the system options, I have enable newly added entities and have clicked update, but alas no T100 is showing.

**Comment by MontyPud** [comment]
Thanks petretiandrea.  I tried that and it didn't seem to work for me. <shrug>  I did find that rebooting HA worked though.  Yay!
