### ISSUE TITLE
P100 Failed to connect

### ISSUE THREAD

**Issue by turokhan** [petretiandrea/home-assistant-tapo-p100#725]
Hi,

For some strange reason i cannot connect to my P100's.  Just say the above.

Version 3 just came out and i had all hope, but alas, HA still refuses it.  Might have to ditch the TAPOs and stick with my TUYA ones, as these connect without issue.

**Comment by dickmann** [comment]
same here. Were working fine before, now stopped working...

**Comment by stefanmairhofer** [comment]
Unfortunately i have same issue... with version 3 all P100 devices stopped working in HA

**Comment by petretiandrea** [comment]
Fixed by [3.1.0](https://github.com/petretiandrea/home-assistant-tapo-p100/tree/3.1.0)

**Comment by turokhan** [comment]
> Fixed by [3.1.0](https://github.com/petretiandrea/home-assistant-tapo-p100/tree/3.1.0)

no it doesn't.  Just tried with 3.1 and it just says failed to connect.

**Comment by rjblake** [comment]
My plug lost connection with HA this morning at 04:20 and tried to reload integration, create new, etc. All I get is a 'Failed to Connect' message now. I can connect and control plug with Tapo app, but not this integration.

**Comment by mlorenzo-stratio** [comment]
Same as @rjblake, version 2 here. Everything works fine in Tapo app but cannot add this one. It just says "Failed to connect"

**Comment by mattse-san** [comment]
Using v3.1.2 and successfully pared two P100 HW v2.0 (FW 1.2.5 Build 240411).
I get the exact same error log as ml0renz0 for the remaining 2 P100 which are also HW v2.0 and same FW.

Any idea what the problem could be?
Did you solve the issue in the meanwhile @ml0renz0 ?

**Comment by ml0renz0** [comment]
Sorry I didn't try again, switched to zigbee plugs as I wanted to keep everything local as much as I could.

**Comment by mattse-san** [comment]
After reading through https://github.com/petretiandrea/home-assistant-tapo-p100/issues/122 I realized that not only user name email must not contain upper case letters but also the password. As my password included an upper case letter I just changed it and afterwards the connect of P100 worked like a charm.... RTFM!!
