### ISSUE TITLE
Methodology compated to TP-Linl extension?

### ISSUE THREAD

**Issue by SvenAbels** [petretiandrea/home-assistant-tapo-p100#726]
Hi,

I saw that there is also an official integration from home assistant for TP-Link: https://www.home-assistant.io/integrations/tplink/

If I only want to integrate the Tapo plugs (e.g. TP110, TP115,...), is there any difference between the two integrations? Do both get the data via local network requests?

Best regards,

Sven

**Comment by petretiandrea** [comment]
This integration retrieve data by local network requests, also I think the python-kasa integration too. This integration was born to support tapo devices, while python-kasa (which is used by integration linked by you) for kasa devices, but now they are providing partial support for tapo devices too.

**Comment by SvenAbels** [comment]
Thanks  a lot for the explanation :-)
