### ISSUE TITLE
 invalid supported color modes with 3.0 and 2024.3

### ISSUE THREAD

**Issue by Sk1vvy** [petretiandrea/home-assistant-tapo-p100#727]
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/148657401/774252f8-e2ff-4d61-b5dc-0021f67e2712)

-->

## Version of the integration

 latest, 3.0

## Configuration

Tapo L920 with latest firmware (1.1.3)

```yaml
Add your logs here.
```

## Describe the bug

Logs show this error after updating to 3.0 (from 2.14 i believe?) and 2024.3 HAOS. Also automations with color change doesn't work on this lightstrip now and showing error:
"  File "/usr/local/lib/python3.12/site-packages/plugp100/common/functional/tri.py", line 159, in get_or_raise
    raise self.value
plugp100.responses.tapo_exception.TapoException: Returned error_code: TapoError.ERR_PARAMS: Request params error" 

That's account only my Tapo LED, other light from different brand is fine

## Debug log

```text

Add your logs here.

```

**Comment by RiderCrazy** [comment]
Hi

I've got something similar.

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/78437975/03b1ea8d-20a9-499a-9dce-f78fb3056986)

**Comment by petretiandrea** [comment]
Fixed by [3.1.0](https://github.com/petretiandrea/home-assistant-tapo-p100/tree/3.1.0)
