### ISSUE TITLE
[plugp100.protocol.klap_protocol] Query failed after succesful authentication

### ISSUE THREAD

**Issue by todely** [petretiandrea/home-assistant-tapo-p100#729]
## Version of the integration
HA
Core 2024.4.0.dev20240301
Interface utilisateur 20240301.0.dev
Integration Tapo V3.0.0 (by HACS)

## Configuration

Tapo P100
1.5.5 Build 20230927 rel. 40646

## Describe the bug

When i switch plug to on from HA, it goes back to off after 20 secondes.
When i switch plug to on from Tapo app, it goes back to off after 20 secondes.
When i disable this P100 in HA, i switch plug to on from Tapo app, it stay on
When i enable this P100 in HA, it go to off

## Debug log

2024-03-16 16:30:57.180 ERROR (MainThread) [plugp100.protocol.klap_protocol] Query failed after succesful authentication at 1710603057.1802678.  Host is ('http', '192.168.0.65', 80), Available attempts count is 3, Sequence is -760973218, Response status is 429, Request was <plugp100.requests.tapo_request.TapoRequest object at 0x7f8d8a66f0>

```

**Comment by amamoh** [comment]
same here

**Comment by petretiandrea** [comment]
429 means "Too many requests", are you flooding your device?

**Comment by todely** [comment]
Hello

I don't do anything else than connect it to HA.
I will check if script do something but i think no

**Comment by petretiandrea** [comment]
Fixed by [3.1.0](https://github.com/petretiandrea/home-assistant-tapo-p100/tree/3.1.0)
