### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by worrah1** [petretiandrea/home-assistant-tapo-p100#73]
Hello. I have default yaml file with tapo_p100_control installed  (but not working though)
And it is almost impossible to use because of the huge switch lag and constant errors with my six p100 plugs.
What is going on?

> Logger: custom_components.tapo
> Source: helpers/update_coordinator.py:219
> Integration: Tapo Controller (documentation, issues)
> First occurred: 4:47:09 (14 occurrences)
> Last logged: 4:48:40
> 
> Error fetching tapo data:

> 2021-09-23 04:46:52 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration sleep_as_android which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2021-09-23 04:46:52 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_gateway3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2021-09-23 04:46:52 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2021-09-23 04:46:52 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tapo_p100_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2021-09-23 04:46:52 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2021-09-23 04:47:08 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
> 2021-09-23 04:47:08 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
> 2021-09-23 04:47:08 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
> 2021-09-23 04:47:08 WARNING (MainThread) [homeassistant.setup] Setup of timer is taking over 10 seconds.
> 2021-09-23 04:47:09 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:47:09 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Living Room' for tapo integration not ready yet: None; Retrying in background
> 2021-09-23 04:47:11 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:47:11 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Hall' for tapo integration not ready yet: None; Retrying in background
> 2021-09-23 04:47:11 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:47:11 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Kitchen' for tapo integration not ready yet: None; Retrying in background
> 2021-09-23 04:47:12 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:47:12 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Office' for tapo integration not ready yet: None; Retrying in background
> 2021-09-23 04:47:15 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:47:15 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Living Room' for tapo integration not ready yet: None; Retrying in background
> 2021-09-23 04:47:15 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:47:15 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Bedroom' for tapo integration not ready yet: None; Retrying in background
> 2021-09-23 04:47:19 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.xiaomi_cloud] Timeout while requesting MIoT api /home/device_list
> 2021-09-23 04:47:30 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:47:51 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:48:21 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:48:40 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:48:40 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:48:40 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:48:40 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:48:40 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:49:11 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:49:50 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:49:50 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:50:28 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:50:28 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:50:28 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:50:41 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:52:08 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:52:11 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:52:18 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:52:18 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:52:18 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
> 2021-09-23 04:52:19 ERROR (MainThread) [custom_components.tapo] Error fetching tapo data: 
>

**Comment by worrah1** [comment]
also this
```
Logger: homeassistant.core
Source: custom_components/tapo/tapo_entity.py:33
Integration: Tapo Controller (documentation, issues)
First occurred: 20:11:47 (1 occurrences)
Last logged: 20:11:47

Error executing service: <ServiceCall switch.turn_off (c:b331df49929bcc1b5ce8c273872eaaeb): entity_id=['switch.hall', 'switch.kitchen', 'switch.living', 'switch.living2']>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.50.124', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1508, in catch_exceptions
    await coro_or_task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 843, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/home/homeassistant/.homeassistant/custom_components/tapo/switch.py", line 30, in async_turn_off
    await self._execute_with_fallback(self._tapo_coordinator.api.off)
  File "/home/homeassistant/.homeassistant/custom_components/tapo/tapo_entity.py", line 33, in _execute_with_fallback
    await self.coordinator.api.login()
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.50.124:80 ssl:default [Connect call failed ('192.168.50.124', 80)]
```

**Comment by petretiandrea** [comment]
> I have default yaml file with tapo_p100_control installed (but not working though)

This integration, actually, doesn't support configuration via yaml file. You can add your tapo devices through UI.
Yaml configuration will be available as soon as possible in 1.1.5 (https://github.com/petretiandrea/home-assistant-tapo-p100/milestone/1)

**Comment by worrah1** [comment]
Yes, i know, i tried both versions. Neither of them not working properly - not yours with adding every plug through UI, nor tapo_p100_control through yaml file, they both lagging and disconnecting from plugs with errors i described above

**Comment by worrah1** [comment]
well, after day of waiting, tapo_p100 starts to work without problem
looks like that while you configuring new setup with big amount of plugs you somehow exceeding some connection limit
but if switch plugs quite rare, it's all ok
