### ISSUE TITLE
Always one device from Kasa Hub is missing

### ISSUE THREAD

**Issue by vsALLodds** [petretiandrea/home-assistant-tapo-p100#730]
## Version of the integration
3.0.0

## Configuration
Core 2024.3.1, Supervisor 2024.03.0, OS 12.1

1x HK100, 4x T110, 6x T315, 7x KE100

## Describe the bug

I get the Tapo integration in version 3.0.0 running on my HA (Core 2024.3.1, Supervisor 2024.03.0, OS 12.1) for a couple of weeks. 

I have one HK100, four T110, six T315 and seven KE100. Making in total 18 devices but from the start the Tapo integration showed only 17 devices. I could live with the situation because only one T110 was missing that was rearly used.

Since a week after a HA reboot the T110 is present but a KE100 is missing. I took a look into the debug logs an found an interesting situation that i can't explain, but could be the cause of the problem:

## Debug log
I have shortened the debug log by points that are not relevant from my point of view.
```
2024-03-12 13:55:43.912 DEBUG (MainThread) [plugp100.protocol.securepassthrough_transport] Raw request:
{
	"method": "get_child_device_list",
	"params": {
		"start_index": 0
	},
	"requestID": ...,
	"request_time_milis": ...,
	"terminal_uuid": "..."
}
2024-03-12 13:55:44.144 DEBUG (MainThread) [plugp100.protocol.securepassthrough_transport] Decrypted response:
Success(TapoResponse(
	error_code=0, result={
		'child_device_list': [
			{'device_id': '8035EB4D30...', 'model': 'KE100', ...},
			{'device_id': '80358C56EC...', 'model': 'KE100', ...},
			{'device_id': '802E04039D...', 'model': 'T315', ...},
			{'device_id': '802E98B493...', 'model': 'T110', ...},
			{'device_id': '802E6899B1...', 'model': 'T110', ...},
			{'device_id': '802EC8DD2A...', 'model': 'T110', ...},
			{'device_id': '802EEF98B6...', 'model': 'T110', ...},
			{'device_id': '802E5D115D...', 'model': 'T315', ...},
			{'device_id': '802EA5B58C...', 'model': 'T315', ...},
			{'device_id': '802EC5F530...', 'model': 'T315', ...}
		],
		'start_index': 0,
		'sum': 17
	},
	msg='No message')
)
2024-03-12 13:55:44.144 DEBUG (MainThread) [plugp100.protocol.securepassthrough_transport] Raw request:
{
	"method": "get_child_device_list",
	"params": {
		"start_index": 11
	},
	"requestID": ...,
	"request_time_milis": ...,
	"terminal_uuid": "..."
}
2024-03-12 13:55:44.304 DEBUG (MainThread) [plugp100.protocol.securepassthrough_transport] Decrypted response:
Success(TapoResponse(
	error_code=0, result={
		'child_device_list': [
			{'device_id': '8035F0BB7A...', 'model': 'KE100', ...},
			{'device_id': '80359EF13B...', 'model': 'KE100', ...},
			{'device_id': '80359DFB0B...', 'model': 'KE100', ...},
			{'device_id': '8035777DB3...', 'model': 'KE100', ...},
			{'device_id': '802EE09834...', 'model': 'T315', ...},
			{'device_id': '802EA6F4B0...', 'model': 'T315', ...}
		],
		'start_index': 11,
		'sum': 17
	},
	msg='No message')
)
2024-03-12 13:55:44.304 INFO (MainThread) [custom_components.tapo.hub.tapo_hub] Found 16 children associated to hub ...
```
The first request was made with start_index = 0 and showed 10 devices. The second request was made with start_index = 11 and showed 6 devices. Both responses clearly said that there sould be 17 devices in total but the integration only found 16 child devices.

From my point of view iff the get_child_device_list request needs a start_index parameter that starts with 0 for the first element. The second request must be made with parameter start_index = 10 instead of 11.

**Comment by petretiandrea** [comment]
Fixed by [3.1.0](https://github.com/petretiandrea/home-assistant-tapo-p100/tree/3.1.0)
