### ISSUE TITLE
Authentication and Config Flow Errors After Today's Update

### ISSUE THREAD

**Issue by au51gtm** [petretiandrea/home-assistant-tapo-p100#742]
After applying the Tapo Integration software update just received and applied today (13 April), I get 'Authentication Expired' and 'Config flow could not be loaded: {"message":"Invalid flow specified"}' on all Tapo devices.  I can successfully authenticate one device, but the other two give the Config flow error.  After a restart, I am again asked to authenticate all three devices and I cannot successfully escape from this loop.

**Comment by tjorim** [comment]
There seem to be some changes happening in the Tapo authentication backend, there was also a PSA about the Tapo camera control custom integration.

**Comment by joaofgf** [comment]
the problem remains after today's update.

**Comment by au51gtm** [comment]
I'm not sure if the updates of today have resolved the issue or not, however I was able to clear the last remaining authentication issue this afternoon (14:00 UTC), with no recurrences.  I can't be completely sure, as the errors would pop up every 24 hours or so, so let's see what tomorrow brings.

**Comment by larionof** [comment]
> I'm not sure if the updates of today have resolved the issue or not, however I was able to clear the last remaining authentication issue this afternoon (14:00 UTC), with no recurrences. I can't be completely sure, as the errors would pop up every 24 hours or so, so let's see what tomorrow brings.

I thought all was good( authentication was successfull on half of my devices) but then they as for reauthentication again in few secs, mins or hours. Also, some give "config flow could not be loaded" -error, and some do not accept the password. 

So, do not unfortunately believe the issue to be rectified yet.

**Comment by Pugwash69** [comment]
I have the same issue with 5 TP-Link bulbs, all giving the same issues as described.

**Comment by au51gtm** [comment]
I agree, it's still not resolved.  I've just had to re-authenticate one of my devices.

**Comment by au51gtm** [comment]
More authentication requests this morning . . . . .

**Comment by GazzaP1** [comment]
I have the same problem, The 3 plugs I have (In HA with the HACS Integration) were all working great up until the update on 14th April 2024, Driving me nuts.
I have removed two of them as I couldn't clear the (config flow) notifications, The remaining one I have to Re-Authenticate every 12 - 24 hours, It varies, or if I have to restart HA for any reason.
I have tried resetting all plugs back to factory settings and going through the setup procedure again, all firmware reports as up to date, I even removed and Re- installed the HACS and TP Link integrations within HA.
Hope a solution is found soon as I'm already looking at alternatives for the Tapo.

**Comment by perjury** [comment]
Same issue with 3 Tapo plugs

**Comment by larionof** [comment]
So, no resolution to the problem and possibly will not be in a while.
But...

I decided to ditch the 'TP-Link Tapo' -integration and use 'TP-Link Smart Home' instead( I did use this one for my cameras already for longer time, as well as with Kasas' devices). All automations and scripts work now as should.

**Comment by eacxx** [comment]
I'm another victim of this issue. :(
Let's cry together

**Comment by puppleStar77** [comment]
When I log in, it says ‘success’, but after 3 seconds, an authentication error occurs again.
Iam crying
![스크린샷 2024-05-06 134930](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/53265228/eeda5866-d0b4-4fa3-80ed-ff6993bc7ddb)

**Comment by Alllfff** [comment]
same issue but only one plug out of 8

**Comment by Pugwash69** [comment]
> As about myself, I've removed Tapo integration and I'm only using TP-Link one... All it's OK until now.

That's what I did too. Had to change all of my dashboard items, automations and scenes also though.

**Comment by DavidSpackman** [comment]
+1

**Comment by Timbo614** [comment]
I went the long way around I only have 6 Tapo sockets so I deleted them all from HA and the Tapo app and started all over again.
For a week now no authentication errors. is is a bit painful even with only six devices :(

**Comment by OldSystemMan** [comment]
Same problem here :(

**Comment by FredericJULIEN** [comment]
Same issue with 11 plugs (P100, P110 and P115)

**Comment by Flob895** [comment]
I'm hit with this too. I used to have authentication accepted for one day but now I just get "Invalid authentication: Server response doesn't match our challenge on ip 192.xxx.x.xxx"

**Comment by willsmarthome** [comment]
Still got problems with the authentication. Is there no solution.

**Comment by kongjudas** [comment]
Got ten cameras that suddenly got the same after I reinstalled the app on my iPhone. Any news? It won't accept my cloud password, even though I've checked it and refreshed it twice.

**Comment by DavidSpackman** [comment]
@petretiandrea 
Any thoughts on what is causing this?

**Comment by Ginxo** [comment]
same issue here

**Comment by doruchiulan** [comment]
same

**Comment by FlunkyFussel** [comment]
same

**Comment by devezaam** [comment]
same issue here

**Comment by zahellx** [comment]
same

**Comment by Ginxo** [comment]
The error remains the same, I just tested it with no luck

**Comment by Ginxo** [comment]
The issue remains the same. It's pretty annoying one, I'm not able to add integration with them (unless I remove devices from tapo and clear all the configuration I have there). I will try to debug the problem and provide solution for this, wish me luck :crossed_fingers:

**Comment by Timbo614** [comment]
My Issues have largely disappeared. If the device(s) is(are) powered off for some time like days then they seem to request re-authentication. Other than that I have not have problems since I re installed them all back in June.
I have a theory this is connected to DHCP obviously if powered off for days the lease(s) will expire and possibly the device gets a new IP this I have found is definitely a problem with Meross devices. So when they give problems and I need to re-config I give them a fixed IP via the router/MAC address. Which may be why my problems have mostly gone. YMMV of course.

**Comment by Ginxo** [comment]
> My Issues have largely disappeared. If the device(s) is(are) powered off for some time like days then they seem to request re-authentication. Other than that I have not have problems since I re installed them all back in June. I have a theory this is connected to DHCP obviously if powered off for days the lease(s) will expire and possibly the device gets a new IP this I have found is definitely a problem with Meross devices. So when they give problems and I need to re-config I give them a fixed IP via the router/MAC address. Which may be why my problems have mostly gone. YMMV of course. Added Note: I am Using he TP-Link Smart Home Integration.

I tried reassigning new IP and the error still happening...
