### ISSUE TITLE
Deco devices showing after 3.1.1 update

### ISSUE THREAD

**Issue by aronkahrs-us** [petretiandrea/home-assistant-tapo-p100#744]
## Version of the integration
v3.1.1

## Describe the bug

After updating to v3.1.1, my deco mesh routers started showing up, I don't think the integration can handle them, it shows authentication error, so probablly they shouldn't show up.
![Captura de pantalla 2024-04-14 112853](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/85702110/8fe5b583-3acd-4586-94cd-edf8f2efe4c3)

**Comment by 747Rocker** [comment]
> Hello, I have the same issue. After upgrading v3.1.1 my tapo H100 hub won't connect any more (authentication issue). Cheers.

Mine does but not my thermostats. They were unavailable after installing the update, and after i downgraded back to the old version and reset the integration, only the kasa hub is found.

**Comment by Rosko77** [comment]
Hello everyone, my KH100 was able to be reintegrated without any problems. Only the KE100 is no longer found with version 3.1.1. I have already deleted the adapter and set it up again after a HA restart. The thermostats are not recognized. Regards Rosko

**Comment by boule3** [comment]
> Hello, I have the same issue. After upgrading v3.1.1 my tapo H100 hub won't connect any more (authentication issue). Cheers.

Same problem for me with the H100, i'm back to 3.0.0 to make it works again

**Comment by paulo-serrao** [comment]
My deco's M5 also started to show up

**Comment by petretiandrea** [comment]
Please try 3.1.2. Regarding Deco device, you can simple ignore it, until I will filter it out from discovery
