### ISSUE TITLE
Tapo L530 HW 1.0 unavailable with 3.1.2

### ISSUE THREAD

**Issue by braymullo** [petretiandrea/home-assistant-tapo-p100#749]
## Version of the integration

3.1.2

## Configuration

L530 
hw version 1.0 
Fw version 1.3

```yaml
Add your logs here.
```

## Describe the bug

tapo l530 hw version 1.0 doesn’t work with 3.1.2. It works fine with 3.0.0

tapo L530 hw version 3.0 works with both 3.1.2 and 3.0

All combinations of removing/readding/reconfiguring attempted 

the entity says “Unavailable”

“ This entity is no longer being provided by the tapo integration. If the entity is no longer in use, delete it in settings.”
.

## Debug log

  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2024.4.1",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.6.25-v8-16k+",
    "run_as_root": true
  },
  "custom_components": {
    "lightener": {
      "version": "v2.3.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tapo": {
      "version": "3.1.2",
      "requirements": [
        "plugp100==5.1.3"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tapo",
    "name": "TP-Link Tapo",
    "config_flow": true,
    "version": "3.1.2",
    "iot_class": "local_polling",
    "documentation": "https://github.com/petretiandrea/home-assistant-tapo-p100",
    "issue_tracker": "https://github.com/petretiandrea/home-assistant-tapo-p100/issues",
    "requirements": [
      "plugp100==5.1.3"
    ],
    "dependencies": [
      "network"
    ],
    "dhcp": [
      {
        "registered_devices": true
      }
    ],
    "integration_type": "device",
    "codeowners": [
      "@petretiandrea"
    ],
    "is_built_in": false
  },
  "data": {
    "oui": "40:3F:8C",
    "protocol_name": "Klap V2",
    "raw_state": {
      "device_id": "80232791F446A65C85ABB4AC47858B6B1DB7A71B",
      "fw_ver": "1.3.0 Build 20230831 Rel. 75926",
      "hw_ver": "1.0.0",
      "type": "SMART.TAPOBULB",
      "model": "L530 Series",
      "mac": "40-3F-8C-6A-DB-0E",
      "hw_id": "93F94D88DA9499F43B929DD38EBDF09A",
      "fw_id": "7BECA9DC454565672FEC87D1104F9972",
      "oem_id": "D042998E924F77C9E23A75966003ADD8",
      "specs": "EU",
      "lang": "en_US",
      "device_on": true,
      "on_time": 116,
      "overheated": false,
      "nickname": "TGl2aW5nIFJvb20gVGFwbw==",
      "avatar": "hang_lamp_1",
      "brightness": 80,
      "dynamic_light_effect_enable": false,
      "color_temp": 2585,
      "default_states": {
        "type": "custom",
        "state": {
          "brightness": 80,
          "color_temp": 2585
        }
      },
      "time_diff": 60,
      "region": "Europe/Berlin",
      "longitude": 134316,
      "latitude": 525306,
      "has_set_location_info": true,
      "ip": "192.168.1.42",
      "ssid": "V29lc3R5bkxpbmsyNA==",
      "signal_level": 3,
      "rssi": -45
    },
    "components": {
      "__type": "<class 'plugp100.responses.components.Components'>",
      "repr": "Components(component_list={'device': 2, 'firmware': 1, 'quick_setup': 3, 'inherit': 1, 'time': 1, 'wireless': 1, 'schedule': 2, 'countdown': 2, 'antitheft': 1, 'account': 1, 'synchronize': 1, 'sunrise_sunset': 1, 'brightness': 1, 'color': 1, 'color_temperature': 1, 'auto_light': 1, 'light_effect': 1, 'on_off_gradually': 1, 'cloud_connect': 1, 'default_states': 1, 'preset': 1})"
    },
    "children": []
  }
}

```text

Add your logs here.

```

**Comment by Vantseer** [comment]
I too have encountered this same issue after the 3.1.2 update.

**Comment by haplm** [comment]
I see some struggle even with 3.1.0 (missing attribute hue is still reported, but at least it seems to be possible to control the light)

**Comment by MrSmithCZ** [comment]
I've just tried to add two of my L530 and have encountered the same issues. Tried 3.1.2 update then downgraded to 3.0.0. which works.

**Comment by petretiandrea** [comment]
> ## Version of the integration
> 3.1.2
> 
> ## Configuration
> L530 hw version 1.0 Fw version 1.3
> 
> ```yaml
> Add your logs here.
> ```
> 
> ## Describe the bug
> tapo l530 hw version 1.0 doesn’t work with 3.1.2. It works fine with 3.0.0
> 
> tapo L530 hw version 3.0 works with both 3.1.2 and 3.0
> 
> All combinations of removing/readding/reconfiguring attempted
> 
> the entity says “Unavailable”
> 
> “ This entity is no longer being provided by the tapo integration. If the entity is no longer in use, delete it in settings.” .
> 
> ## Debug log
> "home_assistant": { "installation_type": "Home Assistant Container", "version": "2024.4.1", "dev": false, "hassio": false, "virtualenv": false, "python_version": "3.12.2", "docker": true, "arch": "aarch64", "timezone": "Europe/Berlin", "os_name": "Linux", "os_version": "6.6.25-v8-16k+", "run_as_root": true }, "custom_components": { "lightener": { "version": "v2.3.0", "requirements": [] }, "hacs": { "version": "1.34.0", "requirements": [ "aiogithubapi>=22.10.1" ] }, "tapo": { "version": "3.1.2", "requirements": [ "plugp100==5.1.3" ] } }, "integration_manifest": { "domain": "tapo", "name": "TP-Link Tapo", "config_flow": true, "version": "3.1.2", "iot_class": "local_polling", "documentation": "https://github.com/petretiandrea/home-assistant-tapo-p100", "issue_tracker": "https://github.com/petretiandrea/home-assistant-tapo-p100/issues", "requirements": [ "plugp100==5.1.3" ], "dependencies": [ "network" ], "dhcp": [ { "registered_devices": true } ], "integration_type": "device", "codeowners": [ "@petretiandrea" ], "is_built_in": false }, "data": { "oui": "40:3F:8C", "protocol_name": "Klap V2", "raw_state": { "device_id": "80232791F446A65C85ABB4AC47858B6B1DB7A71B", "fw_ver": "1.3.0 Build 20230831 Rel. 75926", "hw_ver": "1.0.0", "type": "SMART.TAPOBULB", "model": "L530 Series", "mac": "40-3F-8C-6A-DB-0E", "hw_id": "93F94D88DA9499F43B929DD38EBDF09A", "fw_id": "7BECA9DC454565672FEC87D1104F9972", "oem_id": "D042998E924F77C9E23A75966003ADD8", "specs": "EU", "lang": "en_US", "device_on": true, "on_time": 116, "overheated": false, "nickname": "TGl2aW5nIFJvb20gVGFwbw==", "avatar": "hang_lamp_1", "brightness": 80, "dynamic_light_effect_enable": false, "color_temp": 2585, "default_states": { "type": "custom", "state": { "brightness": 80, "color_temp": 2585 } }, "time_diff": 60, "region": "Europe/Berlin", "longitude": 134316, "latitude": 525306, "has_set_location_info": true, "ip": "192.168.1.42", "ssid": "V29lc3R5bkxpbmsyNA==", "signal_level": 3, "rssi": -45 }, "components": { "__type": "<class 'plugp100.responses.components.Components'>", "repr": "Components(component_list={'device': 2, 'firmware': 1, 'quick_setup': 3, 'inherit': 1, 'time': 1, 'wireless': 1, 'schedule': 2, 'countdown': 2, 'antitheft': 1, 'account': 1, 'synchronize': 1, 'sunrise_sunset': 1, 'brightness': 1, 'color': 1, 'color_temperature': 1, 'auto_light': 1, 'light_effect': 1, 'on_off_gradually': 1, 'cloud_connect': 1, 'default_states': 1, 'preset': 1})" }, "children": [] } }
> 
> ```
> 
> Add your logs here.
> ```

Could you post logs?

**Comment by Arkasha-P** [comment]
Обновил интеграцию на последнюю версию в ручную через ssh. 
Просто через git clone скачайте папку tapo в каталог /homeassistant/custom_components
