### ISSUE TITLE
Unable to install package plugp100==5.1.3 after HA update

### ISSUE THREAD

**Issue by PovilasID** [petretiandrea/home-assistant-tapo-p100#756]
## Version of the integration

3.1.2

## Configuration

Device name: General
Firmware: 1.3.0

```yaml
Unable to install package plugp100==5.1.3: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/lib/python3.12/site-packages/tests/integration' Consider using the `--user` option or check the permissions.
```

## Describe the bug

After the update of HA it stopped working.

## Debug log

```text
2024-04-19 11:19:36.961 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package plugp100==5.1.3: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/lib/python3.12/site-packages/tests/integration'
Consider using the `--user` option or check the permissions.
2024-04-19 11:19:36.962 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tapo': Requirements for tapo not found: ['plugp100==5.1.3'].

```

**Comment by PovilasID** [comment]
I did some investigation and discovered that this was related to the fact that I am running HA in docker in non root container if you have `PUID` and or `PGID` defined in docker compose that is what it is. I was not an issue previously and have some benefits but to deal with it there are two fixes:

Quick fix:
Login SSH into your host and run:
```shell
docker exec -it --user=root homeassistant pip3 install plugp100==5.1.3
```
This will update the plugin relies on or:

Permanent fix:
https://github.com/tribut/homeassistant-docker-venv

It is discussed more in: https://github.com/home-assistant/core/issues/24397

**Comment by Arkasha-P** [comment]
Обновил интеграцию на последнюю версию в ручную через ssh. 
Просто через git clone скачайте папку tapo в каталог /homeassistant/custom_components
