### ISSUE TITLE
Invalid Add-on repository!

### ISSUE THREAD

**Issue by Mothamoz** [petretiandrea/home-assistant-tapo-p100#76]
When I try to add https://github.com/petretiandrea/home-assistant-tapo-p100/ as a repository through HACS it always tells me: Invalid Add-on repository!

I've installed the add-on manually for now, but would like to keep it easily updated. 

Best tapo addon out there!

**Comment by petretiandrea** [comment]
I added a video to show the installation steps in the [README.md](https://github.com/petretiandrea/home-assistant-tapo-p100/blob/main/README.md). Try it and report any issue :)

**Comment by Mothamoz** [comment]
Worked, thanks so much! Closing
