### ISSUE TITLE
user and password

### ISSUE THREAD

**Issue by erbarto** [petretiandrea/home-assistant-tapo-p100#764]
since the last update (3.1.2), every 2-3 days I am asked to enter my tp-link user and password.
is this a problem with the integration?

**Comment by Aipoc76** [comment]
same deal, with 1 more addition.  I have 2 Tapo devices, it logs both out.  I can log 1 back in, it resyncs for both, but leave the other error up (the one i didnt log into) and will not go away.

**Comment by m0v1em4n** [comment]
I have just updated and when it came back from a reboot it did the same wanted user and password, which I gave and was ok till later then wanted again think after the device was used

**Comment by ZeBen84** [comment]
I have the same problem, except that even if i don't reconnect, data are still being reported correctly on HA.
Seems like it's just a display bug when the plug lose connection and reconnect/resync with HA.

**Comment by Benvdaa** [comment]
I have the same issues with TP-Link Smart Home Integration in combination with P115 plugs
see: https://github.com/home-assistant/core/issues/116089

I don't have issues with the TP-Link Tapo (hacs) Integration

**Comment by ZeBen84** [comment]
Seems like the plug just try to connect to both Tapo (hacs) and TP Link, so i personnally just reconnected to TP Link and disable both plug, since then only the Tapo (hacs) sensors works and everything works fine.
