### ISSUE TITLE
KE100 not adding

### ISSUE THREAD

**Issue by OrbitMan92** [petretiandrea/home-assistant-tapo-p100#767]
Hello I have successfully added the KH100, my KH100 has a KE100 connected in the Kasa app, but it's not showing the KE100 in home assistant the KH100 is showing as 1 device.

How do I get it to recognise the KE100 I've tried reloading the KH100

**Comment by ss002d6252** [comment]
I'm having the same issue - can't get the KE100 to appear in HA.

**Comment by varton92** [comment]
I'm having the same issue. Seems it correspondent with the last update

**Comment by iambenmitchell** [comment]
Downgrade to 3.0.0 and it will work fine.

**Comment by rxl881** [comment]
This still appears to be an issue. KE100 devices are not discovered in the current release (3.1.4), but (as suggested by @iambenmitchell) everything works well after downgrading to 3.0.0.

**Comment by MakaanPL** [comment]
The fix has already been submitted by someone, but unfortunately Andrea did not accept it yet and haven't prepared a new release of the plugin. No issues were commented or acknowledged by him for months. It seems to me that plugin has no support as of now. I switched to TP-Link integration from official HA repo.
