### ISSUE TITLE
TAPO P100 stuck in installation limbo

### ISSUE THREAD

**Issue by Netesfiu** [petretiandrea/home-assistant-tapo-p100#768]
I've noticed that my TAPO P100 contoller never finishes installing. Re-integrating the device is possible, but `update` sensor remains the same state(see picture). The buttons are disabled and the update never actually finishes. The device is fully functional and has access to the internet as far as I'm aware. Only inconvinience that the update panel is now permanently populated with the device's update alert.

Home assistant information
| # | version |
| :--- | :---: |
| Hardware | rpi4-64 |
| os type | HASS-OS |
| Core | 2024.4.3 |
| Supervisor | 2024.04.0 |
| Operating System | 12.2 |
| UI | 20240404.2 |

TAPO device info:
| # | version |
| :---- | :---- |
| Firmware | 1.4.10 |
| Firmware available | 1.5.5 Build 20230927 rel.40646 |
| Hardware | 1.20.0 |

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/68812986/280a9d9f-9ed9-4f83-bea1-eec01c78a4ef)

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/68812986/23457699-0d7b-487d-b865-0a47d406ba76)

**Comment by ruipalhinhas** [comment]
Same issue as #747

**Comment by lucasstinis** [comment]
Not stale at all, as it's still very much happening up to and including the most current version of HASS Core and OS.
