### ISSUE TITLE
S200B Smart Switch has no Trigger for button press!

### ISSUE THREAD

**Issue by mcatkins** [petretiandrea/home-assistant-tapo-p100#770]
## Version of the integration
Tapo Controller Version: up-to-date on 11/05/2024 (how do I find the version number?)
HACS version: 1.34.0
HA Core Version: 2024.5.3

## Configuration

```yaml
I just attached the device - don't know more yet!
```

## Describe the bug

There is no "Entity"/"trigger" for the button being pressed!
There are only triggers for firmware availability/update and battery fail

I would also expect triggers for turning the smart button, and for double clicking!

## Debug log

```text
No logs yet

```

**Comment by mcatkins** [comment]
This has also been discussed (by others) at:
https://www.reddit.com/r/homeassistant/comments/1avhxci/comment/krakl1z/

**Comment by messum** [comment]
Same issue here, bought a Tapo Hub and Smart Button but only getting a Siren from the Hub and nothing that I can use from the Smart Button.

**Comment by Nishant0127** [comment]
Exactly the same, i am new to HA and thanks to people like petretiandrea for their support, i also brought the S200B thinking the smart button would work seamlessly.. @petretiandrea can you please do something about it and i would like to buy you a coffee, for sure!

**Comment by jcfarsight** [comment]
I've added simple support for this in #784 but I'm a complete beginner to HA development so some peer review would be helpful.

**Comment by pmavrommatis** [comment]
Hello everyone, it would be really useful to have support for Tapo buttons.

**Comment by LordJamesX** [comment]
Looking really forward to the support.  Moving away from Alexa as the central console, more than privacy hate the UI mess in the mobile app, and there is no proper desktop /  webapp replacement to manage tons of devices. Please let us know if anything we can do

**Comment by AdityaChaudhary** [comment]
I'm guessing no updates have been made for this Smart button.
