### ISSUE TITLE
Getting error: Failed to setup cannot connect

### ISSUE THREAD

**Issue by blackthorn87** [petretiandrea/home-assistant-tapo-p100#774]
I'm getting a similar issue that's described in this ticket (https://github.com/petretiandrea/home-assistant-tapo-p100/issues/681). All my Tapo devices were working fine until a few days ago.

My username and password as all fine, I'm not getting any errors with those.

It looks like others are having the same issue: https://community.home-assistant.io/t/tapo-devices-fail-to-connect/675178/8

I'm running the following if that helps:
- HA Hardware: Raspberry Pi 3 B+
- HA Core: 2024.5.5
- HA Supervisor: 2024.05.1
- HA Operating System: 12.3
- Tapo Control Integration: 3.1.2

The devices I'm trying to connect are:
- P100 plugs x4
- L530B blubs x2

Here is the latest error I get in my logs when trying to add a device:

```
This error originated from a custom integration.

Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:143
integration: TP-Link Tapo (documentation, issues)
First occurred: 11:39:02 (1 occurrences)
Last logged: 11:39:02

Failed to setup cannot connect
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 314, in _async_get_device
    device = await connect(config=config, session=session)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/device_factory.py", line 43, in connect
    protocol = await _get_or_guess_protocol(config, session)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/device_factory.py", line 65, in _get_or_guess_protocol
    return await _guess_protocol(config, session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/device_factory.py", line 102, in _guess_protocol
    raise InvalidAuthentication(config.host, config.device_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/errors/invalid_authentication.py", line 3, in __init__
    super(f"Invalid authentication error for ${host}, ${device_type}")
TypeError: super() argument 1 must be a type, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 143, in async_step_user
    device = await self._async_get_device(user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 322, in _async_get_device
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect
```

_Originally posted by @blackthorn87 in https://github.com/petretiandrea/home-assistant-tapo-p100/issues/681#issuecomment-2139278064_

**Comment by MontyPud** [comment]
I'm getting the same thing.  Could it be to do with two factor authentication that is present in the app?

**Comment by blackthorn87** [comment]
> I'm getting the same thing. Could it be to do with two factor authentication that is present in the app?

I've checked in the app and 2-step verification isn't active at the moment. So I don't think it's that.
