### ISSUE TITLE
Getting unexpected exception in log

### ISSUE THREAD

**Issue by kaizersoje** [petretiandrea/home-assistant-tapo-p100#801]
## Version of the integration

3.1.4

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

I can see an error appearing in the log. The integration seems to be loading properly.

## Debug log

```text

Error fetching tapo data: Unexpected exception: <TapoError.ERR_CLOUD_FAILED: -1007>

```

**Comment by kev-kclub** [comment]
V3.1.2 but same issue:

This error originated from a custom integration.

Logger: custom_components.tapo.coordinators
Source: helpers/update_coordinator.py:386
integration: TP-Link Tapo (documentation, issues)
First occurred: 3 October 2024 at 10:44:09 (73 occurrences)
Last logged: 09:19:22

Error fetching tapo data: Unexpected exception:

**Comment by Tau512** [comment]
v3.1.4 on HAOS here.

Logger: custom_components.tapo.coordinators
Source: helpers/update_coordinator.py:386
integration: TP-Link Tapo ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues))
First occurred: 13:00:17 (54 occurrences)
Last logged: 19:00:40
Error fetching tapo data: Unexpected exception:


[HA-tapo-filtered.log](https://github.com/user-attachments/files/17332541/HA-tapo-filtered.log)

**Comment by Paulholloway** [comment]
Integration 3.1.2 
Core 2024.10.2
Supervisor 2024.10.0
Operating System 13.1
Frontend 20241002.3

```
Logger: custom_components.tapo.coordinators
Source: helpers/update_coordinator.py:386
integration: TP-Link Tapo ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues))
First occurred: 07:35:58 (5 occurrences)
Last logged: 07:39:21

Error fetching tapo data: Error tapo exception: Returned unknown error_code: -1402 msg: curr ver:1.5.5 Build 20230927 Rel. 40646, cloud ver:.
Error fetching tapo data: Unexpected exception:
```

**Comment by arhimidis64** [comment]
> Integration 3.1.2 Core 2024.10.2 Supervisor 2024.10.0 Operating System 13.1 Frontend 20241002.3
> 
> ```
> Logger: custom_components.tapo.coordinators
> Source: helpers/update_coordinator.py:386
> integration: TP-Link Tapo ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues))
> First occurred: 07:35:58 (5 occurrences)
> Last logged: 07:39:21
> 
> Error fetching tapo data: Error tapo exception: Returned unknown error_code: -1402 msg: curr ver:1.5.5 Build 20230927 Rel. 40646, cloud ver:.
> Error fetching tapo data: Unexpected exception:
> ```

I have the same error as Paulholloway above with some minor differences:

Logger: custom_components.tapo.coordinators
Source: custom_components/tapo/helpers.py:70
integration: TP-Link Tapo ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues))
First occurred: November 4, 2024 at 13:37:43 (11 occurrences)
Last logged: 13:37:48

Tapo exception: Returned unknown error_code: -1402 msg: curr ver:1.5.5 Build 20230927 Rel. 40646, cloud ver:.

If you need anything let me know.
