### ISSUE TITLE
Installation video is very outdated

### ISSUE THREAD

**Issue by joeinaustin** [petretiandrea/home-assistant-tapo-p100#803]
The installation video seems to be based on a much older version of HA.  I cannot tell if I am installing something incorrectly or if something is broken.  Due to a lack of proper instructions, I cannot get this integration to work.  It fails when installing with unknown error.  I will open a separate issue for this, but the install video needs an update either way.

**Comment by domgiles** [comment]
Agree.... It's a pain to fo it and I'm not sure if I've got the integration installed correctly.
