### ISSUE TITLE
Auto discovery

### ISSUE THREAD

**Issue by petretiandrea** [petretiandrea/home-assistant-tapo-p100#83]
## Automatic discovery
* new automatic discovery using DHCP

**Comment by irsl** [comment]
Hi @petretiandrea,

I implemented a small Python lib to discover Tapo devices over LAN:

https://gist.github.com/irsl/e6b6e635dc8dfba9ea3e8b6263f119c1

I was about to integrate it into your HA repo and send a PR, but going through the HA development learning curve is probably not something I can afford in the close future. If you think this would be useful, feel free to use it.

**Comment by petretiandrea** [comment]
@irsl Thanks for your support, if you want you can try to integrate it in my plugp100 library. Then I will integrate on HA

**Comment by irsl** [comment]
Deal! I'll send you a PR in a week.

**Comment by codyc1515** [comment]
Current

**Comment by petretiandrea** [comment]
I will, I promise ;)

**Comment by codyc1515** [comment]
Current

**Comment by codyc1515** [comment]
Current

**Comment by petretiandrea** [comment]
Available on breaking version 3.0.0
