### ISSUE TITLE
Not able to add intergration via Ui

### ISSUE THREAD

**Issue by m3lvm** [petretiandrea/home-assistant-tapo-p100#88]
After installing Via hacs and restarting Home Assistant, and the going to configuration - Integration - Add New. The tapo integration isn't  found in the list
I followed the Hacs install process shown on your Video to the letter

![HACS - Home Assistant](https://user-images.githubusercontent.com/6518830/141508305-7546792c-ebc0-44ce-875f-0a2a3c02a9a9.jpg)
This is all I get on the Integration page.

![Configuration - Home Assistant](https://user-images.githubusercontent.com/6518830/141507687-d1dcbd5d-99de-4e10-8b7f-13b7560b1cff.jpg)
.

**Comment by petretiandrea** [comment]
What version of HA do you have? Do you have restarted HA after the install process?

**Comment by richardms** [comment]
Hi, I'm seeing the same thing. I'm on a newly setup R-Pi setup using the latest 2021.11.4 build.

I'm currently looking for clues. So far the only one is this line in the logs:

`2021-11-17 21:45:02 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

Which I take to mean that HA has found the directory in custom_components at least.

**Comment by richardms** [comment]
It appeared! I think it might be a browser cache issue. I found it in the list shortly after clearing mine.

**Comment by MrC74rk** [comment]
Can confirm browser cache (Shift + Refresh) fixed the issue.

**Comment by p487morgan** [comment]
@petretiandrea I just found this issue today, after some searching. Perhaps for other newbies, you could add a note to the main README to clear the browser cache after successful install.

Something like HACS do here : https://hacs.xyz/docs/configuration/basic#clear-your-browser-cache

Thanks for the great work 👍 
Paul
